"use client";

// Local-first case journal (piste 2026-09-24 — "module 100% local",
// extension aux autres écrans) — entirely personal data (this user's own
// clinical case notes, RLS-scoped to its author, never read by an admin or
// used to generate content), so there's no cross-user conflict risk at all —
// same low-risk profile as notes/bookmarks, safe to make instant and
// offline-capable. Unlike local-admin-actions.ts's board patches (which can
// fall back to "no cache yet, skip the local patch" since ElProfesorBoard's
// own useOptimistic already covers the current render), this always takes
// the caller's current in-memory entries/notions as the base to persist —
// CaseJournalWithLocalCache's own React state is the single source of truth
// for what's currently shown, and the IndexedDB cache is just kept as a
// mirror of it, so a cache that started empty (e.g. this page's first load
// came from the live server promise, not from a prior sync) never loses
// entries the user can already see on screen.
import { setCachedCaseJournal, enqueuePendingWrite } from "./local-db";
import type { CaseJournalSnapshot } from "./dashboard-types";

type Entries = CaseJournalSnapshot["entries"];
type Notions = CaseJournalSnapshot["notions"];
type Entry = Entries[number];

export function addEntryToList(entries: Entries, entry: Entry): Entries {
  return [entry, ...entries];
}

export function updateEntryInList(entries: Entries, id: string, patch: Partial<Entry>): Entries {
  return entries.map((e) => (e.id === id ? { ...e, ...patch } : e));
}

export function removeEntryFromList(entries: Entries, id: string): Entries {
  return entries.filter((e) => e.id !== id);
}

function notionName(notions: Notions, notionId: string | null): string | null {
  if (!notionId) return null;
  return notions.find((n) => n.id === notionId)?.name ?? null;
}

/** `id` is generated by the caller (crypto.randomUUID()) so the optimistic entry keeps the exact same id once the queued write flushes — see addCaseJournalEntry's doc comment. */
export async function applyLocalAddCaseJournalEntry(
  entries: Entries,
  notions: Notions,
  id: string,
  title: string,
  body: string,
  notionId: string | null
): Promise<Entries> {
  const now = new Date().toISOString();
  const entry: Entry = { id, notionId, notionName: notionName(notions, notionId), title, body, createdAt: now, updatedAt: now };
  const nextEntries = addEntryToList(entries, entry);
  await setCachedCaseJournal({ notions, entries: nextEntries });
  await enqueuePendingWrite({
    id: crypto.randomUUID(),
    kind: "adminAction",
    createdAt: now,
    payload: { action: "caseJournal.add", args: [title, body, notionId, id] },
  });
  return nextEntries;
}

export async function applyLocalUpdateCaseJournalEntry(
  entries: Entries,
  notions: Notions,
  id: string,
  title: string,
  body: string,
  notionId: string | null
): Promise<Entries> {
  const nextEntries = updateEntryInList(entries, id, { title, body, notionId, notionName: notionName(notions, notionId), updatedAt: new Date().toISOString() });
  await setCachedCaseJournal({ notions, entries: nextEntries });
  await enqueuePendingWrite({
    id: crypto.randomUUID(),
    kind: "adminAction",
    createdAt: new Date().toISOString(),
    payload: { action: "caseJournal.update", args: [id, title, body, notionId] },
  });
  return nextEntries;
}

export async function applyLocalDeleteCaseJournalEntry(entries: Entries, notions: Notions, id: string): Promise<Entries> {
  const nextEntries = removeEntryFromList(entries, id);
  await setCachedCaseJournal({ notions, entries: nextEntries });
  await enqueuePendingWrite({
    id: crypto.randomUUID(),
    kind: "adminAction",
    createdAt: new Date().toISOString(),
    payload: { action: "caseJournal.delete", args: [id] },
  });
  return nextEntries;
}
