// Reference protocols, second part: the families of interventions the first
// ones (reference-protocols.ts) don't cover — digestive, vascular, urology,
// gynaecology and obstetrics here; head and neck, eye, neurosurgery, chest,
// limbs, plastic surgery, children and procedures outside the theatre in
// reference-protocols-children.ts. Same rule: a starting point with a named
// source for every dose, to adapt to the service's protocol.

import {
  MANUAL,
  MONITORING,
  PROSPECT_REF,
  ROELANTS,
  cefazolin,
  clindamycinAlt,
  content,
  dexamethasone,
  drug,
  droperidol,
  ketamineSparing,
  ketorolac,
  lidocaineIv,
  metronidazole,
  ondansetron,
  paracetamol,
  pid,
  postop,
  propofolInduction,
  risk,
  rocuronium,
  ropivacaineBlock,
  sufentanil,
  tranexamic,
  type ReferenceProtocol,
} from "./reference-protocol-kit";
import { DEFAULT_PCEA } from "./postop";

// Pieces of this part -----------------------------------------------------------

const ERAS_EL = "ERAS laparotomie en urgence 2021 et 2023 (PMID 33677649, 37277507)";
const ERAS_PD = "ERAS duodénopancréatectomie 2019 (PMID 32161987)";
const ERAS_OESO = "ERAS œsophagectomie 2019 (PMID 30276441)";
const ERAS_GASTRECTOMY = "ERAS gastrectomie 2014 (PMID 25047143)";
const ERAS_CYSTECTOMY = "ERAS cystectomie 2013 (PMID 24189391)";
const ERAS_GYN = "ERAS gynécologie et gynéco-oncologie 2019 (PMID 30877144)";
const ERAS_CS = "ERAS césarienne 2025 (PMID 40335352)";
const ERAS_CRS = "ERAS cytoréduction ± CHIP 2020 (PMID 32873454, 32826114)";
const ESC_2022 = "ESC 2022, chirurgie non cardiaque (PMID 36017553)";

const etomidate = () => drug("Étomidate", "induction", "bolus_iv", { perKg: 0.3 }, "mg", "0,2–0,4 mg/kg : stabilité hémodynamique (manuel, chap. 6) ; dose unique (inhibition surrénalienne).");
const succinylcholine = () => drug("Suxaméthonium (succinylcholine)", "induction", "bolus_iv", { perKg: 1 }, "mg", "1–1,5 mg/kg au poids réel, sans dépasser 150 mg (manuel, chap. 8) ; ou rocuronium 1,2 mg/kg si contre-indication.");
const sugammadex = () => drug("Sugammadex", "other", "bolus_iv", { perKg: 2 }, "mg", "2 mg/kg dès 2 réponses au TOF ; 4 mg/kg en bloc profond ; 16 mg/kg en urgence (manuel, chap. 8).");
const remifentanil = () => drug("Rémifentanil", "maintenance", "pse", { perKg: 0.5 }, "µg", "Bolus 0,2–1 µg/kg ; entretien 0,1–0,5 µg/kg/min (manuel, chap. 7).");
const phenylephrine = (note = "Bolus 50–100 µg, ou perfusion ; noradrénaline en cas de bradycardie.") => drug("Phényléphrine", "haemodynamic", "bolus_iv", { fixed: 100 }, "µg", note);
const noradrenaline = (note = "Perfusion 0,05–0,3 µg/kg/min par voie dédiée, titrée sur la PAM.") => drug("Noradrénaline", "haemodynamic", "pse", { fixed: 8 }, "µg", note);
const morphineIt = (mg: number, note = "") => drug("Morphine intrathécale", "analgesia", "intrathecal", { fixed: mg }, "mg", `${mg * 1000} µg (tableau 13.5 du manuel) ; surveillance respiratoire 24 h.${note ? ` ${note}` : ""}`);
const bupiSpinal = (mg: number, note = "") => drug("Bupivacaïne hyperbare 0,5 %", "alr", "intrathecal", { fixed: mg }, "mg", `Rachianesthésie (manuel, chap. 13).${note ? ` ${note}` : ""}`);
const vancomycinAlt = () => drug("Vancomycine (si allergie immédiate aux bêtalactamines)", "antibio", "perfusion", { perKg: 15, max: 2500 }, "mg", "15–30 mg/kg, maximum 2,5 g, ≥ 60 min (hypotension par histaminolibération) ; à la place de la céfazoline (manuel, chap. 20).");
const heparinVascular = () => drug("Héparine non fractionnée", "haemodynamic", "bolus_iv", { fixed: 5000 }, "UI", "50–100 UI/kg avant le clampage, sur demande du chirurgien ; ACT cible selon l'équipe ; neutralisation par protamine si besoin.");
const PELVIC_POS = "Lithotomie : points d'appui (nerf fibulaire), durée limitée, jambes descendues une à une.";

// Protocols ---------------------------------------------------------------------

export const MORE_REFERENCE_PROTOCOLS: ReferenceProtocol[] = [
  // ============================================================ Digestif et paroi
  {
    id: pid(34),
    name: "Proctologie en ambulatoire (fissure, fistule, abcès, sinus pilonidal)",
    surgery: "Proctologie",
    operation_category: "A",
    hospital: "",
    source: `${PROSPECT_REF("hémorroïdectomie", 2025, "39917290")} (extrapolé) ; ${MANUAL}, chap. 13 et 23.`,
    content: content({
      techniques: ["neuraxial", "general"],
      drugs: [bupiSpinal(5, "Rachianesthésie « en selle » en position assise, 4–6 mg ; ou chloroprocaïne 1 % 40–50 mg pour une sortie rapide."), propofolInduction(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), drug("Ropivacaïne (bloc pudendal ou infiltration)", "alr", "infiltration", { fixed: 75 }, "mg", "0,375 %, 20 mL en fin d'intervention par le chirurgien.")],
      targets: ["Sortie le jour même", "Miction avant la sortie (rétention urinaire)"],
      material: [...MONITORING.slice(0, 4), "Masque laryngé", "Coussin de position (jackknife) ou étriers"],
      risks: [risk("ponv"), { title: "Rétention urinaire", why: "Rachianesthésie, douleur anale, opioïdes, remplissage abondant.", prevention: "Rachianesthésie courte (faible dose, chloroprocaïne), perfusion limitée, pas de morphine intrathécale.", conduct: "Échographie vésicale ; sondage aller-retour si > 500–600 mL." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "urine"] }),
      notes: "Pas d'antibioprophylaxie systématique en proctologie (sauf avis chirurgical). Laxatifs dès J0. Décubitus ventral jackknife : AG avec masque laryngé possible si courte durée, sinon rachianesthésie en selle.",
    }),
  },
  {
    id: pid(35),
    name: "Cure d'éventration et chirurgie pariétale",
    surgery: "Cure d'éventration",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 12 et 30 ; ${PROSPECT_REF("hernie inguinale ouverte", 2011, "21928388")} (extrapolé).`,
    content: content({
      techniques: ["general", "superficial_block", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ketamineSparing(), ropivacaineBlock(150, "TAP ou bloc des grands droits bilatéral")],
      targets: ["Curarisation profonde pour la fermeture", "Pressions de ventilation surveillées à la fermeture (hyperpression abdominale)"],
      material: [...MONITORING, "Curarimètre (TOF)", "Échographe"],
      risks: [risk("ponv"), { title: "Hyperpression abdominale à la fermeture", why: "Réintégration d'un contenu volumineux (perte de domicile).", prevention: "Curarisation profonde, mesure des pressions de plateau avant et après fermeture.", conduct: "Pressions de plateau qui montent, hypotension, oligurie : prévenir le chirurgien (fermeture sans tension, plaque)." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "urine"] }),
      notes: "Grande éventration : péridurale thoracique ou blocs de paroi continus. Cœlioscopie : pneumopéritoine (voir les spécificités de l'intervention).",
    }),
  },
  {
    id: pid(36),
    name: "Laparotomie en urgence (occlusion, péritonite, perforation)",
    surgery: "Laparotomie pour occlusion",
    operation_category: "A",
    hospital: "",
    source: `${ERAS_EL} ; ${MANUAL}, chap. 20, 21 et 39 (estomac plein).`,
    content: content({
      techniques: ["general"],
      drugs: [etomidate(), drug("Kétamine", "induction", "bolus_iv", { perKg: 1 }, "mg", "1–2 mg/kg en cas d'instabilité (choc septique ou hypovolémique) (manuel, chap. 6)."), sufentanil(0.2), drug("Rocuronium (séquence rapide)", "induction", "bolus_iv", { perKg: 1.2, basis: "total" }, "mg", "1,2 mg/kg ; sugammadex 16 mg/kg prêt."), succinylcholine(), sugammadex(), cefazolin("Céfazoline 2 g + métronidazole 500 mg ; péritonite : antibiothérapie curative déjà en cours ?"), metronidazole(), noradrenaline(), paracetamol()],
      targets: ["Séquence rapide, aspiration de la sonde gastrique avant l'induction", "PAM ≥ 65 mmHg, lactates, diurèse ≥ 0,5 mL/kg/h", "Remplissage guidé (réponse au remplissage) ; pas de surcharge"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale si vasopresseurs", "Sonde gastrique", "Vidéolaryngoscope", "Réchauffeur de liquides"],
      risks: [risk("aspiration"), risk("induction_hypotension"), risk("hypothermia"), risk("bleeding")],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "urine", "temperature", "delirium"] }),
      notes: "ERAS urgences : évaluation et traitement du sepsis avant l'incision (antibiotiques, remplissage, source), score de risque (NELA/P-POSSUM) pour décider de la destination. Péridurale rarement possible (sepsis, coagulation).",
    }),
  },
  {
    id: pid(37),
    name: "Gastrectomie (ouverte, cœlioscopie ou robot)",
    surgery: "Gastrectomie",
    operation_category: "A",
    hospital: "",
    source: `${ERAS_GASTRECTOMY} ; ${MANUAL}, chap. 12 et 30.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketamineSparing(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "T6–T8, test puis 5–10 mL ; PCEA ensuite (voie ouverte)."), noradrenaline()],
      targets: ["Normothermie", "Euvolémie (objectif de remplissage)", "Séquence rapide si sténose ou gastroparésie"],
      material: [...MONITORING, "Cathéter artériel", "Sonde gastrique", "Curarimètre (TOF)"],
      risks: [risk("aspiration"), risk("hypothermia"), risk("bleeding"), risk("ponv")],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "urine", "glucose"] }),
      notes: "Cœlioscopie ou robot : pas de péridurale, analgésie multimodale et blocs de paroi. Dénutrition : assistance nutritionnelle préopératoire (ERAS).",
    }),
  },
  {
    id: pid(38),
    name: "Œsophagectomie (Ivor Lewis, thoracoscopie, robot)",
    surgery: "Œsophagectomie",
    operation_category: "A",
    hospital: "",
    source: `${ERAS_OESO} ; ${MANUAL}, chap. 26.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(0.3), rocuronium(), cefazolin(), dexamethasone(8), paracetamol(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "T5–T7 : couvre laparotomie et thoracotomie ; PCEA ensuite."), noradrenaline(), ketamineSparing()],
      targets: ["Séquence rapide (reflux, achalasie)", "Ventilation unipulmonaire protectrice (Vt 4–6 mL/kg de poids idéal, PEP)", "Remplissage restrictif, PAM ≥ 65 mmHg par vasopresseur", "Extubation au bloc si possible"],
      material: [...MONITORING, "Sonde double lumière gauche", "Fibroscope", "Cathéter artériel", "Voie veineuse centrale", "Sonde urinaire"],
      risks: [risk("aspiration"), risk("hypothermia"), { title: "Hypoxémie en ventilation unipulmonaire", why: "Shunt par le poumon exclu.", prevention: "Sonde vérifiée au fibroscope après chaque mobilisation, PEP au poumon ventilé.", conduct: "FiO₂ 100 %, revérifier la sonde, recrutement, CPAP au poumon exclu, réventilation intermittente." }, risk("bleeding")],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "urine", "temperature", "delirium"] }),
      notes: "Fistule anastomotique : éviter hypotension et surcharge. Kinésithérapie respiratoire et mobilisation précoces.",
    }),
  },
  {
    id: pid(39),
    name: "Chirurgie sus-mésocolique par cœlioscopie (fundoplicature, Heller, rate, surrénale)",
    surgery: "Fundoplicature / cure de hernie hiatale",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 30 (cœlioscopie) ; ${PROSPECT_REF("cholécystectomie", 2024, "39129451")} (extrapolé).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), droperidol(), paracetamol(), ketorolac(), drug("Ropivacaïne (infiltration des orifices)", "alr", "infiltration", { fixed: 75 }, "mg", "0,375 %, 20 mL en fin d'intervention.")],
      targets: ["Pneumopéritoine à basse pression (≤ 12 mmHg)", "Curarisation profonde pendant le pneumopéritoine", "Proclive : PAM surveillée (baisse du retour veineux)"],
      material: [...MONITORING, "Curarimètre (TOF)", "Sonde gastrique (calibrage pour la fundoplicature)"],
      risks: [risk("ponv"), risk("gas_embolism"), { title: "Pneumothorax ou pneumomédiastin (dissection hiatale)", why: "Brèche pleurale lors de la dissection du hiatus.", prevention: "Pressions de ventilation et EtCO₂ surveillées.", conduct: "Désaturation, pressions qui montent : prévenir le chirurgien, baisser l'insufflation, PEP ; exsufflation en fin d'intervention, drain rarement." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", watch: ["pain"] }),
      notes: "Achalasie (Heller) : œsophage plein, séquence rapide tête surélevée après vidange. Splénectomie : vaccinations au moins 2 semaines avant ; plaquettes si thrombopénie. Surrénalectomie pour phéochromocytome : protocole dédié.",
    }),
  },
  {
    id: pid(40),
    name: "Chirurgie du pancréas (duodénopancréatectomie, pancréatectomie gauche)",
    surgery: "Duodénopancréatectomie céphalique",
    operation_category: "A",
    hospital: "",
    source: `${ERAS_PD} ; ${MANUAL}, chap. 12 et 21.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(0.3), rocuronium(), cefazolin(), metronidazole(), dexamethasone(8), ondansetron(), paracetamol(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "T6–T8 ; ou cathéters pariétaux (alternative à la péridurale, ERAS 2019)."), noradrenaline(), tranexamic()],
      targets: ["Normothermie (preuve forte, ERAS 2019)", "Glycémie 6–10 mmol/L", "Euvolémie, PAM ≥ 65 mmHg"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "Sonde urinaire", "Réchauffeur de liquides"],
      risks: [risk("bleeding"), risk("hypothermia"), risk("ponv")],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "glucose", "urine", "hb"] }),
      notes: "Ictère : coagulation, fonction rénale, drainage biliaire préalable selon l'équipe. Perte de poids > 15 % : nutrition préopératoire (ERAS). Péridurale : hypotension fréquente, vasopresseur plutôt que remplissage.",
    }),
  },
  {
    id: pid(41),
    name: "Chirurgie rectale et pelvienne majeure",
    surgery: "Résection du rectum",
    operation_category: "A",
    hospital: "",
    source: `${PROSPECT_REF("chirurgie colorectale ouverte", 2024, "38420876")} ; ERAS colorectal 2025 (PMID 40783294) ; ${MANUAL}, chap. 19 et 30.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), metronidazole(), dexamethasone(8), ondansetron(), paracetamol(), lidocaineIv(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "Voie ouverte : T9–T11 ; en cœlioscopie ou robot, analgésie multimodale sans péridurale.")],
      targets: ["Trendelenburg marqué et lithotomie : pressions de ventilation, œdème facial", "Normothermie, euvolémie", "Curarisation profonde en cœlioscopie ou robot"],
      material: [...MONITORING, "Cathéter artériel si terrain ou chirurgie longue", "Sonde urinaire", "Curarimètre (TOF)", "Matelas anti-glissement"],
      risks: [risk("hypothermia"), risk("bleeding"), risk("ponv"), { title: "Lithotomie et Trendelenburg prolongés", why: "Compression nerveuse (fibulaire), syndrome des loges des jambes, œdème de la face et des voies aériennes.", prevention: PELVIC_POS, conduct: "Durée > 4 h : vérifier les appuis, test de fuite avant l'extubation." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "nsaid", "opioid_titration"], thrombo: "lmwh_mechanical", thromboDays: 28, watch: ["pain", "urine", "glucose"] }),
      notes: "Cancer : thromboprophylaxie prolongée 28 jours. Pas de lidocaïne IV avec une péridurale active.",
    }),
  },
  {
    id: pid(42),
    name: "Chirurgie de cytoréduction avec CHIP",
    surgery: "Chirurgie de cytoréduction et CHIP",
    operation_category: "A",
    hospital: "",
    source: `${ERAS_CRS} ; ${MANUAL}, chap. 21 et 40.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(0.3), rocuronium(), cefazolin(), metronidazole(), dexamethasone(8), paracetamol(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "T8–T10, si coagulation normale."), noradrenaline(), tranexamic()],
      targets: ["Pendant la CHIP (41–43 °C) : température centrale ≤ 39 °C, refroidir activement", "Diurèse ≥ 1 mL/kg/h pendant la CHIP (néphrotoxicité du cisplatine)", "Coagulation surveillée (thromboélastométrie si disponible)"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "Sonde urinaire", "Monitorage du débit cardiaque", "Réchauffeur et matelas refroidissant"],
      risks: [risk("bleeding"), { title: "Hyperthermie et instabilité pendant la CHIP", why: "Perfusion intrapéritonéale chaude : vasodilatation, tachycardie, hausse de la consommation d'O₂, pression abdominale.", prevention: "Refroidissement actif, remplissage anticipé, diurèse suivie.", conduct: "T° > 39 °C : couvertures froides, liquides froids ; hypotension : remplissage puis vasopresseur." }, risk("hypothermia")],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "urine", "hb", "potassium", "temperature"] }),
      notes: "ERAS CRS-CHIP : pas de consensus sur le plasma frais congelé préventif. Pertes hydriques et protéiques majeures.",
    }),
  },
  {
    id: pid(43),
    name: "Surrénalectomie pour phéochromocytome",
    surgery: "Surrénalectomie",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 17 (endocrinopathies) et 30.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), cefazolin(), drug("Nicardipine", "haemodynamic", "pse", { fixed: 1 }, "mg", "Bolus 0,5–1 mg puis 1–5 mg/h lors des pics hypertensifs (manipulation de la tumeur)."), drug("Esmolol", "haemodynamic", "bolus_iv", { fixed: 20 }, "mg", "Tachycardie, seulement après l'alpha-blocage."), drug("Magnésium", "haemodynamic", "perfusion", { perKg: 40 }, "mg", "40–50 mg/kg : atténue les pics catécholaminergiques."), noradrenaline("Après la ligature de la veine surrénalienne : chute de pression attendue, noradrénaline prête."), paracetamol()],
      targets: ["Préparation : alpha-bloquant 10–14 jours, puis bêta-bloquant si tachycardie", "PAM stable : vasodilatateurs avant la ligature, vasopresseur après", "Glycémie après exérèse (hypoglycémie)"],
      material: [...MONITORING, "Cathéter artériel avant l'induction", "Voie veineuse centrale", "Seringues de nicardipine et de noradrénaline prêtes"],
      risks: [{ title: "Crise hypertensive", why: "Libération de catécholamines à l'induction, à l'intubation, à l'insufflation et à la manipulation de la tumeur.", prevention: "Alpha-blocage préopératoire, induction profonde, rémifentanil, pas de kétamine ni d'éphédrine.", conduct: "Nicardipine ou nitroprussiate, approfondir ; prévenir le chirurgien (arrêt de la manipulation)." }, { title: "Hypotension après la ligature", why: "Chute brutale des catécholamines, vasoplégie.", prevention: "Remplissage anticipé, noradrénaline prête.", conduct: "Remplissage, noradrénaline, parfois vasopressine ; hydrocortisone si surrénalectomie bilatérale." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", watch: ["pain", "glucose"] }),
      notes: "Autres surrénalectomies (Cushing, Conn) : corticothérapie substitutive pour le Cushing, kaliémie pour le Conn.",
    }),
  },
  {
    id: pid(44),
    name: "Petite chirurgie superficielle et accès vasculaires",
    surgery: "Exérèse cutanée",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 11 (anesthésiques locaux) et 22 (sédation).`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [drug("Lidocaïne 1 % adrénalinée (infiltration)", "alr", "infiltration", { fixed: 200 }, "mg", "Par le chirurgien ; maximum 7 mg/kg avec adrénaline, 4,5 mg/kg sans (manuel, chap. 11)."), drug("Propofol (sédation)", "maintenance", "pse", { fixed: 20 }, "mg", "Titré par bolus de 10–20 mg ou AIVOC 1–2 µg/mL."), drug("Rémifentanil (sédation)", "maintenance", "pse", { fixed: 20 }, "µg", "0,02–0,05 µg/kg/min en ventilation spontanée (manuel, chap. 7)."), paracetamol()],
      targets: ["Ventilation spontanée, SpO₂ ≥ 94 %", "Patient réveillable"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (capnographie nasale)", "Lunettes à O₂", "Masque laryngé prêt"],
      risks: [risk("last"), { title: "Dépression respiratoire sous sédation", why: "Association propofol et opioïde.", prevention: "Titration, capnographie.", conduct: "Stimuler, subluxation, O₂ ; masque et ventilation, réduire la sédation." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie pour la chirurgie cutanée propre ; chambre implantable selon le protocole local. Chambre implantable, cathéter de dialyse : échoguidage, radiographie de contrôle (pneumothorax). Mélanome ou ganglion : technique du ganglion sentinelle (bleu : allergie, fausse désaturation).",
    }),
  },
  {
    id: pid(45),
    name: "Transplantation hépatique ou pancréatique",
    surgery: "Transplantation hépatique",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 21, 40 et 41 ; protocole du centre de transplantation.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(1.5), sufentanil(0.3), drug("Rocuronium (séquence rapide)", "induction", "bolus_iv", { perKg: 1.2 }, "mg", "Ascite, estomac plein fréquent."), noradrenaline(), drug("Calcium (chlorure)", "haemodynamic", "bolus_iv", { fixed: 1 }, "g", "Hypocalcémie de la transfusion massive (citrate)."), tranexamic(), cefazolin("Antibioprophylaxie selon le protocole du centre de transplantation.")],
      targets: ["Coagulation guidée par thromboélastométrie", "Kaliémie avant la reperfusion (hyperkaliémie)", "Normothermie, glycémie"],
      material: [...MONITORING, "Deux cathéters artériels", "Voie veineuse centrale à gros débit", "Monitorage du débit cardiaque et ETO", "Accélérateur-réchauffeur de transfusion", "Récupérateur de sang"],
      risks: [risk("bleeding"), risk("hyperkalaemia"), { title: "Syndrome de reperfusion", why: "Libération du contenu froid, acide et riche en potassium du greffon au déclampage.", prevention: "Kaliémie et calcémie corrigées, vasopresseur prêt.", conduct: "Hypotension, bradycardie, arythmie : calcium, adrénaline par petits bolus, correction du potassium." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "mechanical", watch: ["pain", "glucose", "potassium", "hb", "urine"] }),
      notes: "Chirurgie de centre spécialisé : ce protocole résume les points d'anesthésie, le protocole du centre prévaut.",
    }),
  },

  // ============================================================ Vasculaire
  {
    id: pid(46),
    name: "Chirurgie aortique ouverte (anévrisme, pontage aorto-bifémoral)",
    surgery: "Chirurgie aortique ouverte",
    operation_category: "A",
    hospital: "",
    source: `${ESC_2022} ; ${MANUAL}, chap. 28 (chirurgie vasculaire).`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [etomidate(), sufentanil(0.3), rocuronium(), cefazolin(), vancomycinAlt(), heparinVascular(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "T8–T10, posée la veille ou avant l'induction ; délai avec l'héparine (ESAIC/ASRA)."), drug("Nicardipine", "haemodynamic", "pse", { fixed: 1 }, "mg", "Au clampage : hypertension d'amont."), noradrenaline("Au déclampage : chute de pression, remplissage anticipé et noradrénaline."), tranexamic(), paracetamol()],
      targets: ["Clampage : contrôle de l'hypertension (vasodilatateur, approfondir)", "Déclampage : remplissage anticipé, déclampage progressif", "Diurèse, lactates, normothermie"],
      material: [...MONITORING, "Cathéter artériel avant l'induction", "Voie veineuse centrale", "Sonde urinaire", "Récupérateur de sang", "Accélérateur-réchauffeur de transfusion"],
      risks: [risk("bleeding"), { title: "Ischémie myocardique", why: "Coronaropathie fréquente (ESC 2022 : chirurgie à haut risque), contraintes du clampage.", prevention: "Bêtabloquant poursuivi, fréquence cardiaque et PAM contrôlées, anémie évitée.", conduct: "Sus-décalage ou sous-décalage ST : optimiser fréquence, pression, Hb ; troponine postopératoire." }, risk("hypothermia"), { title: "Insuffisance rénale et ischémie digestive", why: "Clampage suprarénal, hypovolémie, embols.", prevention: "Durée de clampage limitée, perfusion rénale maintenue.", conduct: "Diurèse, créatinine, lactates ; colite ischémique à rechercher." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "troponin", "urine", "hb"] }),
      notes: "Anévrisme rompu : hypotension permissive (PAS 70–90 mmHg) jusqu'au clampage, induction au bloc champ prêt, transfusion massive.",
    }),
  },
  {
    id: pid(47),
    name: "Endoprothèse aortique (EVAR, TEVAR)",
    surgery: "Endoprothèse aortique",
    operation_category: "A",
    hospital: "",
    source: `${ESC_2022} ; ${MANUAL}, chap. 28.`,
    content: content({
      techniques: ["general", "neuraxial", "sedation"],
      drugs: [propofolInduction(1.5), sufentanil(), rocuronium(), cefazolin(), heparinVascular(), drug("Lidocaïne 1 % (infiltration fémorale)", "alr", "infiltration", { fixed: 200 }, "mg", "Voie percutanée sous anesthésie locale et sédation possible."), noradrenaline(), paracetamol()],
      targets: ["PAM stable pendant le déploiement (hypotension contrôlée brève si demandée)", "Fonction rénale : produit de contraste limité, hydratation", "TEVAR : drainage du LCS et PAM ≥ 80–90 mmHg si risque médullaire"],
      material: [...MONITORING, "Cathéter artériel (bras gauche si TEVAR)", "Sonde urinaire", "Protection contre les rayons X"],
      risks: [risk("bleeding"), { title: "Ischémie médullaire (TEVAR)", why: "Couverture des artères intercostales.", prevention: "Drainage du LCS si couverture étendue, PAM élevée.", conduct: "Déficit des membres inférieurs au réveil : PAM > 90 mmHg, drainage du LCS, avis urgent." }, { title: "Conversion en chirurgie ouverte", why: "Rupture ou échec du déploiement.", prevention: "Salle et produits sanguins prêts.", conduct: "AG rapide, transfusion, clampage." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol"], thrombo: "lmwh", watch: ["pain", "urine", "neuro"] }),
      notes: "Endoprothèse fenêtrée ou branchée : procédure longue, AG, risque rénal et médullaire plus élevé.",
    }),
  },
  {
    id: pid(48),
    name: "Endartériectomie carotidienne",
    surgery: "Endartériectomie carotidienne",
    operation_category: "A",
    hospital: "",
    source: `${ESC_2022} ; ${MANUAL}, chap. 28 ; GALA (AG ou locorégionale : pas de différence de résultat).`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [propofolInduction(1.5), remifentanil(), rocuronium(), cefazolin(), heparinVascular(), ropivacaineBlock(100, "bloc cervical superficiel ou intermédiaire"), phenylephrine("Clampage : PAM maintenue 10–20 % au-dessus de la valeur de base."), drug("Nicardipine", "haemodynamic", "pse", { fixed: 1 }, "mg", "Hypertension après déclampage (syndrome d'hyperperfusion)."), paracetamol()],
      targets: ["Clampage : PAM de base + 10–20 %", "Surveillance neurologique : patient éveillé (locorégionale) ou NIRS/potentiels/pression résiduelle (AG)", "Réveil rapide pour l'examen neurologique"],
      material: [...MONITORING, "Cathéter artériel", "NIRS cérébrale (AG)", "Échographe (bloc cervical)"],
      risks: [{ title: "Ischémie cérébrale au clampage", why: "Suppléance controlatérale insuffisante.", prevention: "PAM élevée au clampage, shunt selon la surveillance.", conduct: "Déficit (éveillé) ou chute de la NIRS : augmenter la PAM, shunt, prévenir le chirurgien." }, { title: "Hématome cervical compressif", why: "Saignement sous héparine et antiagrégants.", prevention: "Hémostase, PA contrôlée au réveil.", conduct: "Dyspnée, stridor : ouverture de la plaie au lit, intubation difficile à prévoir (vidéolaryngoscope, fibroscope)." }, { title: "Instabilité hémodynamique (sinus carotidien)", why: "Stimulation du barorécepteur.", prevention: "Infiltration du sinus par le chirurgien.", conduct: "Bradycardie, hypotension : arrêt de la stimulation, atropine, phényléphrine." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol"], thrombo: "lmwh", watch: ["neuro", "pain"] }),
      notes: "Antiagrégant poursuivi. Stenting carotidien : sédation légère, atropine prête (bradycardie à l'inflation du ballon).",
    }),
  },
  {
    id: pid(49),
    name: "Revascularisation des membres inférieurs",
    surgery: "Pontage fémoro-poplité ou distal",
    operation_category: "A",
    hospital: "",
    source: `${ESC_2022} ; ${MANUAL}, chap. 12, 13 et 28 ; ESAIC/ASRA : délais des antithrombotiques avant ALR.`,
    content: content({
      techniques: ["neuraxial", "general", "superficial_block"],
      drugs: [bupiSpinal(12), propofolInduction(1.5), sufentanil(), cefazolin(), heparinVascular(), ropivacaineBlock(150, "fascia iliaca ou fémoral"), paracetamol()],
      targets: ["PAM stable (coronaropathie associée)", "Normothermie", "Antiagrégants poursuivis ; délais des anticoagulants respectés avant la rachianesthésie"],
      material: [...MONITORING, "Cathéter artériel selon le terrain", "Échographe"],
      risks: [risk("bleeding"), risk("spinal_hypotension"), { title: "Ischémie myocardique", why: "Artériopathie : coronaropathie très fréquente.", prevention: "Bêtabloquant et statine poursuivis, pas d'hypotension ni de tachycardie.", conduct: "Optimiser pression, fréquence, Hb ; troponine postopératoire." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "perineural"], thrombo: "lmwh", watch: ["pain", "troponin"] }),
      notes: "Ischémie aiguë (embolectomie) : urgence, souvent sous héparine : AG ou anesthésie locale ; revascularisation : hyperkaliémie et acidose de reperfusion.",
    }),
  },
  {
    id: pid(50),
    name: "Amputation de membre inférieur",
    surgery: "Amputation de membre inférieur",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 12, 13 et 25 ; ESAIC/ASRA pour les délais des antithrombotiques.`,
    content: content({
      techniques: ["neuraxial", "superficial_block", "general"],
      drugs: [bupiSpinal(12), ropivacaineBlock(150, "sciatique et fémoral, cathéter périnerveux"), propofolInduction(1.5), cefazolin("Céfazoline ; infection en cours : antibiothérapie adaptée au germe."), paracetamol(), ketamineSparing()],
      targets: ["ALR périnerveuse continue : prévention des douleurs du membre fantôme", "PAM stable (terrain vasculaire, diabète, insuffisance rénale)"],
      material: [...MONITORING, "Échographe", "Cathéter périnerveux"],
      risks: [risk("spinal_hypotension"), { title: "Douleur de membre fantôme", why: "Douleur préopératoire intense et prolongée.", prevention: "Analgésie préopératoire efficace, cathéter périnerveux, kétamine.", conduct: "Analgésie multimodale, avis de l'équipe douleur." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "perineural", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "glucose"] }),
      notes: "Pied diabétique ou amputation mineure : bloc de cheville ou poplité seul. Infection : pas de rachianesthésie si sepsis.",
    }),
  },
  {
    id: pid(51),
    name: "Fistule artério-veineuse et accès de dialyse",
    surgery: "Fistule artério-veineuse",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 12 et 32 (insuffisance rénale).`,
    content: content({
      techniques: ["superficial_block", "sedation"],
      drugs: [ropivacaineBlock(150, "bloc axillaire ou supraclaviculaire"), drug("Propofol (sédation)", "maintenance", "pse", { fixed: 20 }, "mg", "Titré par bolus de 10–20 mg."), paracetamol()],
      targets: ["Bloc du plexus brachial : vasodilatation, meilleure perméabilité de la fistule", "Kaliémie du jour < 5,5 mmol/L", "Pas de brassard ni de perfusion sur le bras de la fistule"],
      material: ["ECG", "PNI (autre bras)", "SpO₂", "Échographe"],
      risks: [risk("hyperkalaemia"), risk("last")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Antibioprophylaxie : céfazoline pour une prothèse (pontage prothétique), pas pour une fistule native. Dialyse la veille ; pas d'AINS ; succinylcholine seulement si kaliémie normale ; doses adaptées à la fonction rénale.",
    }),
  },
  {
    id: pid(52),
    name: "Chirurgie des varices",
    surgery: "Chirurgie des varices",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 11 et 22.`,
    content: content({
      techniques: ["sedation", "neuraxial", "general"],
      drugs: [drug("Lidocaïne 0,1 % (anesthésie par tumescence)", "alr", "infiltration", { fixed: 350 }, "mg", "Par le chirurgien, adrénalinée diluée ; maximum 7 mg/kg."), drug("Propofol (sédation)", "maintenance", "pse", { fixed: 20 }, "mg", "Titré ; AIVOC 1–2 µg/mL."), paracetamol(), ketorolac()],
      targets: ["Sortie le jour même", "Compression et marche précoce"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (capnographie nasale)"],
      risks: [risk("last")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", thromboDays: 7, watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie (chirurgie propre superficielle). Stripping classique : rachianesthésie courte ou AG avec masque laryngé.",
    }),
  },

  // ============================================================ Urologie
  {
    id: pid(53),
    name: "Néphrectomie totale ou partielle",
    surgery: "Néphrectomie",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}, chap. 19 (lombotomie), 30 (cœlioscopie) et 33 (urologie).`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), drug("Ropivacaïne 0,2 % (péridurale ou paravertébral)", "alr", "peridural", { fixed: 10 }, "mg", "Lombotomie : péridurale T8–T10 ou paravertébral ; cœlioscopie ou robot : blocs de paroi (ESP, TAP) et infiltration."), tranexamic()],
      targets: ["Décubitus latéral avec billot : PAM (compression cave), appuis", "Néphrectomie partielle : clampage de l'artère rénale court, mannitol selon l'équipe", "Pas d'AINS (rein unique ou partiel)"],
      material: [...MONITORING, "Cathéter artériel si partielle ou gros rein", "Sonde urinaire", "Deux voies veineuses"],
      risks: [risk("bleeding"), { title: "Plaie pleurale (lombotomie)", why: "Incision haute proche de la plèvre.", prevention: "Pressions de ventilation surveillées.", conduct: "Pneumothorax : exsufflation par le chirurgien, drain selon la taille." }, risk("ponv")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "urine", "hb"] }),
      notes: "Tumeur avec thrombus cave : chirurgie de centre (CEC possible). Fonction rénale postopératoire à suivre.",
    }),
  },
  {
    id: pid(54),
    name: "Cystectomie radicale",
    surgery: "Cystectomie totale",
    operation_category: "J2",
    hospital: "",
    source: `${ERAS_CYSTECTOMY} ; ${MANUAL}, chap. 30 et 33.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), metronidazole(), dexamethasone(8), paracetamol(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "Voie ouverte T10 ; robot : morphine intrathécale ou blocs de paroi."), tranexamic(), noradrenaline()],
      targets: ["Remplissage guidé (Doppler œsophagien : moins de morbidité, ERAS 2013)", "Robot : Trendelenburg marqué prolongé (œdème, pressions)", "Normothermie"],
      material: [...MONITORING, "Cathéter artériel", "Monitorage du débit cardiaque", "Réchauffeur de liquides"],
      risks: [risk("bleeding"), risk("hypothermia"), { title: "Iléus postopératoire", why: "Dérivation urinaire intestinale, opioïdes.", prevention: "Retrait précoce de la sonde gastrique, gomme à mâcher, prévention des NVPO, chirurgie mini-invasive (ERAS).", conduct: "Alimentation progressive, correction des électrolytes." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", thromboDays: 28, watch: ["pain", "urine", "potassium", "hb"] }),
      notes: "ERAS : pas de préparation colique. Pas de diurèse mesurable pendant la dérivation : l'euvolémie se juge sur les autres signes.",
    }),
  },
  {
    id: pid(55),
    name: "Endo-urologie (urétéroscopie, cystoscopie, résection de vessie)",
    surgery: "Urétéroscopie",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}, chap. 13 et 33.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), drug("Alfentanil", "induction", "bolus_iv", { perKg: 10 }, "µg", "10–40 µg/kg ; geste court (manuel, chap. 7)."), bupiSpinal(7.5, "Rachianesthésie basse si terrain respiratoire."), drug("Céfuroxime", "antibio", "bolus_iv", { fixed: 1.5 }, "g", "Urine stérile avant le geste (ECBU) ; sinon antibiothérapie adaptée."), dexamethasone(4), ondansetron(), paracetamol()],
      targets: ["Masque laryngé, ventilation spontanée ou contrôlée", "Résection de vessie latérale : curarisation (réflexe obturateur)"],
      material: [...MONITORING.slice(0, 4), "Masque laryngé", "Étriers (lithotomie)"],
      risks: [{ title: "Réflexe obturateur (résection de vessie latérale)", why: "Stimulation du nerf obturateur par le courant : adduction brutale, perforation vésicale.", prevention: "Curarisation sous AG, ou bloc obturateur échoguidé sous rachianesthésie.", conduct: "Perforation : prévenir le chirurgien, douleur abdominale ou scapulaire, laparotomie si intrapéritonéale." }, { title: "Sepsis urinaire", why: "Obstacle infecté, manipulation.", prevention: "ECBU préopératoire, antibiothérapie.", conduct: "Fièvre, hypotension : hémocultures, antibiotiques, remplissage." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "urine"] }),
      notes: "Colique néphrétique : AINS efficaces. Laser : lunettes de protection.",
    }),
  },
  {
    id: pid(56),
    name: "Néphrolithotomie percutanée",
    surgery: "Néphrolithotomie percutanée",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}, chap. 19 et 33.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), drug("Céfuroxime", "antibio", "bolus_iv", { fixed: 1.5 }, "g", "ECBU stérile ; sinon traitement adapté."), dexamethasone(8), ondansetron(), paracetamol(), ropivacaineBlock(100, "paravertébral ou ESP homolatéral"), tranexamic()],
      targets: ["Décubitus ventral : yeux, visage, abdomen libres, sonde bien fixée", "Normothermie (liquide d'irrigation)"],
      material: [...MONITORING, "Sonde armée", "Coussins de décubitus ventral", "Réchauffeur d'irrigation"],
      risks: [risk("bleeding"), { title: "Plaie pleurale (accès supérieur)", why: "Ponction au-dessus de la 12e côte.", prevention: "Pressions de ventilation surveillées.", conduct: "Désaturation, pressions qui montent : hydrothorax ou pneumothorax, drain." }, { title: "Absorption du liquide d'irrigation, sepsis", why: "Pression intrarénale, calcul infecté.", prevention: "Pression d'irrigation basse, antibiotiques.", conduct: "Fièvre, frissons, hypotension au réveil : hémocultures, antibiotiques, remplissage." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "hb", "temperature"] }),
      notes: "Retournement en décubitus ventral après l'intubation : vérifier la position de la sonde.",
    }),
  },
  {
    id: pid(57),
    name: "Chirurgie des bourses et de la verge",
    surgery: "Chirurgie scrotale",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}, chap. 12, 13 et 33.`,
    content: content({
      techniques: ["general", "neuraxial", "superficial_block"],
      drugs: [propofolInduction(), drug("Alfentanil", "induction", "bolus_iv", { perKg: 10 }, "µg", "Geste court."), bupiSpinal(7.5), drug("Ropivacaïne (bloc du cordon ou pénien)", "alr", "infiltration", { fixed: 75 }, "mg", "0,375 %, par le chirurgien ou échoguidé."), cefazolin("Seulement pour les prothèses (implant pénien, sphincter)."), dexamethasone(4), paracetamol(), ketorolac()],
      targets: ["Masque laryngé", "Traction du cordon : bradycardie vagale possible"],
      material: [...MONITORING.slice(0, 4), "Masque laryngé"],
      risks: [risk("ponv"), { title: "Réflexe vagal (traction du cordon)", why: "Stimulation vagale.", prevention: "Profondeur suffisante.", conduct: "Arrêt de la traction, atropine 0,5 mg." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "urine"] }),
      notes: "Torsion testiculaire : urgence (ischémie), souvent estomac plein chez l'adolescent : séquence rapide.",
    }),
  },
  {
    id: pid(58),
    name: "Transplantation rénale",
    surgery: "Transplantation rénale",
    operation_category: "J2",
    hospital: "",
    source: `${ESC_2022} ; ${MANUAL}, chap. 32 (insuffisance rénale) ; protocole du centre de transplantation.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(1.5), sufentanil(), drug("Cisatracurium", "induction", "bolus_iv", { perKg: 0.15, basis: "ideal" }, "mg", "0,15–0,2 mg/kg : élimination indépendante du rein (manuel, chap. 8)."), cefazolin("Selon le protocole du centre de transplantation."), noradrenaline("PAM ≥ 80 mmHg au déclampage (perfusion du greffon)."), paracetamol(), drug("Ropivacaïne (TAP ou carré des lombes)", "alr", "perinerveux", { fixed: 100 }, "mg", "Échoguidé, en fin d'intervention.")],
      targets: ["Kaliémie ≤ 5,5 mmol/L avant l'induction", "Déclampage : PAM ≥ 80 mmHg, PVC selon l'équipe, remplissage cristalloïde équilibré", "Diurèse du greffon"],
      material: [...MONITORING, "Cathéter artériel (pas sur le bras de la fistule)", "Voie veineuse centrale", "Sonde urinaire"],
      risks: [risk("hyperkalaemia"), risk("induction_hypotension"), { title: "Hypoperfusion du greffon", why: "Hypotension, hypovolémie au déclampage.", prevention: "Remplissage et vasopresseur titrés, PAM élevée.", conduct: "Pas de diurèse : PAM, volémie, prévenir le chirurgien (thrombose, clampage)." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "mechanical", watch: ["pain", "urine", "potassium"] }),
      notes: "Pas d'AINS. Opioïdes à élimination rénale évités (morphine) ; fistule artério-veineuse protégée. Donneur vivant : néphrectomie par cœlioscopie (protocole néphrectomie).",
    }),
  },
  {
    id: pid(59),
    name: "Gestes urologiques courts sous sédation (biopsies, lithotritie, curiethérapie)",
    surgery: "Biopsies prostatiques",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}, chap. 22 (sédation).`,
    content: content({
      techniques: ["sedation", "general", "neuraxial"],
      drugs: [drug("Propofol (sédation)", "maintenance", "pse", { fixed: 20 }, "mg", "Titré ; AIVOC 1–2 µg/mL."), drug("Alfentanil", "analgesia", "bolus_iv", { perKg: 10 }, "µg", "Bolus avant le geste douloureux."), drug("Céfuroxime", "antibio", "bolus_iv", { fixed: 1.5 }, "g", "Biopsies transrectales : antibioprophylaxie selon le protocole local (voie transpérinéale de préférence)."), paracetamol()],
      targets: ["Ventilation spontanée", "Sortie le jour même"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (capnographie nasale)", "Masque laryngé prêt"],
      risks: [{ title: "Dépression respiratoire sous sédation", why: "Propofol et opioïde.", prevention: "Titration, capnographie.", conduct: "Stimuler, O₂, masque, réduire la sédation." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain", "urine"] }),
      notes: "Curiethérapie prostatique : rachianesthésie ou AG, lithotomie, sonde urinaire.",
    }),
  },

  // ============================================================ Gynécologie et obstétrique
  {
    id: pid(60),
    name: "Hystérectomie et chirurgie gynécologique par laparotomie",
    surgery: "Hystérectomie par laparotomie",
    operation_category: "J1",
    hospital: "",
    source: `${ERAS_GYN} ; ${MANUAL}, chap. 13 et 34.`,
    content: content({
      techniques: ["general", "neuraxial", "superficial_block"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), clindamycinAlt(), dexamethasone(8), ondansetron(), droperidol(), paracetamol(), ketorolac(), morphineIt(0.1, "Ou TAP bilatéral ; péridurale si laparotomie xipho-pubienne (oncologie)."), tranexamic()],
      targets: ["Prévention des NVPO (femme, opioïdes) : double ou triple prophylaxie", "Normothermie, euvolémie"],
      material: [...MONITORING, "Sonde urinaire", "Curarimètre (TOF)"],
      risks: [risk("ponv"), risk("bleeding"), risk("hypothermia")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "intrathecal_morphine"], thrombo: "lmwh", watch: ["pain", "sedation", "urine"] }),
      notes: "Gynéco-oncologie (hystérectomie élargie, cancer de l'ovaire) : péridurale thoracique, cathéter artériel, thromboprophylaxie 28 jours.",
    }),
  },
  {
    id: pid(61),
    name: "Chirurgie vaginale et périnéale (prolapsus, bandelette, hystérectomie vaginale)",
    surgery: "Hystérectomie vaginale",
    operation_category: "J1",
    hospital: "",
    source: `${ERAS_GYN} ; ${MANUAL}, chap. 13 et 19.`,
    content: content({
      techniques: ["neuraxial", "general"],
      drugs: [bupiSpinal(12), morphineIt(0.1), propofolInduction(), sufentanil(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Lithotomie : appuis, durée", "Bandelette sous-urétrale : AL et sédation (test de toux) ou rachianesthésie courte"],
      material: [...MONITORING.slice(0, 4), "Étriers", "Masque laryngé"],
      risks: [risk("spinal_hypotension"), risk("ponv"), { title: "Lésion nerveuse de position", why: "Lithotomie prolongée : nerf fibulaire, fémoral.", prevention: PELVIC_POS, conduct: "Déficit au réveil : noter, examen neurologique, avis." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "intrathecal_morphine"], thrombo: "lmwh", watch: ["pain", "urine", "sedation"] }),
      notes: "Vulvectomie : AG ou rachianesthésie, curage inguinal associé.",
    }),
  },
  {
    id: pid(62),
    name: "Cœlioscopie gynécologique (annexes, GEU, endométriose)",
    surgery: "Cœlioscopie gynécologique",
    operation_category: "J1",
    hospital: "",
    source: `${PROSPECT_REF("hystérectomie cœlioscopique", 2019, "30914471")} (extrapolé) ; ${MANUAL}, chap. 30.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin("Seulement si ouverture vaginale ou digestive."), dexamethasone(8), ondansetron(), droperidol(), paracetamol(), ketorolac(), drug("Ropivacaïne (infiltration des orifices)", "alr", "infiltration", { fixed: 75 }, "mg", "0,375 %, 20 mL.")],
      targets: ["Pneumopéritoine à basse pression, Trendelenburg", "Double prophylaxie des NVPO"],
      material: [...MONITORING, "Curarimètre (TOF)"],
      risks: [risk("ponv"), risk("gas_embolism"), { title: "Grossesse extra-utérine rompue", why: "Hémopéritoine : choc hémorragique chez une femme jeune.", prevention: "Deux voies veineuses, groupe, sang disponible.", conduct: "Induction adaptée au choc (kétamine, étomidate), séquence rapide, transfusion." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Endométriose profonde et promontofixation : longues, Trendelenburg marqué, hospitalisation, thromboprophylaxie. Test de grossesse avant l'intervention.",
    }),
  },
  {
    id: pid(63),
    name: "Césarienne en urgence et hémorragie du post-partum",
    surgery: "Césarienne en urgence",
    operation_category: "B",
    hospital: "",
    source: `${ROELANTS} ; ${ERAS_CS} ; ${MANUAL}, chap. 36 ; CNGOF/SFAR : hémorragie du post-partum 2022.`,
    content: content({
      techniques: ["neuraxial", "general"],
      drugs: [
        drug("Lidocaïne 2 % adrénalinée + bicarbonate (extension de la péridurale)", "alr", "peridural", { fixed: 300 }, "mg", "15–20 mL par fractions : bloc chirurgical en 10–15 min (cours Roelants)."),
        bupiSpinal(10, "Rachianesthésie si pas de péridurale et délai compatible."),
        propofolInduction(2.5),
        succinylcholine(),
        drug("Rocuronium (alternative)", "induction", "bolus_iv", { perKg: 1.2 }, "mg", "1,2 mg/kg ; sugammadex 16 mg/kg prêt."),
        drug("Citrate de sodium 0,3 M", "premed", "po", { fixed: 30 }, "mL", "Antiacide avant une AG."),
        cefazolin("Avant l'incision (ERAS césarienne 2025)."),
        drug("Ocytocine", "haemodynamic", "bolus_iv", { fixed: 5 }, "UI", "Après la naissance, bolus lent (5 min), puis 5–10 UI/h (cours Roelants)."),
        drug("Acide tranexamique", "haemodynamic", "perfusion", { fixed: 1 }, "g", "Hémorragie du post-partum : 1 g IV en 10 min dès le diagnostic, 2e g si persistance (CNGOF/SFAR 2022)."),
        drug("Sulprostone", "haemodynamic", "pse", { fixed: 500 }, "µg", "Atonie résistante à l'ocytocine : 500 µg en 1 h."),
        phenylephrine("Perfusion prophylactique sous rachianesthésie (ERAS 2025)."),
      ],
      targets: ["Code d'urgence : extension de la péridurale d'abord ; AG si code rouge ou contre-indication", "AG : séquence rapide, vidéolaryngoscope, algorithme OAA/DAS de l'intubation difficile obstétricale", "Hémorragie : Hb, fibrinogène > 2 g/L, calcium, température"],
      material: [...MONITORING, "Vidéolaryngoscope", "Sondes 6–6,5", "Deux voies veineuses de gros calibre", "Accélérateur-réchauffeur de transfusion", "Chariot d'hémorragie obstétricale"],
      risks: [risk("aspiration"), risk("difficult_airway"), risk("bleeding"), { title: "Réveil peropératoire sous AG", why: "Induction rapide, hémodynamique instable, halogénés réduits.", prevention: "Doses d'induction suffisantes, halogéné ≥ 1 MAC jusqu'à la naissance.", conduct: "BIS si disponible ; informer la patiente si doute." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "nsaid", "intrathecal_morphine"], thrombo: "lmwh", watch: ["pain", "bleeding", "hb", "sedation"] }),
      notes: "Hystérectomie d'hémostase : AG, transfusion massive (ratio concentrés/plasma), fibrinogène, récupérateur si disponible. Embolisation : transport vers la radiologie avec l'équipe.",
    }),
  },
  {
    id: pid(64),
    name: "Analgésie du travail et gestes obstétricaux",
    surgery: "Analgésie péridurale du travail",
    operation_category: "B",
    hospital: "",
    source: `${ROELANTS} ; ${MANUAL}, chap. 36.`,
    content: content({
      techniques: ["neuraxial"],
      drugs: [
        drug("Lévobupivacaïne 0,0625 % + sufentanil 0,5 µg/mL (péridurale)", "alr", "peridural", { fixed: 12.5 }, "mg", "Dose d'attaque 20 mL, puis PIEB ou PCEA (cours Roelants)."),
        drug("Sufentanil (rachi-péridurale combinée)", "alr", "intrathecal", { fixed: 5 }, "µg", "2,5–5 µg intrathécal avec 2,5 mg de bupivacaïne : analgésie rapide."),
        drug("Nitroglycérine", "haemodynamic", "bolus_iv", { fixed: 100 }, "µg", "Relâchement utérin (révision, délivrance artificielle) : 50–100 µg IV."),
        phenylephrine(),
      ],
      targets: ["Analgésie sans bloc moteur (EVA ≤ 3)", "Rythme cardiaque fœtal surveillé après la dose d'attaque", "Extension possible pour une césarienne ou un geste"],
      material: ["PNI", "SpO₂", "Monitorage fœtal", "Kit de péridurale", "Chariot de réanimation"],
      risks: [risk("spinal_hypotension"), risk("last"), { title: "Brèche dure-mérienne", why: "Aiguille de Tuohy.", prevention: "Technique soigneuse.", conduct: "Céphalées posturales : antalgiques, hydratation ; blood patch si persistance (protocole)." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "block"] }),
      notes: "Pas d'antibioprophylaxie pour l'analgésie ; gestes obstétricaux selon le protocole obstétrical. Révision utérine, déchirure, extraction instrumentale : renforcer la péridurale ; sinon rachianesthésie courte ou AG à séquence rapide. Cerclage : rachianesthésie. Version par manœuvre externe : rachi-péridurale possible.",
    }),
  },
  {
    id: pid(65),
    name: "Chirurgie non obstétricale pendant la grossesse",
    surgery: "Chirurgie non obstétricale pendant la grossesse",
    operation_category: "B",
    hospital: "",
    source: `${ROELANTS} ; ${MANUAL}, chap. 36.`,
    content: content({
      techniques: ["neuraxial", "general", "superficial_block"],
      drugs: [propofolInduction(), succinylcholine(), sufentanil(), drug("Citrate de sodium 0,3 M", "premed", "po", { fixed: 30 }, "mL", "À partir du 2e trimestre, avant une AG."), cefazolin(), paracetamol(), phenylephrine()],
      targets: ["À partir de 20 SA : décubitus latéral gauche (compression aorto-cave)", "Normocapnie, normoxie, PAM maintenue (perfusion utéro-placentaire)", "Monitorage fœtal selon le terme, avis obstétrical"],
      material: [...MONITORING, "Cale sous la fesse droite", "Vidéolaryngoscope", "Monitorage fœtal (≥ 24 SA)"],
      risks: [risk("aspiration"), risk("difficult_airway"), { title: "Accouchement prématuré", why: "Chirurgie abdominale, inflammation.", prevention: "Tocolyse selon l'obstétricien.", conduct: "Contractions : avis obstétrical." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "opioid_titration"], thrombo: "lmwh", watch: ["pain"] }),
      notes: "ALR préférée quand elle suffit. Pas d'AINS après 20 SA. Chirurgie non urgente reportée après l'accouchement ; semi-urgente de préférence au 2e trimestre.",
    }),
  },
];
