// Reference protocols for the interventions that had none of their own
// (audit of the « Fiches » tab, 2026-10): rather than borrowing the protocol
// of a neighbouring but different operation (sinus surgery for an adult
// tonsillectomy, a caesarean for a cerclage), each gets a short protocol of
// its own. Same conventions as reference-protocols-more.ts.

import {
  MANUAL,
  MONITORING,
  cefazolin,
  content,
  dexamethasone,
  drug,
  ketorolac,
  ondansetron,
  paracetamol,
  pid,
  postop,
  propofolInduction,
  risk,
  rocuronium,
  ropivacaineBlock,
  sufentanil,
  thoracicEpidural,
  tranexamic,
  type ReferenceProtocol,
} from "./reference-protocol-kit";
import { DEFAULT_PCEA } from "./postop";

const remifentanil = () => drug("Rémifentanil", "maintenance", "pse", { perKg: 0.5, basis: "lean" }, "µg", "Bolus 0,2–1 µg/kg ; entretien 0,05–0,25 µg/kg/min : réveil rapide, hypotension contrôlée possible (manuel, chap. 7).");

export const EXTRA_REFERENCE_PROTOCOLS: ReferenceProtocol[] = [
  {
    id: pid(112),
    name: "Chirurgie ORL et cervicale de l'adulte (amygdalectomie, parotide, glande sous-maxillaire)",
    surgery: "Amygdalectomie",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), remifentanil(), rocuronium(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Sonde armée ou préformée, fixée loin du champ", "Parotide, sous-maxillaire : pas de curare d'entretien (monitorage du nerf facial)", "Réveil calme, sans toux ; aspiration pharyngée sous contrôle de la vue"],
      material: [...MONITORING, "Deux aspirations"],
      risks: [{ title: "Hémorragie (amygdalectomie : J0 et jusqu'à J10)", why: "Lit amygdalien ; sang dégluti, estomac plein.", prevention: "Hémostase, PA contrôlée au réveil, consignes de retour.", conduct: "Reprise : remplissage avant l'induction, séquence rapide, deux aspirations (fiche hémorragie après amygdalectomie)." }, risk("ponv"), risk("laryngospasm")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "bleeding"] }),
      postop: ["Amygdalectomie : alimentation froide, AINS selon le chirurgien", "Parotide : surveillance du nerf facial et du drain"],
      notes: "Pas d'antibioprophylaxie (chirurgie propre ou propre-contaminée de courte durée). SAOS : opioïdes réduits, surveillance prolongée de la SpO₂.",
    }),
  },
  {
    id: pid(113),
    name: "Trachéotomie chirurgicale",
    surgery: "Trachéotomie",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL} ; prévention du feu au bloc (ASA 2013).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium()],
      targets: ["FiO₂ ≤ 0,3 dès l'usage du bistouri électrique et à l'ouverture de la trachée (feu)", "Sonde retirée progressivement sous contrôle de la vue, canule vérifiée à l'EtCO₂", "Ballonnet de la sonde sous les cordes jusqu'à la canulation"],
      material: [...MONITORING, "Canules de deux tailles, mandrin", "Matériel d'intubation difficile, fibroscope", "Raccord stérile pour la canule"],
      risks: [{ title: "Perte des voies aériennes", why: "Ouverture de la trachée, faux trajet de la canule, décanulation.", prevention: "Retrait progressif de la sonde, canule vérifiée par l'EtCO₂ avant de retirer la sonde.", conduct: "Pas d'EtCO₂ : réavancer la sonde par la bouche, réintuber ; décanulation précoce : intubation orale plutôt que recanulation à l'aveugle." }, { title: "Feu des voies aériennes", why: "Oxygène + bistouri électrique + sonde.", prevention: "FiO₂ ≤ 0,3, ciseaux pour ouvrir la trachée.", conduct: "Arrêter le gaz, retirer la sonde, sérum dans le champ, réintuber, bronchoscopie." }, risk("bleeding")],
      postopPlan: postop({ analgesia: ["paracetamol"], thrombo: "lmwh", watch: ["pain", "bleeding"] }),
      postop: ["Canule fixée, ballonnet contrôlé ; canule de rechange et mandrin au lit", "Radiographie de thorax selon le contexte"],
      notes: "Pas d'antibioprophylaxie systématique (geste court, propre-contaminé). Patient souvent déjà intubé (réanimation) : le transfert et le retour se préparent comme un geste sur voies aériennes à risque.",
    }),
  },
  {
    id: pid(114),
    name: "Chirurgie des paupières et des voies lacrymales",
    surgery: "Chirurgie des paupières",
    operation_category: "I",
    hospital: "",
    source: `${MANUAL}.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [
        drug("Lidocaïne adrénalinée 1–2 % (infiltration)", "alr", "infiltration", { fixed: 60 }, "mg", "Par le chirurgien ; maximum 7 mg/kg."),
        drug("Propofol (sédation)", "maintenance", "pse", { perKg: 1, basis: "lean" }, "mg", "Sédation légère, patient réveillable et coopérant (le chirurgien peut demander d'ouvrir ou fermer les yeux)."),
        propofolInduction(),
        sufentanil(),
        dexamethasone(8),
        ondansetron(),
        paracetamol(),
      ],
      targets: ["Sédation : oxygène sous les champs avec prudence (feu) — FiO₂ minimale", "Voies lacrymales (dacryocystorhinostomie) : AG, packing pharyngé, hypotension modérée"],
      material: [...MONITORING],
      risks: [{ title: "Réflexe oculocardiaque", why: "Traction sur le globe ou l'orbite.", prevention: "Prévenir le chirurgien.", conduct: "Bradycardie : arrêt de la traction, atropine si elle persiste." }, risk("ponv")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      postop: ["Sortie le jour même", "Glace, tête surélevée"],
      notes: "Pas d'antibioprophylaxie systématique (chirurgie palpébrale propre). Antiagrégants et anticoagulants : avis du chirurgien (hématome orbitaire rare mais grave).",
    }),
  },
  {
    id: pid(115),
    name: "Angioplastie et stenting (périphérique, carotidien)",
    surgery: "Angioplastie périphérique",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL} ; ESVS 2023 (sténose carotidienne).`,
    content: content({
      techniques: ["sedation"],
      drugs: [
        drug("Lidocaïne 1 % (infiltration du point de ponction)", "alr", "infiltration", { fixed: 100 }, "mg", "Par l'opérateur."),
        drug("Rémifentanil (sédation légère)", "maintenance", "pse", { fixed: 20 }, "µg", "Bolus de 10–20 µg si besoin, puis 0,02–0,05 µg/kg/min : patient réveillé et coopérant (examen neurologique au stenting carotidien)."),
        drug("Atropine", "haemodynamic", "bolus_iv", { fixed: 0.5 }, "mg", "Stenting carotidien : bradycardie, hypotension au gonflement du ballonnet (sinus carotidien)."),
        drug("Héparine", "other", "bolus_iv", { perKg: 70 }, "UI", "Selon l'opérateur (50–100 UI/kg), ACT."),
      ],
      targets: ["Carotide : examen neurologique (parole, main controlatérale) à chaque étape", "PA dans la cible de l'opérateur, éviter hypotension et pic hypertensif (hyperperfusion après stenting carotidien)"],
      material: [...MONITORING, "Cathéter artériel si stenting carotidien", "Vasopresseur prêt"],
      risks: [{ title: "Bradycardie et hypotension (stenting carotidien)", why: "Barorécepteurs du sinus carotidien.", prevention: "Atropine prête, remplissage.", conduct: "Atropine, vasopresseur ; hypotension prolongée : surveillance en unité adaptée." }, { title: "Accident neurologique", why: "Embolie pendant le geste.", prevention: "Patient éveillé, examen neurologique répété.", conduct: "Déficit : prévenir l'opérateur (angiographie, thrombectomie), PA haute normale." }, risk("bleeding")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol"], thrombo: "none", watch: ["neuro", "bleeding"] }),
      postop: ["Point de ponction et pouls distaux", "Antiagrégants selon l'opérateur", "Carotide : PA et examen neurologique horaires les premières heures"],
      notes: "Pas d'antibioprophylaxie en routine (geste percutané) ; endoprothèse selon l'opérateur. Anesthésie générale seulement si le patient ne peut pas rester immobile ou coopérer.",
    }),
  },
  {
    id: pid(116),
    name: "Arthroscopie de hanche",
    surgery: "Arthroscopie de hanche",
    operation_category: "K",
    hospital: "",
    source: `${MANUAL}.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), ropivacaineBlock(100, "bloc PENG ou fascia iliaca"), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Curarisation profonde pendant la traction (distraction articulaire)", "Normothermie (liquide d'irrigation)"],
      material: [...MONITORING, "Curamètre", "Réchauffement actif"],
      risks: [{ title: "Complications de la traction", why: "Poteau périnéal : lésion du nerf pudendal, du périnée ; nerf sciatique étiré.", prevention: "Durée de traction limitée et notée, poteau bien rembourré.", conduct: "Signaler la durée au chirurgien ; examen neurologique au réveil." }, { title: "Extravasation du liquide d'irrigation", why: "Liquide sous pression vers l'abdomen et le rétropéritoine.", prevention: "Pression d'irrigation basse, surveiller l'abdomen.", conduct: "Abdomen tendu, hypothermie, instabilité : arrêter l'irrigation, prévenir le chirurgien." }, risk("hypothermia"), risk("ponv")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", watch: ["pain", "block"] }),
      postop: ["Marche avec cannes selon le chirurgien", "Ambulatoire possible selon l'équipe"],
    }),
  },
  {
    id: pid(117),
    name: "Gastrostomie chirurgicale",
    surgery: "Gastrostomie chirurgicale",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(1.5), sufentanil(), rocuronium(), cefazolin(), paracetamol()],
      targets: ["Séquence rapide si troubles de la déglutition ou estomac plein", "Patient fragile (dénutrition, maladie neurologique) : induction prudente"],
      material: [...MONITORING],
      risks: [risk("aspiration"), risk("induction_hypotension")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol"], thrombo: "lmwh", watch: ["pain"] }),
      postop: ["Sonde de gastrostomie fixée ; alimentation selon le chirurgien (souvent dès J1)"],
      notes: "Souvent proposée en voie endoscopique ou radiologique sous sédation quand c'est possible.",
    }),
  },
  {
    id: pid(118),
    name: "Prostatectomie radicale par voie ouverte",
    surgery: "Prostatectomie radicale par voie ouverte",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [thoracicEpidural("T10–T12", "Ou morphine intrathécale 100–150 µg."), propofolInduction(), sufentanil(), rocuronium(), tranexamic(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Saignement veineux (plexus de Santorini) : PVC basse, remplissage guidé", "Normothermie"],
      material: [...MONITORING, "Deux voies veineuses de bon calibre", "Réchauffement actif", "Cathéter artériel selon le terrain"],
      risks: [risk("bleeding"), risk("hypothermia"), risk("ponv")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "urine", "hb"] }),
      postop: ["Sonde vésicale (anastomose) selon l'urologue", "Hémoglobine à J1"],
    }),
  },
  {
    id: pid(119),
    name: "Chirurgie plastique et reconstructrice (hors lambeau libre)",
    surgery: "Chirurgie plastique ou reconstructrice",
    operation_category: "L",
    hospital: "",
    source: `${MANUAL}.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Normothermie, normovolémie (perfusion des greffes et lambeaux)", "Réveil calme, sans toux ni pic hypertensif (hématome)"],
      material: [...MONITORING, "Réchauffement actif", "Compression pneumatique si > 1 h"],
      risks: [risk("ponv"), risk("hypothermia")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "mechanical", watch: ["pain", "bleeding"] }),
      postop: ["Surveillance du site (hématome) selon le chirurgien"],
      notes: "Lambeau libre ou microchirurgie : protocole « Lambeau libre et microchirurgie ».",
    }),
  },
];
