// Reference protocols for common interventions, importable from Paramètres ›
// Protocoles. They are a starting point, to be adapted to the service's own
// protocol: every dose comes from a named source — the Belgian
// inter-university teaching (EIUA / BeSARPP courses: Ph. Dubois, CHU UCL
// Namur, orthopaedics; F. Roelants, Saint-Luc, obstetrics 2022; P.-Y. Hardy,
// CHU Liège, enhanced recovery), the ESC/ESAIC guidelines and the reference
// textbook (Manuel pratique d'anesthésie 2020, chapter given). No patient
// data: doses are per kilo or fixed, computed for the patient in the plan.

import {
  pid,
  MANUAL,
  DUBOIS,
  ROELANTS,
  HARDY,
  ESAIC_FASTING,
  drug,
  content,
  cefazolin,
  clindamycinAlt,
  propofolInduction,
  sufentanil,
  rocuronium,
  dexamethasone,
  ondansetron,
  droperidol,
  paracetamol,
  ketorolac,
  tranexamic,
  ketamineSparing,
  MONITORING,
  metronidazole,
  ropivacaineBlock,
  lidocaineIv,
  risk,
  postop,
  PROSPECT_REF,
} from "./reference-protocol-kit";
import type { ReferenceProtocol } from "./reference-protocol-kit";
import { DEFAULT_PCEA } from "./postop";
import { MORE_REFERENCE_PROTOCOLS } from "./reference-protocols-more";
import { CHILDREN_AND_OTHER_PROTOCOLS } from "./reference-protocols-children";

export type { ReferenceProtocol };

// Protocols ------------------------------------------------------------------

const FIRST_REFERENCE_PROTOCOLS: ReferenceProtocol[] = [
  {
    id: pid(1),
    name: "Prothèse totale de hanche sous rachianesthésie",
    surgery: "Prothèse totale de hanche",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${MANUAL}, chap. 40 ; ERAS Society PTH/PTG (Wainwright, Acta Orthop 2020).`,
    content: content({
      techniques: ["neuraxial"],
      drugs: [
        drug("Bupivacaïne 0,5 % hyperbare", "alr", "intrathecal", { fixed: 12.5 }, "mg", "2–4 ml de bupivacaïne 0,5 % ; chirurgie > 120 min (cours Dubois)."),
        drug("Morphine intrathécale", "analgesia", "intrathecal", { fixed: 100 }, "µg", "Analgésie 12–24 h ; surveillance respiratoire à l'étage (dépression retardée à 6 h), NVPO, rétention urinaire."),
        drug("Propofol (sédation)", "maintenance", "pse", { perKg: 2 }, "mg", "Sédation 2–6 mg/kg/h si besoin."),
        cefazolin("Matériel intra-articulaire : 2 g puis 2 g × 2 (24 h au total) ; > 4 h : réinjection de 1 g (cours Dubois)."),
        clindamycinAlt(),
        tranexamic(),
        dexamethasone(8),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["PAM ≥ 65 mmHg ou ≥ 80 % de la valeur de base", "Normothermie (T ≥ 36 °C)", "Hb transfusionnelle 7–9 g/dl selon le patient"],
      material: [...MONITORING, "Réchauffement actif (air pulsé)", "Groupe et RAI"],
      risks: [
        { title: "Syndrome d'implantation du ciment", conduct: "Hypotension, désaturation au scellement : volémie optimisée, FiO₂ augmentée, pas de N₂O, vasopresseur prêt. Prothèse non cimentée si HTAP ou dysfonction cardiaque." },
        { title: "Saignement", conduct: "Acide tranexamique, récupération peropératoire si prévue, seuil transfusionnel selon le terrain." },
      ],
      postop: ["Lever à J0–J1", "Thromboprophylaxie jusqu'à la déambulation normale (PTH : 28–35 jours)", "Pas de drain ni de sonde urinaire systématique"],
      notes: "AG possible (installation, voie antérieure en traction : curarisation profonde, rocuronium + sugammadex). Infiltration périarticulaire ou bloc (plexus lombaire, fémoral) selon l'équipe.",
    }),
  },
  {
    id: pid(2),
    name: "Prothèse totale de genou sous rachianesthésie",
    surgery: "Prothèse totale de genou",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${MANUAL}, chap. 40 ; ERAS Society PTH/PTG (Wainwright, Acta Orthop 2020).`,
    content: content({
      techniques: ["neuraxial", "deep_block"],
      drugs: [
        drug("Bupivacaïne 0,5 % hyperbare", "alr", "intrathecal", { fixed: 12.5 }, "mg", "2–4 ml de bupivacaïne 0,5 %."),
        drug("Morphine intrathécale", "analgesia", "intrathecal", { fixed: 100 }, "µg", "Surveillance respiratoire à l'étage."),
        drug("Ropivacaïne (bloc du canal des adducteurs)", "alr", "perinerveux", { fixed: 75 }, "mg", "Bloc sensitif respectant le quadriceps ; ou infiltration périarticulaire par le chirurgien (ne pas cumuler au-delà de la dose maximale de 3 mg/kg)."),
        cefazolin("Matériel intra-articulaire : 2 g puis 2 g × 2 (24 h au total) ; > 4 h : réinjection de 1 g (cours Dubois)."),
        clindamycinAlt(),
        tranexamic(),
        dexamethasone(8),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["PAM ≥ 65 mmHg", "Normothermie"],
      material: [...MONITORING, "Échographe", "Garrot pneumatique si utilisé"],
      tourniquetAlertMin: 90,
      risks: [
        { title: "Garrot", conduct: "Pression PAS + 100–150 mmHg au membre inférieur ; au lâcher : hypotension, hyperkaliémie, embolies — anticiper la volémie. Au-delà de 60 min : douleur, tachycardie, hypertension." },
        { title: "Syndrome du ciment", conduct: "Surveillance au scellement ; vasopresseur prêt." },
      ],
      postop: ["Mobilisation précoce, critères de sortie objectifs", "Thromboprophylaxie jusqu'à la déambulation normale (PTG : 14 jours)"],
      notes: "Le bloc fémoral bloque le quadriceps et retarde la revalidation active : canal des adducteurs ou infiltration périarticulaire préférés (cours Dubois, ERAS).",
    }),
  },
  {
    id: pid(3),
    name: "Fracture de l'extrémité supérieure du fémur (sujet âgé)",
    surgery: "Fracture du col du fémur",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${MANUAL}, chap. 40 et 43.`,
    content: content({
      techniques: ["neuraxial", "deep_block"],
      drugs: [
        drug("Lévobupivacaïne (bloc ilio-fascial)", "alr", "perinerveux", { perKg: 1, max: 150 }, "mg", "Aux urgences et avant l'installation ; dose maximale 3 mg/kg."),
        drug("Bupivacaïne 0,5 % hyperbare", "alr", "intrathecal", { fixed: 10 }, "mg", "Dose réduite chez le sujet âgé ; pas de rachianesthésie si sténose aortique serrée (cours Dubois)."),
        cefazolin("Matériel extra-articulaire : dose unique ; prothèse : 24 h (cours Dubois)."),
        clindamycinAlt(),
        tranexamic(),
        paracetamol(),
      ],
      targets: ["PAM ≥ 65 mmHg ou ≥ 80 % de la valeur de base", "Normothermie", "Seuil transfusionnel plus élevé chez le coronarien"],
      material: [...MONITORING, "Échographe", "Deux concentrés érythrocytaires disponibles"],
      risks: [
        { title: "Délai opératoire", conduct: "Opérer dans les 24–48 h ; un antithrombotique ne retarde que le temps nécessaire (voir les règles de délai)." },
        { title: "Confusion postopératoire", conduct: "Éviter benzodiazépines et anticholinergiques, analgésie par bloc, lunettes et appareils auditifs, repérage." },
        { title: "Ciment (prothèse)", conduct: "Hypotension et désaturation au scellement : volémie, FiO₂, vasopresseur prêt." },
      ],
      postop: ["Lever précoce", "Thromboprophylaxie", "Dépistage de la dénutrition, de l'anémie, de la rhabdomyolyse (CK si station au sol)"],
      notes: "Anesthésie générale possible (+ bloc ilio-fascial) ; mortalité à 1 an ≈ 36 %.",
    }),
  },
  {
    id: pid(4),
    name: "Arthroscopie d'épaule : AG et bloc interscalénique",
    surgery: "Arthroscopie de l'épaule",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${MANUAL}, chap. 12 et 40.`,
    content: content({
      techniques: ["general", "deep_block"],
      drugs: [
        drug("Ropivacaïne 0,5 % (bloc interscalénique)", "alr", "perinerveux", { fixed: 75 }, "mg", "15 ml ; paralysie phrénique homolatérale constante : prudence si insuffisance respiratoire."),
        propofolInduction(),
        sufentanil(),
        drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6, basis: "ideal" }, "mg", "Bloc profond si la chirurgie le demande ; décurarisation contrôlée (sugammadex)."),
        dexamethasone(8),
        ondansetron(),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["Position semi-assise : PA mesurée au niveau du cerveau", "Éviter une hypotension prolongée (ischémie cérébrale en position assise)"],
      material: [...MONITORING, "Échographe", "Curamètre", "Protection des points d'appui (tête, bras)"],
      risks: [
        { title: "Position semi-assise", conduct: "Hypotension, bradycardie (réflexe de Bezold-Jarisch) : remplissage, éphédrine ou atropine." },
        { title: "Bloc interscalénique", conduct: "Paralysie phrénique, syndrome de Claude Bernard-Horner, dysphonie ; toxicité des AL (intralipides disponibles)." },
      ],
      postop: ["Arthroscopie sans implant : pas d'antibioprophylaxie (cours Dubois)", "Relai analgésique avant la levée du bloc"],
      notes: "Antibioprophylaxie : céfazoline 2 g seulement si implant (ancres, matériel).",
    }),
  },
  {
    id: pid(5),
    name: "Césarienne programmée sous rachianesthésie",
    surgery: "Césarienne",
    operation_category: "B",
    hospital: "",
    source: `${ROELANTS} ; ${MANUAL}, chap. 36.`,
    content: content({
      techniques: ["neuraxial"],
      drugs: [
        drug("Citrate de sodium 0,3 M", "premed", "po", { fixed: 30 }, "mL", "15 min avant ; + anti-H2 ou IPP (prophylaxie de l'inhalation)."),
        drug("Bupivacaïne 0,5 % hyperbare", "alr", "intrathecal", { fixed: 9 }, "mg", "8–10 mg avec sufentanil (ED95 pure 11 mg) ; ± 1 mg si < 155 cm ou > 170 cm ; macrosomie : moins, RCIU ou prématurité : + 1–2 mg."),
        drug("Sufentanil", "alr", "intrathecal", { fixed: 2.5 }, "µg", "2–5 µg."),
        drug("Morphine intrathécale", "analgesia", "intrathecal", { fixed: 100 }, "µg", "Analgésie postopératoire."),
        drug("Phényléphrine", "haemodynamic", "pse", { fixed: 25 }, "µg", "Perfusion prophylactique 25–50 µg/min dès la ponction (co-remplissage cristalloïde) ; bolus 50–150 µg si hypotension sans bradycardie ; bradycardie : éphédrine 5–10 mg. Objectif PAS > 90 % de la valeur de base."),
        cefazolin("Avant l'incision ; > 120 kg : 3 g."),
        drug("Ocytocine", "other", "bolus_iv", { fixed: 5 }, "UI", "Après la naissance, bolus lent (5 min) puis 5–10 UI/h (manuel, chap. 36)."),
        dexamethasone(8),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["PAS > 90 % de la valeur de base", "Décubitus latéral gauche (15°) jusqu'à la naissance", "Durée d'une hypotension < 3 min"],
      material: [...MONITORING, "Phényléphrine en seringue", "Matériel d'intubation difficile (conversion en AG)", "Acide tranexamique et fibrinogène disponibles"],
      risks: [
        { title: "Conversion en AG", conduct: "Séquence rapide : propofol 2,5 mg/kg, succinylcholine 1,5 mg/kg (ou rocuronium 1–1,2 mg/kg avec sugammadex 16 mg/kg prêt), sonde 6,5–7, préoxygénation (FeO₂ ≥ 90 %), sévoflurane 0,75 CAM." },
        { title: "Hémorragie du post-partum", conduct: "Ocytocine puis sulprostone, acide tranexamique 1 g, fibrinogène (> 2 g/l), plaquettes > 50 G/l, Ca²⁺, normothermie." },
      ],
      postop: ["Paracétamol + AINS + morphine intrathécale ; sans opioïde neuraxial : TAP, ilio-inguinal ou carré des lombes", "Alimentation et lever précoces, contact mère-enfant", "Thromboprophylaxie selon le risque"],
      notes: "Pas d'oxygène systématique. Péridurale de travail en place : lidocaïne 2 % adrénalinée 20 ml (urgence) ou ropivacaïne 0,75 % (sans urgence).",
    }),
  },
  {
    id: pid(6),
    name: "Cholécystectomie cœlioscopique (RAC)",
    surgery: "Cholécystectomie par cœlioscopie",
    operation_category: "A",
    hospital: "",
    source: `${HARDY} ; ${MANUAL}, chap. 20, 23 et 30.`,
    content: content({
      techniques: ["general"],
      drugs: [
        propofolInduction(),
        sufentanil(),
        rocuronium(),
        dexamethasone(8),
        cefazolin("Dose unique avant l'incision (chirurgie propre-contaminée)."),
        clindamycinAlt(),
        ondansetron(),
        droperidol(),
        paracetamol(),
        ketorolac(),
        drug("Ropivacaïne (infiltration des orifices)", "analgesia", "infiltration", { fixed: 75 }, "mg", "Par le chirurgien, en fin d'intervention."),
      ],
      targets: ["Pression du pneumopéritoine ≤ 12–15 mmHg", "Ventilation protectrice (Vt 6–8 ml/kg de poids idéal, PEP)", "Euvolémie"],
      material: [...MONITORING, "Curamètre", "Compression pneumatique des membres inférieurs"],
      risks: [{ title: "Pneumopéritoine", conduct: "Hypercapnie, baisse du retour veineux, bradycardie à l'insufflation (arrêt de l'insufflation, atropine) ; emphysème sous-cutané, pneumothorax." }],
      postop: ["Réalimentation le jour même", "Lever précoce", "Ambulatoire possible"],
      notes: "Jeûne : solides 6 h, liquides clairs 2 h, boisson sucrée (50 g d'hydrates de carbone) ; pas de prémédication anxiolytique systématique (cours Hardy).",
    }),
  },
  {
    id: pid(7),
    name: "Colectomie par cœlioscopie (RAC)",
    surgery: "Colectomie",
    operation_category: "A",
    hospital: "",
    source: `${HARDY} ; ${MANUAL}, chap. 20 et 30 ; ERAS Society colorectal.`,
    content: content({
      techniques: ["general"],
      drugs: [
        propofolInduction(),
        sufentanil(),
        rocuronium(),
        lidocaineIv(),
        ketamineSparing(),
        drug("Dexaméthasone", "ponv", "bolus_iv", { perKg: 0.1, max: 8 }, "mg", "0,1 mg/kg (cours Hardy)."),
        cefazolin("Dans l'heure avant l'incision ; réinjection à 4 h."),
        metronidazole(),
        ondansetron(),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["Euvolémie (remplissage guidé, vasopresseur plutôt que surcharge)", "Diurèse ≥ 0,5 ml/kg/h tolérée", "Normothermie", "Ventilation protectrice"],
      material: [...MONITORING, "Curamètre", "Réchauffement actif", "Compression pneumatique", "Cathéter artériel si terrain le justifie"],
      risks: [{ title: "Iléus postopératoire", conduct: "Épargne morphinique (lidocaïne IV, AINS 48 h, ALR), pas de surcharge hydrique, réalimentation précoce." }],
      postop: ["Pas de sonde gastrique ni de drain systématiques ; sonde urinaire retirée tôt", "Réalimentation et lever le soir même", "HBPM postopératoire", "AINS 48 h si pas de contre-indication"],
      notes: "Pas de préparation colique (sauf rectum). Jeûne moderne et boisson sucrée ; dépister la dénutrition (IMC ≤ 18,5, < 21 après 70 ans, perte ≥ 10 %) : immunonutrition (cours Hardy).",
    }),
  },
  {
    id: pid(8),
    name: "Cure de hernie inguinale en ambulatoire",
    surgery: "Cure de hernie inguinale",
    operation_category: "A",
    hospital: "",
    source: `${DUBOIS} (anesthésiques intrathécaux) ; ${MANUAL}, chap. 13, 20 et 33.`,
    content: content({
      techniques: ["neuraxial"],
      drugs: [
        drug("Chloroprocaïne 1 % (Ampres)", "alr", "intrathecal", { fixed: 45 }, "mg", "4–5 ml ; chirurgie courte (40–45 min), miction jusqu'à 2 h, sortie ≈ 3 h (cours Dubois)."),
        drug("Prilocaïne 2 % hyperbare (Tachipri)", "alr", "intrathecal", { fixed: 50 }, "mg", "Alternative : 2–3 ml ; 100–130 min, sortie ≈ 4 h."),
        cefazolin("Dose unique si prothèse (plaque)."),
        drug("Ropivacaïne (bloc ilio-inguinal ou infiltration)", "analgesia", "infiltration", { fixed: 75 }, "mg", "Analgésie après la levée du bloc."),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["Critères de sortie : miction, marche, douleur < 4, pas de NVPO"],
      material: [...MONITORING],
      risks: [{ title: "Rétention urinaire", conduct: "Éviter la morphine intrathécale ; échographie vésicale avant la sortie si doute." }],
      postop: ["Sortie le jour même", "Paracétamol + AINS 3–5 jours"],
      notes: "AG + bloc ou anesthésie locale selon le chirurgien et le patient.",
    }),
  },
  {
    id: pid(9),
    name: "Amygdalectomie de l'enfant",
    surgery: "Amygdalectomie de l'enfant",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 37 et 38 ; ${ESAIC_FASTING}.`,
    content: content({
      techniques: ["general"],
      drugs: [
        drug("Midazolam (prémédication)", "premed", "po", { perKg: 0.3, max: 15 }, "mg", "0,3–0,5 mg/kg per os, 20–30 min avant (manuel, chap. 37)."),
        drug("Propofol", "induction", "bolus_iv", { perKg: 3 }, "mg", "2,5–5 mg/kg chez l'enfant ; ou induction au sévoflurane puis voie veineuse."),
        drug("Sufentanil", "induction", "bolus_iv", { perKg: 0.2 }, "µg", "Douleur importante."),
        drug("Dexaméthasone", "ponv", "bolus_iv", { perKg: 0.15, max: 8 }, "mg", "0,1–0,2 mg/kg (manuel, chap. 38)."),
        drug("Ondansétron", "ponv", "bolus_iv", { perKg: 0.1, max: 4 }, "mg", "0,1–0,2 mg/kg (manuel, chap. 38)."),
        drug("Paracétamol", "analgesia", "perfusion", { perKg: 15, max: 1000 }, "mg", "15 mg/kg, 4 × / jour."),
      ],
      targets: ["Sonde préformée (RAE), souvent sans curare", "Réveil calme, aspiration pharyngée sous contrôle de la vue"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Sonde RAE", "Deux aspirations"],
      risks: [
        { title: "Laryngospasme", conduct: "O₂ 100 % en pression positive, approfondir (propofol), succinylcholine 0,3 mg/kg si désaturation." },
        { title: "Hémorragie (jusqu'à J7)", conduct: "Estomac plein de sang : correction de la volémie avant l'induction, séquence rapide, deux aspirations, groupe sanguin." },
        { title: "SAOS de l'enfant", conduct: "Opioïdes réduits, surveillance respiratoire prolongée." },
      ],
      postop: ["Paracétamol ; AINS selon le chirurgien", "Pas de codéine (métaboliseurs ultra-rapides)"],
      notes: "Jeûne ESAIC 2022 : liquides clairs jusqu'à 1 h, lait maternel 3 h, lait artificiel et repas léger 4–6 h. Pas d'antibioprophylaxie.",
    }),
  },
  {
    id: pid(10),
    name: "Thyroïdectomie",
    surgery: "Thyroïdectomie",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 23 et 34.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(0.6), dexamethasone(8), ondansetron(), paracetamol()],
      targets: ["Euthyroïdie obligatoire avant une chirurgie programmée", "Réveil sans toux ni effort"],
      material: [...MONITORING, "Sonde avec électrodes de monitorage du nerf récurrent (si demandée : curare de courte durée à l'intubation seulement)", "Vidéolaryngoscope", "Protection oculaire (exophtalmie)"],
      risks: [
        { title: "Intubation difficile", conduct: "Trachée déviée ou comprimée : bilan (scanner), vidéolaryngoscope ou fibroscope, sonde armée si trachéomalacie." },
        { title: "Hématome compressif", conduct: "Dyspnée, stridor : ouverture de la plaie au lit, réintubation." },
        { title: "Hypocalcémie, paralysie récurrentielle", conduct: "Calcémie postopératoire ; laryngospasme possible." },
      ],
      postop: ["Surveillance de la voie aérienne et de la loge", "Calcémie à J1"],
      notes: "Éviter anticholinergiques et kétamine (hyperthyroïdie) ; phényléphrine plutôt qu'éphédrine. Pas d'antibioprophylaxie en règle (chirurgie propre sans implant) : suivre le protocole du service.",
    }),
  },
  {
    id: pid(11),
    name: "Résection transurétrale de prostate sous rachianesthésie",
    surgery: "Résection transurétrale de la prostate",
    operation_category: "J2",
    hospital: "",
    source: `${MANUAL}, chap. 13, 20 et 35.`,
    content: content({
      techniques: ["neuraxial"],
      drugs: [
        drug("Bupivacaïne 0,5 % hyperbare", "alr", "intrathecal", { fixed: 10 }, "mg", "Niveau T10 ; patient conscient : détection précoce d'un syndrome de résorption."),
        drug("Céfuroxime", "antibio", "bolus_iv", { fixed: 1.5 }, "g", "Selon l'ECBU (stérile avant la chirurgie) et le protocole du service (manuel, chap. 20).", 240),
        paracetamol(),
      ],
      targets: ["Surveillance de la natrémie si résection longue (> 60 min) ou irrigation au glycocolle", "Normothermie (irrigation réchauffée)"],
      material: [...MONITORING, "Liquide d'irrigation réchauffé", "Natrémie au bloc"],
      risks: [
        { title: "Syndrome de résorption (TURP syndrome)", conduct: "Confusion, nausées, troubles visuels, bradycardie, hypertension puis hypotension : arrêter la résection, natrémie, furosémide si surcharge ; NaCl hypertonique si Na < 120 mmol/l symptomatique." },
        { title: "Perforation vésicale", conduct: "Douleur scapulaire ou abdominale, hypotension : arrêt et bilan." },
      ],
      postop: ["Irrigation continue", "Natrémie si symptômes"],
      notes: "Résection bipolaire au sérum physiologique : pas d'hyponatrémie de dilution, mais surcharge volémique possible.",
    }),
  },
  {
    id: pid(12),
    name: "Hystérectomie par cœlioscopie",
    surgery: "Hystérectomie",
    operation_category: "J1",
    hospital: "",
    source: `${HARDY} ; ${MANUAL}, chap. 20, 23 et 30 ; ERAS Society gynécologie.`,
    content: content({
      techniques: ["general"],
      drugs: [
        propofolInduction(),
        sufentanil(),
        rocuronium(),
        dexamethasone(8),
        cefazolin("Avant l'incision ; > 120 kg : 3 g ; réinjection à 4 h."),
        drug("Métronidazole", "antibio", "perfusion", { fixed: 500 }, "mg", "Voie vaginale ou ouverture vaginale selon le protocole du service."),
        ondansetron(),
        droperidol(),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["Trendelenburg et pneumopéritoine : pressions de ventilation, PEP", "Euvolémie"],
      material: [...MONITORING, "Curamètre", "Protection des points d'appui (jambes écartées)", "Compression pneumatique"],
      risks: [{ title: "Trendelenburg prolongé", conduct: "Œdème facial et laryngé (test de fuite avant l'extubation), glissement du patient, pression intraoculaire." }],
      postop: ["Réalimentation précoce", "Thromboprophylaxie selon le risque", "NVPO fréquents : double prophylaxie"],
    }),
  },
  {
    id: pid(13),
    name: "Cataracte sous anesthésie topique",
    surgery: "Cataracte",
    operation_category: "I",
    hospital: "",
    source: `${MANUAL}, chap. 38.`,
    content: content({
      techniques: ["sedation"],
      drugs: [drug("Midazolam", "premed", "bolus_iv", { fixed: 1 }, "mg", "Sédation légère seulement si nécessaire : une sédation profonde fait bouger.")],
      targets: ["Patient coopérant, capable de rester à plat 20–30 min", "Glycémie et PA contrôlées sans retarder le geste"],
      material: ["ECG", "PNI", "SpO₂", "O₂ sous les champs (lunettes)"],
      risks: [{ title: "Agitation ou toux", conduct: "Arrêt du geste ; rester en contact verbal." }],
      postop: ["Sortie rapide", "Collyres selon l'ophtalmologue"],
      notes: "Antithrombotiques poursuivis pour une anesthésie topique (voir les règles). Pas d'antibioprophylaxie IV (céfuroxime intracamérulaire par l'ophtalmologue).",
    }),
  },
  {
    id: pid(14),
    name: "Chirurgie bariatrique (sleeve, bypass) par cœlioscopie",
    surgery: "Chirurgie bariatrique",
    operation_category: "A",
    hospital: "",
    source: `${HARDY} ; ${MANUAL}, chap. 20 et 44.`,
    content: content({
      techniques: ["general"],
      drugs: [
        drug("Propofol", "induction", "bolus_iv", { perKg: 2, basis: "adjusted" }, "mg", "Au poids corrigé (manuel, chap. 44)."),
        drug("Sufentanil", "induction", "bolus_iv", { perKg: 0.2, basis: "lean" }, "µg", "Au poids maigre."),
        drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6, basis: "ideal" }, "mg", "Au poids idéal ; sugammadex en fin d'intervention au poids réel."),
        drug("Céfazoline", "antibio", "bolus_iv", { fixed: 3 }, "g", "> 120 kg : 3 g (sinon 2 g) ; réinjection à 4 h.", 240),
        ketamineSparing(),
        drug("Dexaméthasone", "ponv", "bolus_iv", { fixed: 8 }, "mg", "NVPO."),
        ondansetron(),
        paracetamol(),
      ],
      targets: ["Préoxygénation proclive avec PEP", "PEP 8–10 cmH₂O et recrutements", "Vt 6–8 ml/kg de poids idéal"],
      material: [...MONITORING, "Coussin de rampe", "Vidéolaryngoscope", "Brassard adapté", "Curamètre", "Compression pneumatique"],
      risks: [
        { title: "Intubation et ventilation difficiles", conduct: "Rampe, préoxygénation proclive, vidéolaryngoscope ; séquence rapide seulement si reflux ou anneau gastrique." },
        { title: "SAOS", conduct: "Épargne morphinique (kétamine, AINS, infiltrations), extubation semi-assise, PPC en SSPI si appareillé." },
      ],
      postop: ["Lever le jour même", "HBPM à dose adaptée au poids", "PPC si SAOS appareillé"],
      notes: "Poids : idéal pour le rocuronium, corrigé pour l'induction au propofol, maigre pour les morphiniques (manuel, chap. 44).",
    }),
  },
  {
    id: pid(15),
    name: "Arthroscopie du genou en ambulatoire",
    surgery: "Arthroscopie du genou",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} (rachianesthésie courte, antibioprophylaxie) ; ${MANUAL}, chap. 13 et 23.`,
    content: content({
      techniques: ["neuraxial", "general"],
      drugs: [
        drug("Prilocaïne 2 % hyperbare (Tachipri)", "alr", "intrathecal", { fixed: 50 }, "mg", "2–3 ml ; 100–130 min, sortie ≈ 4 h (cours Dubois)."),
        drug("Chloroprocaïne 1 % (Ampres)", "alr", "intrathecal", { fixed: 45 }, "mg", "Alternative si geste court (40–45 min), sortie ≈ 3 h."),
        paracetamol(),
        ketorolac(),
        dexamethasone(8),
      ],
      targets: ["Critères de sortie : miction, marche avec béquilles, douleur < 4, pas de NVPO"],
      material: ["ECG", "PNI", "SpO₂", "Garrot pneumatique si utilisé"],
      tourniquetAlertMin: 90,
      risks: [{ title: "Rétention urinaire", conduct: "Pas de morphine intrathécale ; échographie vésicale si pas de miction." }],
      postop: ["Sortie le jour même", "Thromboprophylaxie selon le risque et le geste"],
      notes: "Arthroscopie sans implant : pas d'antibioprophylaxie (cours Dubois) ; ligamentoplastie : céfazoline 2 g. AG au masque laryngé possible.",
    }),
  },
  {
    id: pid(16),
    name: "Chirurgie de la main (canal carpien) en ambulatoire",
    surgery: "Chirurgie de la main",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} (ALR du membre supérieur) ; ${MANUAL}, chap. 12.`,
    content: content({
      techniques: ["superficial_block"],
      drugs: [
        drug("Lidocaïne 0,5 % (ALRIV)", "alr", "iv_regional", { perKg: 3, max: 250 }, "mg", "Bloc de Bier : 3–4 mg/kg (manuel, chap. 12) ; garrot double, jamais lâché avant 20–30 min."),
        drug("Ropivacaïne (bloc axillaire, alternative)", "alr", "perinerveux", { fixed: 100 }, "mg", "Échoguidé ; dose maximale 3 mg/kg (cumul avec toute infiltration)."),
        paracetamol(),
      ],
      targets: ["Garrot au bras : PAS + 70–100 mmHg"],
      material: ["ECG", "PNI", "SpO₂", "Garrot double (ALRIV)", "Intralipides disponibles"],
      tourniquetAlertMin: 60,
      risks: [{ title: "Toxicité des anesthésiques locaux (ALRIV)", conduct: "Garrot vérifié, lâcher progressif ; convulsions, arythmie : arrêt de l'injection, oxygène, benzodiazépine, intralipides 20 % 1,5 ml/kg." }],
      postop: ["Sortie le jour même", "Paracétamol et AINS"],
      notes: "Pas d'antibioprophylaxie (tissus mous sans implant, cours Dubois). Anesthésie locale par le chirurgien (WALANT) possible.",
    }),
  },
  {
    id: pid(17),
    name: "Hystéroscopie opératoire ou curetage",
    surgery: "Hystéroscopie",
    operation_category: "J1",
    hospital: "",
    source: `${MANUAL}, chap. 23 et 35.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), drug("Sufentanil", "induction", "bolus_iv", { perKg: 0.1, basis: "lean" }, "µg", "Geste court ; ou alfentanil."), dexamethasone(4), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Masque laryngé", "Bilan entrées-sorties du liquide de distension"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Masque laryngé"],
      risks: [{ title: "Résorption du liquide de distension", conduct: "Déficit > 1 000 ml (liquide hypotonique) ou > 2 500 ml (sérum physiologique) : arrêt du geste, natrémie, diurétique si surcharge (comme le syndrome de résection prostatique)." }],
      postop: ["Sortie le jour même", "Saignement vaginal à surveiller"],
      notes: "Pas d'antibioprophylaxie en règle pour une hystéroscopie diagnostique ou un curetage simple : suivre le protocole du service.",
    }),
  },
  {
    id: pid(18),
    name: "Endoscopie digestive sous sédation (propofol)",
    surgery: "Coloscopie",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 6 et 42 (anesthésie hors bloc).`,
    content: content({
      techniques: ["sedation"],
      drugs: [
        drug("Propofol (titration)", "induction", "bolus_iv", { fixed: 20 }, "mg", "Titration par 10–20 mg (dose d'usage) ou perfusion de 2–6 mg/kg/h (manuel, chap. 6) ; doses réduites chez le sujet âgé."),
        drug("Lidocaïne (injection du propofol)", "premed", "bolus_iv", { fixed: 20 }, "mg", "Douleur à l'injection."),
      ],
      targets: ["Ventilation spontanée, SpO₂ ≥ 94 %", "Capnographie (dépression respiratoire)"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (lunettes à capnographie)", "Aspiration", "Matériel de ventilation et d'intubation à portée"],
      risks: [
        { title: "Dépression respiratoire", conduct: "Subluxation, oxygène, arrêt de l'injection ; ventilation au masque si besoin." },
        { title: "Inhalation (gastroscopie, occlusion)", conduct: "Jeûne respecté ; estomac plein ou achalasie : intubation." },
      ],
      postop: ["Surveillance jusqu'au retour de la conscience, sortie accompagnée"],
      notes: "Hors bloc : même niveau de monitorage et de matériel qu'au bloc (manuel, chap. 42). Pas d'antibioprophylaxie en règle (sauf CPRE avec obstruction biliaire, selon le gastro-entérologue).",
    }),
  },
  {
    id: pid(19),
    name: "Chirurgie du sein (tumorectomie, mastectomie)",
    surgery: "Chirurgie du sein",
    operation_category: "A",
    hospital: "",
    source: `${MANUAL}, chap. 12, 20 et 23 ; ESRA PROSPECT (chirurgie du sein).`,
    content: content({
      techniques: ["general", "deep_block"],
      drugs: [
        propofolInduction(),
        sufentanil(),
        drug("Ropivacaïne (bloc PECS ou serratus)", "alr", "perinerveux", { fixed: 100 }, "mg", "Échoguidé ; dose maximale 3 mg/kg."),
        cefazolin("Dans l'heure avant l'incision (mastectomie, prothèse) ; > 120 kg : 3 g."),
        clindamycinAlt(),
        dexamethasone(8),
        ondansetron(),
        paracetamol(),
        ketorolac(),
      ],
      targets: ["Masque laryngé possible pour une tumorectomie"],
      material: [...MONITORING, "Échographe"],
      risks: [{ title: "NVPO fréquents", conduct: "Double prophylaxie (dexaméthasone + sétron), épargne morphinique par le bloc." }],
      postop: ["Bras du côté du curage : pas de brassard ni de perfusion (lymphœdème)", "Sortie le jour même pour une tumorectomie"],
      notes: "Allergie au bleu patenté (ganglion sentinelle) : à rechercher.",
    }),
  },
  // --- Protocols after the PROSPECT recommendations (ESRA) ---------------------------------------
  {
    id: pid(20),
    name: "Appendicectomie par cœlioscopie",
    surgery: "Appendicectomie par cœlioscopie",
    operation_category: "A",
    hospital: "",
    source: `${PROSPECT_REF("appendicectomie", 2024, "38214556")} ; ${MANUAL}, chap. 20 et 23.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), metronidazole(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), drug("Bupivacaïne intrapéritonéale", "alr", "infiltration", { fixed: 50 }, "mg", "Instillation intrapéritonéale d'anesthésique local (PROSPECT) ; dose totale ≤ 2 mg/kg.")],
      targets: ["PAM ≥ 65 mmHg", "Normothermie ≥ 36 °C", "TOF ≥ 0,9 avant l'extubation"],
      material: [...MONITORING, "Curarimètre (TOF)"],
      risks: [risk("aspiration"), risk("ponv")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], ponvRescue: true }),
      notes: "Urgence souvent : estomac plein → séquence rapide. Voie ouverte : TAP unilatéral préopératoire ou infiltration pré-incisionnelle (PROSPECT). Appendicite compliquée : antibiothérapie, pas prophylaxie.",
    }),
  },
  {
    id: pid(21),
    name: "Colectomie par laparotomie avec péridurale",
    surgery: "Colectomie par laparotomie",
    operation_category: "A",
    hospital: "",
    source: `${PROSPECT_REF("chirurgie colorectale ouverte", 2024, "38420876")} ; ${HARDY} ; ${MANUAL}, chap. 20, 25 et 30.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), metronidazole(), dexamethasone(8), ondansetron(), paracetamol()],
      targets: ["PAM ≥ 65 mmHg", "Normothermie ≥ 36 °C", "Balance hydrique proche de zéro"],
      material: [...MONITORING, "Curarimètre (TOF)", "Cathéter péridural thoracique", "Sonde urinaire", "Réchauffeur à air pulsé"],
      risks: [risk("induction_hypotension"), risk("hypothermia"), risk("bleeding")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", ponvRescue: true, watch: ["pain", "sedation", "block", "urine"] }),
      notes: "Péridurale thoracique basse avant l'induction. Sans péridurale : TAP bilatéral ou lidocaïne IV (PROSPECT), jamais deux voies d'anesthésique local en même temps. AINS pour le côlon seulement (pas pour le rectum).",
    }),
  },
  {
    id: pid(22),
    name: "Hépatectomie par laparotomie",
    surgery: "Hépatectomie par laparotomie",
    operation_category: "A",
    hospital: "",
    source: `${PROSPECT_REF("hépatectomie ouverte", 2021, "33436442")} ; ${MANUAL}, chap. 20, 25 et 30.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), tranexamic()],
      targets: ["PVC basse pendant la transection si demandée par le chirurgien", "PAM ≥ 65 mmHg", "Normothermie ≥ 36 °C"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "Cathéter péridural thoracique", "2 VVP de gros calibre (16–14G)", "Groupe et RAI", "Réchauffeur de solutés"],
      risks: [risk("bleeding"), risk("gas_embolism"), risk("hypothermia")],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "sedation", "bleeding", "glucose", "hb"] }),
      notes: "PROSPECT : péridurale thoracique continue ou TAP sous-costaux obliques bilatéraux. Coagulation postopératoire à contrôler avant le retrait du cathéter (hépatectomie majeure). Paracétamol et AINS selon la fonction hépatique et rénale.",
    }),
  },
  {
    id: pid(23),
    name: "Prostatectomie radicale robot-assistée",
    surgery: "Prostatectomie radicale robot-assistée",
    operation_category: "J2",
    hospital: "",
    source: `${PROSPECT_REF("prostatectomie", 2021, "34197976")} ; ${MANUAL}, chap. 20 et 30.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(0.6), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ropivacaineBlock(150, "TAP bilatéral en fin d'intervention")],
      targets: ["Curarisation profonde, TOF monitoré", "Restriction liquidienne jusqu'à l'anastomose", "PAM ≥ 65 mmHg"],
      material: [...MONITORING, "Curarimètre (TOF)", "Protection des points d'appui", "2 VVP 18G (bras le long du corps)"],
      risks: [{ title: "Trendelenburg marqué prolongé", why: "Pneumopéritoine et tête très basse pendant des heures : œdème facial et laryngé, hypoxémie, pression intraoculaire.", prevention: "Restriction liquidienne peropératoire, ventilation protectrice, yeux protégés, bras et épaules calés.", conduct: "Vérifier l'œdème avant l'extubation (test de fuite) ; tête surélevée au réveil." }, risk("ponv")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", ponvRescue: true }),
      notes: "Robot arrimé : accès au patient limité, prévoir la conduite en cas d'urgence (désarrimage). Voie ouverte : lidocaïne IV et infiltration de la plaie (PROSPECT).",
    }),
  },
  {
    id: pid(24),
    name: "Lobectomie par thoracoscopie (VATS)",
    surgery: "Lobectomie pulmonaire",
    operation_category: "G",
    hospital: "",
    source: `${PROSPECT_REF("VATS", 2021, "34739134")} ; ${MANUAL}, chap. 20 et 26.`,
    content: content({
      techniques: ["general", "deep_block"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ropivacaineBlock(150, "paravertébral ou ESP")],
      targets: ["Ventilation unipulmonaire protectrice (Vt 4–6 mL/kg de poids idéal sur un poumon, PEP)", "SpO₂ ≥ 90 %", "Restriction liquidienne"],
      material: [...MONITORING, "Sonde double lumière", "Fibroscope", "Cathéter artériel", "Échographe"],
      risks: [{ title: "Hypoxémie en ventilation unipulmonaire", why: "Shunt par le poumon exclu, encore perfusé ; plus fréquent à droite, en décubitus dorsal et si la fonction respiratoire préopératoire est bonne.", prevention: "Position de la sonde vérifiée au fibroscope (et après chaque mobilisation), FiO₂ adaptée, PEP 5 cmH₂O au poumon ventilé, recrutement avant l'exclusion.", conduct: "FiO₂ 100 %, revérifier la sonde au fibroscope, aspirer, recrutement du poumon ventilé, CPAP 5–10 cmH₂O au poumon exclu, puis réventilation intermittente des deux poumons ; clamper l'artère pulmonaire si pneumonectomie." }, risk("bleeding")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", watch: ["pain", "sedation"] }),
      notes: "PROSPECT : paravertébral ou ESP en premier choix, serratus antérieur en second ; dexmédétomidine IV si analgésie de base et régionale impossibles.",
    }),
  },
  {
    id: pid(25),
    name: "Thoracotomie avec péridurale thoracique",
    surgery: "Lobectomie par thoracotomie",
    operation_category: "G",
    hospital: "",
    source: `${PROSPECT_REF("thoracotomie", 2026, "41521792")} ; ${MANUAL}, chap. 20, 25 et 26.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Ventilation unipulmonaire protectrice", "SpO₂ ≥ 90 %", "Restriction liquidienne (pneumonectomie : < 3 L les 24 premières heures, manuel chap. 21)"],
      material: [...MONITORING, "Sonde double lumière", "Fibroscope", "Cathéter artériel", "Cathéter péridural thoracique"],
      risks: [{ title: "Hypoxémie en ventilation unipulmonaire", why: "Shunt par le poumon exclu, encore perfusé ; plus fréquent à droite, en décubitus dorsal et si la fonction respiratoire préopératoire est bonne.", prevention: "Position de la sonde vérifiée au fibroscope (et après chaque mobilisation), FiO₂ adaptée, PEP 5 cmH₂O au poumon ventilé, recrutement avant l'exclusion.", conduct: "FiO₂ 100 %, revérifier la sonde au fibroscope, aspirer, recrutement du poumon ventilé, CPAP 5–10 cmH₂O au poumon exclu, puis réventilation intermittente des deux poumons ; clamper l'artère pulmonaire si pneumonectomie." }, risk("bleeding")],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "nsaid", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh_mechanical", watch: ["pain", "sedation", "block"] }),
      notes: "PROSPECT 2025 : péridurale thoracique ou paravertébral en premier choix ; ESP, rhomboïde-intercostal ou intercostal en second.",
    }),
  },
  {
    id: pid(26),
    name: "Craniotomie programmée",
    surgery: "Craniotomie pour tumeur",
    operation_category: "D",
    hospital: "",
    source: `${PROSPECT_REF("craniotomie", 2023, "37417808")} ; ${MANUAL}, chap. 20 et 28.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), drug("Rémifentanil", "maintenance", "aivoc", { perKg: 0.5 }, "µg", "Bolus 0,5 µg/kg avant la pose de la têtière à pointes ; entretien 0,1–0,25 µg/kg/min ou AIVOC 2–5 ng/mL (manuel, chap. 7 et 22)."), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), drug("Dexmédétomidine", "analgesia", "pse", { perKg: 1 }, "µg", "Charge 1 µg/kg en 10 min puis 0,2–0,7 µg/kg/h (manuel, chap. 10) ; recommandée par PROSPECT. Bradycardie : réduire.")],
      targets: ["PAM stable (perfusion cérébrale), normocapnie", "Normoglycémie", "Réveil rapide pour l'examen neurologique"],
      material: [...MONITORING, "Cathéter artériel", "Sonde urinaire", "Curarimètre (TOF)"],
      risks: [risk("delayed_awakening"), risk("ponv")],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "nsaid"], thrombo: "mechanical", watch: ["pain", "neuro", "glucose"] }),
      notes: "PROSPECT : paracétamol, AINS, dexmédétomidine IV et bloc du scalp ou infiltration du site d'incision ; opioïdes en secours. AINS à discuter avec le neurochirurgien (saignement).",
    }),
  },
  {
    id: pid(27),
    name: "Hémorroïdectomie",
    surgery: "Hémorroïdectomie",
    operation_category: "A",
    hospital: "",
    source: `${PROSPECT_REF("hémorroïdectomie", 2023, "39917290")} ; ${MANUAL}, chap. 20 et 23.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [propofolInduction(), sufentanil(0.1), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ropivacaineBlock(75, "bloc pudendal bilatéral")],
      targets: ["Masque laryngé si position le permet"],
      material: [...MONITORING, "Échographe ou neurostimulateur (bloc pudendal)"],
      risks: [risk("ponv")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], watch: ["pain", "urine"] }),
      notes: "PROSPECT : bloc pudendal bilatéral, corticoïde systémique ; topiques (métronidazole, diltiazem, sucralfate ou trinitrine), toxine botulique. Antibioprophylaxie selon le protocole du service.",
    }),
  },
  {
    id: pid(28),
    name: "Hallux valgus en ambulatoire",
    surgery: "Chirurgie de l'avant-pied",
    operation_category: "K",
    hospital: "",
    source: `${PROSPECT_REF("hallux valgus", 2025, "41122054")} ; ${DUBOIS} ; ${MANUAL}, chap. 12.`,
    content: content({
      techniques: ["superficial_block", "general"],
      drugs: [ropivacaineBlock(100, "bloc de cheville"), propofolInduction(), dexamethasone(8), paracetamol(), ketorolac()],
      targets: ["Garrot de cheville : durée surveillée"],
      material: [...MONITORING, "Échographe", "Garrot"],
      tourniquetAlertMin: 90,
      risks: [risk("last")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], watch: ["pain", "neuro"] }),
      notes: "PROSPECT 2025 : bloc de cheville en premier choix (infiltration en alternative), chirurgie mini-invasive ou percutanée préférée. Antibioprophylaxie seulement si matériel (vis, plaque) : céfazoline 2 g selon le protocole du service.",
    }),
  },
  {
    id: pid(29),
    name: "Arthrodèse lombaire (rachis complexe)",
    surgery: "Arthrodèse rachidienne",
    operation_category: "K",
    hospital: "",
    source: `${PROSPECT_REF("chirurgie complexe du rachis", 2021, "34397527")} ; ${MANUAL}, chap. 20 et 40.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), tranexamic(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ketamineSparing()],
      targets: ["PAM ≥ 65 mmHg (moelle, yeux en décubitus ventral)", "Normothermie ≥ 36 °C"],
      material: [...MONITORING, "Cathéter artériel", "Protection des points d'appui", "Cell saver", "Groupe et RAI"],
      risks: [risk("bleeding"), { title: "Décubitus ventral", why: "Compression oculaire (cécité postopératoire), points d'appui, abdomen comprimé (saignement épidural).", prevention: "Tête neutre, yeux libres vérifiés, abdomen libre, appuis rembourrés, PAM maintenue.", conduct: "Vérifier les yeux régulièrement ; hypotension prolongée à éviter." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "pca_morphine", "ketamine"], thrombo: "mechanical", watch: ["pain", "sedation", "neuro", "hb"] }),
      notes: "PROSPECT : paracétamol, anti-COX-2 ou AINS, kétamine peropératoire ; péridurale posée par le chirurgien possible. AINS à discuter avec le chirurgien (fusion osseuse). Potentiels évoqués : TIVA.",
    }),
  },
  {
    id: pid(30),
    name: "Décompression lombaire ou hernie discale",
    surgery: "Décompression lombaire",
    operation_category: "D",
    hospital: "",
    source: `${PROSPECT_REF("laminectomie", 2020, "33247353")} ; ${MANUAL}, chap. 20.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), drug("Bupivacaïne (infiltration de la plaie)", "alr", "infiltration", { fixed: 50 }, "mg", "Avant la fermeture (PROSPECT) ; ≤ 2 mg/kg.")],
      targets: ["PAM ≥ 65 mmHg"],
      material: [...MONITORING, "Protection des points d'appui"],
      risks: [risk("ponv")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], watch: ["pain", "neuro"] }),
      notes: "PROSPECT : paracétamol et AINS ou anti-COX-2 poursuivis, infiltration ou instillation de la plaie ; gabapentinoïdes et opioïdes intrathécaux non recommandés (risques).",
    }),
  },
  {
    id: pid(31),
    name: "Réparation de la coiffe des rotateurs",
    surgery: "Réparation de la coiffe des rotateurs",
    operation_category: "K",
    hospital: "",
    source: `${PROSPECT_REF("coiffe des rotateurs", 2019, "31392721")} ; ${DUBOIS} ; ${MANUAL}, chap. 12 et 19.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [ropivacaineBlock(75, "bloc interscalénique ou suprascapulaire"), propofolInduction(), sufentanil(0.1), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Position semi-assise : PA mesurée ou corrigée au niveau du cerveau"],
      material: [...MONITORING, "Échographe"],
      risks: [{ title: "Bloc interscalénique : paralysie phrénique", why: "Parésie diaphragmatique homolatérale quasi constante.", prevention: "Éviter si insuffisance respiratoire ; bloc suprascapulaire en alternative.", conduct: "Dyspnée : position assise, oxygène ; évolution favorable avec la levée du bloc." }, risk("last")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], watch: ["pain", "block"] }),
      notes: "PROSPECT : voie arthroscopique, paracétamol, AINS, dexaméthasone, bloc interscalénique ou suprascapulaire (± nerf axillaire).",
    }),
  },
  {
    id: pid(32),
    name: "Fente palatine de l'enfant",
    surgery: "Fente labio-palatine",
    operation_category: "L",
    hospital: "",
    source: `${PROSPECT_REF("fente palatine", 2024, "38124208")} ; ${MANUAL}, chap. 37 ; ${ESAIC_FASTING}.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [drug("Propofol", "induction", "bolus_iv", { perKg: 3 }, "mg", "Enfant : 2,5–4 mg/kg (manuel, chap. 37) ; ou induction au sévoflurane."), drug("Ropivacaïne (bloc maxillaire suprazygomatique)", "alr", "perinerveux", { perKg: 0.3, max: 30 }, "mg", "Bilatéral ; dose totale ≤ 3 mg/kg (manuel, chap. 12)."), cefazolin("Enfant : 30 mg/kg, dans l'heure avant l'incision."), drug("Paracétamol", "analgesia", "perfusion", { perKg: 15 }, "mg", "15 mg/kg 4 ×/j (manuel, chap. 37).")],
      targets: ["Sonde préformée (RAE), fixation médiane", "Normothermie"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Température", "Échographe", "Canule de Guedel adaptée"],
      risks: [risk("laryngospasm"), { title: "Obstruction des voies aériennes au réveil", why: "Palais refait, œdème, saignement ; langue parfois fixée par un fil.", prevention: "Aspiration douce, extubation complètement réveillé, décubitus latéral.", conduct: "Fil de traction de langue, canule nasopharyngée, réintubation si besoin (difficile)." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], watch: ["pain", "sedation"] }),
      notes: "PROSPECT : bloc du nerf maxillaire suprazygomatique (ou palatin), dexmédétomidine avec l'anesthésique local ou IV, paracétamol et AINS. Doses au poids de l'enfant.",
    }),
  },
  {
    id: pid(33),
    name: "Chirurgie cardiaque sous CEC (sternotomie)",
    surgery: "Pontages aorto-coronariens sous CEC",
    operation_category: "F",
    hospital: "",
    source: `${PROSPECT_REF("sternotomie", 2023, "37501517")} ; EACTS/EACTA/EBCP : circulation extracorporelle de l'adulte 2019 (PMID 31576396) ; ${MANUAL}, chap. 20, 27 et 40.`,
    content: content({
      techniques: ["general"],
      drugs: [
        drug("Étomidate ou propofol titré", "induction", "bolus_iv", { perKg: 0.3 }, "mg", "Induction lente et titrée (étomidate 0,2–0,3 mg/kg) : fonction ventriculaire altérée, maintenir la pression de perfusion coronaire."),
        sufentanil(0.5),
        rocuronium(),
        cefazolin("2 g dans l'heure avant l'incision (3 g si > 120 kg) ; seconde dose 3–4 h après ou si pertes > 1 500 mL (manuel, chap. 20)."),
        tranexamic(),
        drug("Héparine (CEC)", "haemodynamic", "bolus_iv", { perKg: 300 }, "UI", "300–400 UI/kg avant la canulation, sur demande du chirurgien ; ACT 400–480 s (cœur battant : ACT 250 s) (manuel, chap. 27). Antécédent de TIH : contre-indiquée."),
        drug("Protamine", "haemodynamic", "perfusion", { perKg: 3 }, "mg", "Après la sortie de CEC, lentement : 1 mg pour 100 UI d'héparine, puis 25–50 mg si le saignement persiste (manuel, chap. 27) ; hypotension, HTAP, anaphylaxie possibles."),
        paracetamol(),
        drug("Magnésium", "analgesia", "perfusion", { perKg: 40 }, "mg", "Adjuvant proposé par PROSPECT (et prévention des arythmies) ; 40–50 mg/kg sur 15 min (manuel, chap. 7)."),
      ],
      targets: ["PAM ≥ 65 mmHg (plus si sténose carotidienne ou insuffisance rénale)", "Normoglycémie (< 10 mmol/L)", "Hb selon la situation : transfusion si < 7,5–8 g/dL (restrictive)", "Normothermie au sevrage"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "ETO", "BIS", "Sonde urinaire", "Défibrillateur, palettes internes", "Sang en salle"],
      risks: [risk("bleeding"), risk("hypothermia"), { title: "Sevrage difficile de la CEC", why: "Sidération myocardique, protection incomplète, vasoplégie.", prevention: "ETO avant sevrage, normothermie, potassium et calcium corrigés, rythme contrôlé (entraînement électrosystolique).", conduct: "Inotropes (dobutamine, adrénaline) ou noradrénaline selon l'ETO ; retour en CEC si échec ; ballon de contre-pulsion ou assistance à discuter." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "mechanical", watch: ["pain", "bleeding", "hb", "glucose", "potassium", "troponin", "delirium"] }),
      notes: "PROSPECT : paracétamol et AINS (sauf contre-indication — souvent contre-indiqués après pontage : à décider avec l'équipe), magnésium ou dexmédétomidine peropératoires, bloc parasternal ou infiltration ; opioïdes en secours. Anticoagulation et sevrage de CEC selon le protocole local.",
    }),
  },
];

export const REFERENCE_PROTOCOLS: ReferenceProtocol[] = [...FIRST_REFERENCE_PROTOCOLS, ...MORE_REFERENCE_PROTOCOLS, ...CHILDREN_AND_OTHER_PROTOCOLS];
