// Reference protocols, third part: head and neck, eye, neurosurgery, chest
// and heart, limbs, plastic surgery, children, and procedures outside the
// theatre. Same rule as the others: a starting point with a named source for
// every dose, to adapt to the service's protocol.

import {
  DUBOIS,
  ESAIC_FASTING,
  MANUAL,
  MONITORING,
  PROSPECT_REF,
  cefazolin,
  content,
  dexamethasone,
  drug,
  droperidol,
  ketamineSparing,
  ketorolac,
  ondansetron,
  paracetamol,
  pid,
  postop,
  propofolInduction,
  risk,
  rocuronium,
  ropivacaineBlock,
  sufentanil,
  tranexamic,
  type ReferenceProtocol,
} from "./reference-protocol-kit";
import { DEFAULT_PCEA, DEFAULT_PERINEURAL } from "./postop";

const CHILD = `${MANUAL}, chap. 37 (enfant) ; ${ESAIC_FASTING}`;
const ERAS_NEONATE = "ERAS nouveau-né 2024 (PMID 39083294) ; ERAS chirurgie intestinale néonatale 2020 (PMID 32385680)";
const ERAS_BREAST = "ERAS reconstruction mammaire 2017 (PMID 28445352)";
const ERAS_SPINE = "ERAS arthrodèse lombaire 2021 (PMID 33444664)";

const remifentanil = () => drug("Rémifentanil", "maintenance", "pse", { perKg: 0.5 }, "µg", "Bolus 0,2–1 µg/kg ; entretien 0,1–0,5 µg/kg/min (manuel, chap. 7).");
const noradrenaline = (note = "Perfusion 0,05–0,3 µg/kg/min titrée sur la PAM.") => drug("Noradrénaline", "haemodynamic", "pse", { fixed: 8 }, "µg", note);
const sedationPropofol = () => drug("Propofol (sédation)", "maintenance", "pse", { fixed: 20 }, "mg", "Titré par bolus de 10–20 mg ou AIVOC 1–2 µg/mL (manuel, chap. 22).");
const sedationRemi = () => drug("Rémifentanil (sédation)", "maintenance", "pse", { fixed: 20 }, "µg", "0,02–0,05 µg/kg/min en ventilation spontanée (manuel, chap. 7).");
const lidocaineTopical = () => drug("Lidocaïne 5 % naphazolinée ou 4 % (topique)", "alr", "infiltration", { fixed: 100 }, "mg", "Méchage ou pulvérisation par le chirurgien ; maximum 4,5 mg/kg.");
// Children: doses per kilo, capped to the adult dose.
const childPremed = () => drug("Midazolam (prémédication)", "premed", "po", { perKg: 0.3, max: 15 }, "mg", "0,3–0,5 mg/kg per os, 20–30 min avant ; ou dexmédétomidine intranasale 1–2 µg/kg (manuel, chap. 37).");
const childPropofol = () => drug("Propofol", "induction", "bolus_iv", { perKg: 3 }, "mg", "2,5–5 mg/kg ; ou induction au sévoflurane puis voie veineuse (manuel, chap. 37).");
const childSufentanil = () => drug("Sufentanil", "induction", "bolus_iv", { perKg: 0.2 }, "µg", "0,1–0,3 µg/kg (manuel, chap. 37).");
const childAtropine = () => drug("Atropine", "premed", "bolus_iv", { perKg: 0.02, max: 0.6 }, "mg", "20 µg/kg si bradycardie (nourrisson, réflexe oculocardiaque, succinylcholine).");
const childParacetamol = () => drug("Paracétamol", "analgesia", "perfusion", { perKg: 15, max: 1000 }, "mg", "15 mg/kg IV ou per os, 4 × / jour (nouveau-né : voir le manuel, chap. 37).");
const childDexa = () => drug("Dexaméthasone", "ponv", "bolus_iv", { perKg: 0.15, max: 8 }, "mg", "0,1–0,2 mg/kg (manuel, chap. 38).");
const childOndansetron = () => drug("Ondansétron", "ponv", "bolus_iv", { perKg: 0.1, max: 4 }, "mg", "0,1 mg/kg (manuel, chap. 23).");
const childIbuprofen = () => drug("Ibuprofène", "analgesia", "po", { perKg: 10, max: 400 }, "mg", "10 mg/kg per os, 3 × / jour, après 3 mois (manuel, chap. 37).");
const childCefazolin = () => drug("Céfazoline", "antibio", "bolus_iv", { perKg: 30, max: 2000 }, "mg", "30 mg/kg, maximum 2 g, dans l'heure avant l'incision.");
const caudal = () => drug("Bupivacaïne 0,25 % (caudale)", "alr", "peridural", { perKg: 2.5 }, "mg", "1 mL/kg (T10) ; clonidine 1 µg/kg pour prolonger après 6 mois (manuel, chap. 37).");
const CHILD_MONITORING = ["ECG", "PNI", "SpO₂", "EtCO₂", "Température", "Matériel au poids (tableau du manuel, chap. 37)", "Réchauffement (air pulsé)"];

export const CHILDREN_AND_OTHER_PROTOCOLS: ReferenceProtocol[] = [
  // ============================================================ ORL et maxillo-facial
  {
    id: pid(66),
    name: "Chirurgie endonasale et des sinus",
    surgery: "Chirurgie endoscopique des sinus",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 38 (ORL).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), lidocaineTopical(), dexamethasone(8), ondansetron(), tranexamic(), paracetamol(), ketorolac()],
      targets: ["Champ exsangue : AIVOC propofol-rémifentanil, proclive 15–20°, PAM 60–70 mmHg chez le sujet sain", "Packing pharyngé si saignement, retiré avant l'extubation", "Réveil calme sans toux"],
      material: [...MONITORING, "Sonde préformée ou armée", "Deux aspirations"],
      risks: [risk("bleeding"), risk("ponv"), { title: "Inhalation de sang au réveil", why: "Saignement dégluti ou oublié dans le pharynx.", prevention: "Packing, aspiration sous contrôle de la vue, extubation éveillée en position latérale.", conduct: "Toux, désaturation : aspiration, O₂, radiographie si doute." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "bleeding"] }),
      notes: "Pas d'antibioprophylaxie en chirurgie nasale propre. Amygdalectomie et chirurgie du SAOS de l'adulte : sonde RAE, saignement, PROSPECT amygdalectomie 2021 (PMID 33201518) : paracétamol, AINS, dexaméthasone ; SAOS : opioïdes réduits, surveillance respiratoire. Septoplastie, rhinoplastie : mèches, respiration buccale au réveil. Épistaxis : estomac plein de sang, séquence rapide, patient souvent hypertendu ou anticoagulé. Hypophyse par voie endonasale : protocole neurochirurgie.",
    }),
  },
  {
    id: pid(67),
    name: "Chirurgie de l'oreille",
    surgery: "Tympanoplastie",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 23 (NVPO) et 38.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), remifentanil(), dexamethasone(8), ondansetron(), droperidol(), paracetamol(), ketorolac()],
      targets: ["Pas de N₂O (pression de l'oreille moyenne, greffe)", "Pas de curare après l'intubation si surveillance du nerf facial", "Champ exsangue, tête tournée sans étirer le cou"],
      material: [...MONITORING, "Monitorage du nerf facial selon le chirurgien"],
      risks: [risk("ponv"), { title: "Toux et agitation au réveil", why: "Déplacement de la greffe tympanique.", prevention: "Réveil sous rémifentanil, lidocaïne, extubation profonde selon l'équipe.", conduct: "Réveil calme, antiémétiques." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie (chirurgie propre) sauf implant cochléaire (céfazoline). NVPO très fréquentes : triple prophylaxie.",
    }),
  },
  {
    id: pid(68),
    name: "Endoscopie laryngée et trachéale (microchirurgie, laser, panendoscopie)",
    surgery: "Microchirurgie laryngée",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 38 (voies aériennes partagées).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), drug("Sugammadex", "other", "bolus_iv", { perKg: 2 }, "mg", "Geste court avec curarisation profonde : 2–4 mg/kg (manuel, chap. 8)."), dexamethasone(8), lidocaineTopical()],
      targets: ["Voies aériennes partagées : plan défini avec le chirurgien (sonde fine, jet-ventilation, apnée oxygénée à haut débit)", "Laser : FiO₂ < 0,3, sonde laser, ballonnet rempli de sérum coloré", "Curarisation profonde jusqu'à la fin"],
      material: [...MONITORING, "Sonde fine (5–6) ou sonde laser", "Jet-ventilateur", "Oxygène nasal à haut débit", "Vidéolaryngoscope", "Kit de cricothyroïdotomie"],
      risks: [risk("difficult_airway"), risk("laryngospasm"), { title: "Feu des voies aériennes (laser)", why: "Laser, oxygène et sonde combustible réunis.", prevention: "FiO₂ la plus basse possible, pas de N₂O, sonde adaptée, ballonnet au sérum.", conduct: "Arrêter la ventilation et l'O₂, retirer la sonde, sérum dans les voies aériennes, ventiler au masque, bronchoscopie." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie. Tumeur obstructive : évaluation préalable (fibroscopie, scanner), intubation vigile ou trachéotomie sous AL si doute. Zenker : séquence rapide tête surélevée.",
    }),
  },
  {
    id: pid(69),
    name: "Chirurgie carcinologique cervico-faciale et lambeau libre",
    surgery: "Chirurgie carcinologique tête et cou",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 38 ; ERAS tête et cou avec lambeau libre (Dort et al., JAMA Otolaryngol 2017).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(0.3), rocuronium(), drug("Amoxicilline-clavulanate", "antibio", "bolus_iv", { fixed: 2 }, "g", "Chirurgie contaminée (ouverture des voies aérodigestives) : 2 g, réinjection 1 g toutes les 2 h (protocole local) ; allergie : clindamycine + gentamicine."), dexamethasone(8), ondansetron(), paracetamol(), ketamineSparing(), tranexamic()],
      targets: ["Voies aériennes : évaluation, intubation vigile au fibroscope ou trachéotomie sous AL si tumeur obstructive", "Lambeau libre : normothermie, normovolémie, Hb 8–10 g/dL, PAM stable, pas de vasopresseur à forte dose", "Sevrage alcoolo-tabagique : prévention du delirium"],
      material: [...MONITORING, "Fibroscope", "Cathéter artériel", "Sonde urinaire", "Réchauffement", "Canule de trachéotomie"],
      risks: [risk("difficult_airway"), risk("bleeding"), { title: "Échec du lambeau libre", why: "Hypoperfusion, hypothermie, vasoconstriction, compression du pédicule.", prevention: "Normothermie, remplissage guidé, analgésie, pas de pansement compressif sur le pédicule.", conduct: "Lambeau pâle ou congestif : prévenir le chirurgien immédiatement (reprise)." }, { title: "Sevrage alcoolique", why: "Consommation chronique fréquente.", prevention: "Thiamine, benzodiazépines selon le score de sevrage.", conduct: "Agitation, tremblements : score CIWA, benzodiazépines." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "delirium", "bleeding"] }),
      notes: "Laryngectomie : trachéostome définitif, sonde armée par le stome. Curage cervical : hématome compressif. Parotidectomie : pas de curare (nerf facial).",
    }),
  },
  {
    id: pid(70),
    name: "ORL et voies aériennes de l'enfant (aérateurs, adénoïdes, larynx, corps étranger)",
    surgery: "Aérateurs transtympaniques",
    operation_category: "C",
    hospital: "",
    source: CHILD,
    content: content({
      techniques: ["general"],
      drugs: [childPremed(), childPropofol(), childParacetamol(), childDexa(), childIbuprofen()],
      targets: ["Induction au masque (sévoflurane) acceptable pour les gestes très courts", "Masque laryngé ou masque facial ; sonde préformée pour l'adénoïdectomie", "Larynx, trachée, corps étranger : voies aériennes partagées, ventilation spontanée sous propofol ou sévoflurane, plan partagé avec l'ORL, bronchoscope rigide prêt"],
      material: CHILD_MONITORING,
      risks: [risk("laryngospasm"), { title: "Infection des voies aériennes récente", why: "Hyperréactivité bronchique pendant 2–4 semaines.", prevention: "Report si fièvre ou infection basse ; sinon masque laryngé, pas de sonde si possible.", conduct: "Désaturation : laryngospasme ou bronchospasme, fiches de crise." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie. Jeûne ESAIC 2022 : liquides clairs jusqu'à 1 h. Corps étranger bronchique : obstruction complète possible, induction en ventilation spontanée. Laryngomalacie, sténose sous-glottique : œdème postopératoire (dexaméthasone), surveillance. Kyste du tractus thyréoglosse : sonde, curare possible.",
    }),
  },
  {
    id: pid(71),
    name: "Urgence ORL avec voies aériennes menacées (abcès, hémorragie)",
    surgery: "Abcès péri-amygdalien ou cervical profond",
    operation_category: "C",
    hospital: "",
    source: `${MANUAL}, chap. 38 ; DAS : intubation difficile (Frerk et al. 2015).`,
    content: content({
      techniques: ["general"],
      drugs: [drug("Kétamine", "induction", "bolus_iv", { perKg: 1 }, "mg", "1–2 mg/kg : ventilation spontanée préservée (manuel, chap. 6)."), propofolInduction(1.5), drug("Rocuronium (séquence rapide)", "induction", "bolus_iv", { perKg: 1.2 }, "mg", "Seulement une fois l'intubation jugée possible ; sugammadex 16 mg/kg prêt."), dexamethasone(8), drug("Amoxicilline-clavulanate", "antibio", "bolus_iv", { fixed: 2 }, "g", "Antibiothérapie de l'infection, déjà débutée ?")],
      targets: ["Plan A-B-C-D annoncé avant l'induction (DAS)", "Intubation vigile au fibroscope si trismus ou œdème ; oxygénation nasale à haut débit", "Chirurgien présent, cou préparé pour un accès chirurgical"],
      material: [...MONITORING, "Vidéolaryngoscope", "Fibroscope", "Sondes de petite taille", "Kit de cricothyroïdotomie", "Deux aspirations"],
      risks: [risk("difficult_airway"), risk("aspiration"), { title: "Rupture de l'abcès à l'intubation", why: "Collection pharyngée sous tension.", prevention: "Laryngoscopie douce, aspiration prête, tête basse.", conduct: "Aspiration, position tête basse, intubation rapide." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "none", watch: ["pain", "bleeding"] }),
      notes: "Hémorragie après amygdalectomie (J0 ou J5–J10) : hypovolémie sous-estimée chez l'enfant, estomac plein de sang, remplissage avant l'induction, séquence rapide, deux aspirations. Cellulite dentaire : trismus souvent levé par l'anesthésie seulement s'il est antalgique.",
    }),
  },
  {
    id: pid(72),
    name: "Chirurgie maxillo-faciale et dentaire",
    surgery: "Extraction des dents de sagesse",
    operation_category: "E",
    hospital: "",
    source: `${MANUAL}, chap. 38.`,
    content: content({
      techniques: ["general", "sedation"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), drug("Lidocaïne adrénalinée (infiltration dentaire)", "alr", "infiltration", { fixed: 72 }, "mg", "Par le chirurgien ; maximum 7 mg/kg."), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Intubation nasotrachéale (sonde nasale préformée), vasoconstricteur nasal", "Packing pharyngé, retiré et compté avant l'extubation", "Ostéotomies : hypotension contrôlée modérée, acide tranexamique"],
      material: [...MONITORING, "Sonde nasale préformée", "Pince de Magill", "Fibroscope si ouverture de bouche limitée"],
      risks: [risk("bleeding"), risk("ponv"), { title: "Blocage maxillo-mandibulaire au réveil", why: "Fixation des mâchoires après ostéotomie ou fracture.", prevention: "Extubation éveillée, antiémétiques, pinces coupantes au lit.", conduct: "Vomissements ou détresse : couper les élastiques ou fils, aspirer." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "bleeding"] }),
      notes: "Pas d'antibioprophylaxie pour les extractions simples ; céfazoline ou amoxicilline pour les ostéotomies et les fractures (voie endobuccale). Soins dentaires de la personne handicapée : prémédication, AG ambulatoire.",
    }),
  },

  // ============================================================ Ophtalmologie
  {
    id: pid(73),
    name: "Chirurgie du segment postérieur sous ALR (vitrectomie, décollement, glaucome)",
    surgery: "Vitrectomie",
    operation_category: "I",
    hospital: "",
    source: `${MANUAL}, chap. 12 et 39 (ophtalmologie).`,
    content: content({
      techniques: ["superficial_block", "sedation", "general"],
      drugs: [propofolInduction(), drug("Lidocaïne 2 % (bloc sous-ténonien ou péribulbaire)", "alr", "infiltration", { fixed: 100 }, "mg", "3–5 mL sous-ténonien, 6–10 mL péribulbaire ; ± ropivacaïne 0,75 %."), sedationPropofol(), sedationRemi(), paracetamol()],
      targets: ["Immobilité, patient coopérant", "Sédation légère au moment du bloc seulement", "Antithrombotiques poursuivis (bloc sous-ténonien)"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (capnographie sous les champs)", "O₂ sous les champs"],
      risks: [{ title: "Réflexe oculocardiaque", why: "Traction ou pression sur le globe.", prevention: "Bloc efficace.", conduct: "Arrêt de la stimulation, atropine 0,5 mg." }, { title: "Complications du bloc (hématome rétrobulbaire, injection intradurale)", why: "Aiguille dans l'orbite.", prevention: "Sous-ténonien plutôt qu'aiguille si anticoagulé ; échoguidage.", conduct: "Exophtalmie tendue : prévenir l'ophtalmologue (canthotomie) ; apnée, convulsions : ventilation, fiche intoxication aux AL." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Antibioprophylaxie intracamérulaire par l'ophtalmologue, pas IV. Gaz intra-oculaire (SF6, C3F8) : pas de N₂O pendant des semaines (bracelet). AG si patient non coopérant ou chirurgie longue.",
    }),
  },
  {
    id: pid(74),
    name: "Ophtalmologie sous AG (enfant, globe ouvert, orbite)",
    surgery: "Chirurgie du strabisme",
    operation_category: "I",
    hospital: "",
    source: `${MANUAL}, chap. 37 et 39.`,
    content: content({
      techniques: ["general"],
      drugs: [childPropofol(), childSufentanil(), childAtropine(), childDexa(), childOndansetron(), childParacetamol(), droperidol()],
      targets: ["Réflexe oculocardiaque : atropine prête", "NVPO (strabisme) : double prophylaxie", "Globe ouvert : pas de pression sur l'œil, pas de toux à l'induction"],
      material: CHILD_MONITORING,
      risks: [risk("ponv"), { title: "Réflexe oculocardiaque", why: "Traction des muscles oculomoteurs.", prevention: "Atropine prête, profondeur suffisante.", conduct: "Arrêt de la traction, atropine 20 µg/kg." }, risk("mh")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie IV (collyres). Adulte : doses adultes. Plaie du globe : estomac plein ; rocuronium 1,2 mg/kg plutôt que succinylcholine discutée (pression intraoculaire). Strabisme : association à des myopathies (hyperthermie maligne).",
    }),
  },

  // ============================================================ Neurochirurgie
  {
    id: pid(75),
    name: "Chirurgie du rachis cervical",
    surgery: "Arthrodèse cervicale antérieure",
    operation_category: "D",
    hospital: "",
    source: `${MANUAL}, chap. 29 (neurochirurgie).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketamineSparing(), tranexamic()],
      targets: ["Myélopathie : intubation rachis en rectitude (vidéolaryngoscope ou fibroscope vigile)", "PAM ≥ valeur de base (perfusion médullaire)", "Potentiels évoqués : TIVA, pas de curare après l'induction"],
      material: [...MONITORING, "Vidéolaryngoscope", "Fibroscope", "Cathéter artériel si myélopathie ou voie postérieure"],
      risks: [risk("difficult_airway"), { title: "Hématome cervical compressif (voie antérieure)", why: "Saignement dans la loge prévertébrale.", prevention: "Hémostase, réveil sans toux ni hypertension.", conduct: "Dyspnée, stridor : ouverture de la plaie au lit, intubation difficile." }, { title: "Lésion médullaire", why: "Hypotension, mobilisation, compression.", prevention: "PAM maintenue, rectitude, potentiels évoqués.", conduct: "Alerte des potentiels : PAM, Hb, prévenir le chirurgien." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "opioid_titration"], thrombo: "mechanical", watch: ["pain", "neuro"] }),
      notes: "Voie postérieure (laminectomie, laminoplastie) : décubitus ventral, têtière, yeux et appuis.",
    }),
  },
  {
    id: pid(76),
    name: "Neurochirurgie en urgence (hématome, hypertension intracrânienne)",
    surgery: "Hématome extradural ou sous-dural aigu",
    operation_category: "D",
    hospital: "",
    source: `${MANUAL}, chap. 29 ; Brain Trauma Foundation 2016.`,
    content: content({
      techniques: ["general"],
      drugs: [drug("Étomidate", "induction", "bolus_iv", { perKg: 0.3 }, "mg", "0,2–0,4 mg/kg (manuel, chap. 6)."), propofolInduction(1.5), drug("Rocuronium (séquence rapide)", "induction", "bolus_iv", { perKg: 1.2 }, "mg", "1,2 mg/kg."), sufentanil(0.3), drug("Mannitol 20 %", "haemodynamic", "perfusion", { perKg: 0.5 }, "g", "0,25–1 g/kg en 15 min si signes d'engagement (manuel, chap. 29)."), noradrenaline("PAS ≥ 100–110 mmHg, PAM ≥ 80 mmHg (perfusion cérébrale)."), cefazolin()],
      targets: ["Séquence rapide, rachis cervical maintenu si traumatisme", "PaCO₂ 35–40 mmHg (hyperventilation brève seulement si engagement)", "PAM ≥ 80 mmHg, SpO₂ ≥ 94 %, normoglycémie, normothermie"],
      material: [...MONITORING, "Cathéter artériel", "Collier cervical", "Vidéolaryngoscope"],
      risks: [risk("aspiration"), risk("induction_hypotension"), { title: "Engagement cérébral", why: "Hypertension intracrânienne.", prevention: "Tête surélevée 30°, cou libre, normocapnie, osmothérapie.", conduct: "Mydriase, bradycardie-hypertension : mannitol ou sérum salé hypertonique, hyperventilation brève, chirurgie immédiate." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "mechanical", watch: ["neuro", "glucose", "temperature"] }),
      notes: "Hématome sous-dural chronique : sujet âgé sous antithrombotiques ; trépanation sous AL et sédation ou AG ; réversion des anticoagulants.",
    }),
  },
  {
    id: pid(77),
    name: "Neuroradiologie interventionnelle (thrombectomie, embolisation)",
    surgery: "Thrombectomie cérébrale",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 29 ; ESAIC/ESO 2022 : sédation ou AG pour la thrombectomie.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [sedationPropofol(), sedationRemi(), propofolInduction(1.5), rocuronium(), noradrenaline("PAS 140–180 mmHg avant la recanalisation ; < 140–160 après, selon le neurologue."), drug("Nicardipine", "haemodynamic", "pse", { fixed: 1 }, "mg", "Hypertension après recanalisation ou rupture d'anévrisme.")],
      targets: ["Pas de retard à la procédure (« le temps c'est du cerveau »)", "PAS ≥ 140 mmHg jusqu'à la recanalisation, pas d'hypotension à l'induction", "Normocapnie, normoglycémie"],
      material: [...MONITORING, "Cathéter artériel (par le cathéter fémoral de l'angiographie)", "Protection contre les rayons X"],
      risks: [risk("induction_hypotension"), risk("aspiration"), { title: "Rupture vasculaire ou anévrismale", why: "Manipulation endovasculaire.", prevention: "Pression contrôlée.", conduct: "Protamine (héparine), baisse de la PA, dérivation ventriculaire, AG si sédation." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol"], thrombo: "mechanical", watch: ["neuro"] }),
      notes: "Pas d'antibioprophylaxie. Embolisation d'anévrisme : AG, curarisation, PA contrôlée, héparine selon le neuroradiologue.",
    }),
  },
  {
    id: pid(78),
    name: "Craniotomie éveillée",
    surgery: "Craniotomie éveillée",
    operation_category: "D",
    hospital: "",
    source: `${MANUAL}, chap. 29 ; ${PROSPECT_REF("craniotomie", 2023, "37417808")}.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [propofolInduction(1.5), drug("Ropivacaïne 0,5 % (bloc du scalp)", "alr", "infiltration", { fixed: 150 }, "mg", "Nerfs supra-orbitaire, supratrochléaire, auriculotemporal, grand et petit occipitaux, bilatéraux selon la têtière."), drug("Dexmédétomidine", "maintenance", "pse", { perKg: 1 }, "µg", "Charge 1 µg/kg en 10 min puis 0,2–0,7 µg/kg/h ; arrêtée ou réduite pour le temps éveillé."), sedationRemi(), sedationPropofol(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol()],
      targets: ["Patient confortable, calme, capable de parler et bouger pendant la cartographie", "Voies aériennes accessibles (masque laryngé prêt)", "Crise convulsive : sérum froid sur le cortex par le chirurgien, propofol 20–30 mg"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (capnographie nasale)", "Cathéter artériel", "Masque laryngé", "Accès au visage sous les champs"],
      risks: [risk("delayed_awakening"), { title: "Crise convulsive peropératoire", why: "Stimulation corticale.", prevention: "Antiépileptique poursuivi, sérum glacé prêt.", conduct: "Sérum froid sur le cortex, propofol, benzodiazépine ; AG si généralisation." }, { title: "Obstruction des voies aériennes", why: "Sédation, position.", prevention: "Sédation titrée, capnographie.", conduct: "Subluxation, canule, masque laryngé." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol"], thrombo: "mechanical", watch: ["neuro", "pain"] }),
      notes: "Sélection et préparation du patient (anxiété, SAOS, obésité) essentielles ; technique endormi-éveillé-endormi selon l'équipe.",
    }),
  },
  {
    id: pid(79),
    name: "Dérivation du LCS et neurochirurgie fonctionnelle",
    surgery: "Dérivation ventriculo-péritonéale",
    operation_category: "D",
    hospital: "",
    source: `${MANUAL}, chap. 29 et 37.`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin("Céfazoline : matériel implanté (valve, électrodes, pompe)."), dexamethasone(8), ondansetron(), paracetamol()],
      targets: ["Hypertension intracrânienne (valve dysfonctionnelle) : séquence rapide, normocapnie", "Stimulation cérébrale profonde : enregistrement éveillé sans benzodiazépine, cadre stéréotaxique (clé de démontage)"],
      material: [...MONITORING, "Clé du cadre stéréotaxique si présent"],
      risks: [risk("aspiration"), { title: "Hypertension intracrânienne", why: "Obstruction de la valve.", prevention: "Tête surélevée, normocapnie.", conduct: "Mannitol, drainage rapide par le chirurgien." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol"], thrombo: "mechanical", watch: ["neuro", "pain"] }),
      notes: "Enfant : doses au poids. Neurostimulateur médullaire et pompe intrathécale : décubitus ventral, test éveillé selon l'équipe.",
    }),
  },

  // ============================================================ Thorax et cœur
  {
    id: pid(80),
    name: "Médiastinoscopie et chirurgie du médiastin (thymectomie)",
    surgery: "Médiastinoscopie",
    operation_category: "G",
    hospital: "",
    source: `${MANUAL}, chap. 26 (thorax) et 34 (myasthénie).`,
    content: content({
      techniques: ["general"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), drug("Sugammadex", "other", "bolus_iv", { perKg: 2 }, "mg", "Myasthénie : curares réduits (rocuronium 0,3 mg/kg) et monitorage ; sugammadex en fin d'intervention."), cefazolin(), dexamethasone(8), paracetamol()],
      targets: ["Masse médiastinale antérieure : ventilation spontanée jusqu'à la sécurisation, position semi-assise ou latérale possible", "Médiastinoscopie : pression artérielle au bras gauche, SpO₂ à droite (compression du tronc artériel brachiocéphalique)"],
      material: [...MONITORING, "Cathéter artériel", "Sonde armée", "Deux voies veineuses (membre inférieur si syndrome cave)", "Bronchoscope rigide disponible"],
      risks: [{ title: "Collapsus cardiorespiratoire à l'induction (masse médiastinale)", why: "Compression trachéale, cardiaque ou cave quand le tonus disparaît.", prevention: "Scanner, symptômes posturaux ; induction en ventilation spontanée, CEC ou ECMO prévue si très haut risque.", conduct: "Changer de position (latérale, ventrale), bronchoscope rigide, ECMO." }, risk("bleeding")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "opioid_titration"], thrombo: "lmwh", watch: ["pain"] }),
      notes: "Myasthénie : pyridostigmine poursuivie, sensibilité aux curares non dépolarisants, résistance à la succinylcholine ; ventilation postopératoire si forme sévère.",
    }),
  },
  {
    id: pid(81),
    name: "Cardiologie structurelle (TAVI, MitraClip, fermeture d'auricule)",
    surgery: "TAVI",
    operation_category: "F",
    hospital: "",
    source: `${MANUAL}, chap. 27 ; ESC/EACTS 2021 valvulopathies.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [propofolInduction(1.5), sedationPropofol(), sedationRemi(), drug("Lidocaïne 1 % (infiltration fémorale)", "alr", "infiltration", { fixed: 200 }, "mg", "Voie fémorale percutanée."), cefazolin(), noradrenaline("Rétrécissement aortique : éviter hypotension et tachycardie ; noradrénaline titrée."), drug("Héparine non fractionnée", "haemodynamic", "bolus_iv", { fixed: 5000 }, "UI", "Selon le cardiologue (70–100 UI/kg), ACT ≥ 250 s ; protamine en fin de procédure.")],
      targets: ["Rétrécissement aortique : rythme sinusal, fréquence basse, précharge et résistances maintenues", "Stimulation rapide (valvuloplastie, déploiement) : récupération de la pression attendue", "MitraClip et auricule : AG avec ETO"],
      material: [...MONITORING, "Cathéter artériel", "Électrodes de défibrillation", "Stimulateur temporaire", "ETO (MitraClip, auricule)"],
      risks: [risk("induction_hypotension"), { title: "Complications vasculaires ou tamponnade", why: "Gros introducteurs, perforation ventriculaire.", prevention: "Salle hybride, chirurgien cardiaque disponible.", conduct: "Hypotension brutale : échographie (tamponnade, hémorragie rétropéritonéale), drainage, transfusion, conversion." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol"], thrombo: "mechanical", watch: ["neuro", "urine", "hb"] }),
      notes: "Fermeture percutanée de FOP ou CIA : sédation légère ou AG avec ETO selon l'équipe.",
    }),
  },
  {
    id: pid(82),
    name: "Électrophysiologie et dispositifs (ablation, pacemaker, cardioversion)",
    surgery: "Ablation de fibrillation auriculaire",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 22 (sédation) et 27.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [sedationPropofol(), sedationRemi(), drug("Propofol (cardioversion)", "induction", "bolus_iv", { perKg: 1 }, "mg", "0,5–1 mg/kg titré pour une cardioversion de quelques secondes (manuel, chap. 6)."), drug("Céfazoline (pacemaker, défibrillateur)", "antibio", "bolus_iv", { fixed: 2 }, "g", "Dans l'heure avant l'incision pour un dispositif implanté.")],
      targets: ["Ventilation spontanée sous sédation ; AG pour l'ablation de FA longue (immobilité, ventilation régulière)", "Cardioversion : patient à jeun, anticoagulation vérifiée ou ETO"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂ (capnographie)", "Électrodes de défibrillation", "Masque laryngé prêt"],
      risks: [{ title: "Tamponnade (ablation)", why: "Perforation lors de la ponction transseptale ou de l'ablation.", prevention: "Pression artérielle surveillée.", conduct: "Hypotension brutale : échographie, drainage péricardique, protamine." }, { title: "Dépression respiratoire sous sédation", why: "Propofol et opioïde.", prevention: "Titration, capnographie.", conduct: "Stimuler, O₂, masque ; masque laryngé." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie pour l'ablation et la cardioversion ; céfazoline pour l'implantation de dispositifs. Extraction de sondes : AG, cathéter artériel, sang et chirurgien cardiaque disponibles.",
    }),
  },
  {
    id: pid(83),
    name: "Chirurgie thoracique courte (talcage, pneumothorax, sympathectomie)",
    surgery: "Chirurgie du pneumothorax",
    operation_category: "G",
    hospital: "",
    source: `${PROSPECT_REF("VATS", 2022, "34739134")} ; ${MANUAL}, chap. 26.`,
    content: content({
      techniques: ["general", "deep_block"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ropivacaineBlock(150, "paravertébral ou ESP")],
      targets: ["Ventilation unipulmonaire (sonde double lumière ou bloqueur)", "Pneumothorax : pas de N₂O, pressions basses avant le drainage"],
      material: [...MONITORING, "Sonde double lumière", "Fibroscope", "Échographe"],
      risks: [{ title: "Hypoxémie en ventilation unipulmonaire", why: "Shunt.", prevention: "Sonde vérifiée au fibroscope, PEP.", conduct: "FiO₂ 100 %, revérifier la sonde, CPAP au poumon exclu." }, { title: "Œdème de réexpansion", why: "Réexpansion rapide d'un poumon longtemps collabé.", prevention: "Réexpansion progressive.", conduct: "Hypoxémie après réexpansion : PEP, diurétique selon l'état." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh", watch: ["pain"] }),
      notes: "Talcage : douleur et fièvre fréquentes. Drain thoracique seul : AL et sédation.",
    }),
  },

  // ============================================================ Membres
  {
    id: pid(84),
    name: "Chirurgie du membre supérieur sous bloc (coude, avant-bras, poignet, main)",
    surgery: "Chirurgie du poignet et de la main (tendons, nerfs)",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${MANUAL}, chap. 12.`,
    content: content({
      techniques: ["superficial_block", "sedation", "general"],
      drugs: [propofolInduction(), ropivacaineBlock(150, "bloc axillaire ou supraclaviculaire"), drug("Dexaméthasone (périnerveuse ou IV)", "alr", "bolus_iv", { fixed: 4 }, "mg", "Prolonge le bloc d'environ 8 h (manuel, chap. 12)."), sedationPropofol(), paracetamol(), ketorolac(), cefazolin("Ostéosynthèse ou prothèse : céfazoline ; pas pour la chirurgie des parties molles de moins de 2 h.")],
      targets: ["Bloc complet avant le garrot", "Garrot ≤ 2 h, pression notée", "Sortie avec le bras en écharpe, analgésie orale prescrite avant la levée du bloc"],
      material: ["ECG", "PNI (autre bras)", "SpO₂", "Échographe", "Garrot"],
      risks: [risk("last"), { title: "Levée du bloc la nuit", why: "Douleur de rebond 12–24 h après.", prevention: "Analgésiques pris avant la levée, dexaméthasone.", conduct: "Paracétamol, AINS, opioïde oral de secours prescrit." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid", "perineural"], thrombo: "none", watch: ["pain", "block"] }),
      tourniquetAlertMin: 120,
      notes: "Canal carpien, Dupuytren, doigt à ressaut : WALANT (AL adrénalinée sans garrot) par le chirurgien possible. Réimplantation : cathéter axillaire continu (sympatholyse), normothermie.",
    }),
  },
  {
    id: pid(85),
    name: "Chirurgie de l'épaule et de l'humérus (prothèse, fracture)",
    surgery: "Prothèse d'épaule",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${PROSPECT_REF("coiffe des rotateurs", 2019, "31392721")} (extrapolé) ; ${MANUAL}, chap. 12 et 19.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [ropivacaineBlock(75, "interscalénique ou tronc supérieur"), propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), tranexamic()],
      targets: ["Position semi-assise : PAM mesurée au niveau du cerveau (correction de hauteur), pas d'hypotension", "Bloc interscalénique : paralysie phrénique (prudence si insuffisance respiratoire)"],
      material: [...MONITORING, "Échographe", "Têtière de beach chair"],
      risks: [{ title: "Hypoperfusion cérébrale en position assise", why: "Pression mesurée au bras plus haute que celle du cerveau.", prevention: "PA au niveau du méat auditif, PAM ≥ 70 mmHg, pas d'hypotension contrôlée profonde.", conduct: "Hypotension : vasopresseur, baisser le dossier." }, risk("last")],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid", "perineural"], perineural: DEFAULT_PERINEURAL, thrombo: "lmwh", watch: ["pain", "block"] }),
      notes: "Fracture de la clavicule : bloc interscalénique bas ou cervical superficiel. Butée : idem prothèse. Épaule gelée anesthésique : sortie avec écharpe.",
    }),
  },
  {
    id: pid(86),
    name: "Chirurgie du genou et de la jambe (ligamentoplastie, rotule, tibia)",
    surgery: "Ligamentoplastie du genou",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${PROSPECT_REF("prothèse de genou", 2022, "35852550")} (extrapolé) ; ${MANUAL}, chap. 12.`,
    content: content({
      techniques: ["general", "neuraxial", "superficial_block"],
      drugs: [propofolInduction(), sufentanil(), drug("Chloroprocaïne 1 % (rachianesthésie courte)", "alr", "intrathecal", { fixed: 50 }, "mg", "40–50 mg : ambulatoire ; ou bupivacaïne 7,5–10 mg."), ropivacaineBlock(100, "canal des adducteurs + IPACK"), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac()],
      targets: ["Blocs moteurs épargnés (canal des adducteurs) : mobilisation précoce", "Garrot : durée notée"],
      material: [...MONITORING, "Échographe", "Garrot"],
      risks: [risk("spinal_hypotension"), risk("last"), { title: "Syndrome des loges (fracture du tibia)", why: "Œdème post-traumatique ou de reperfusion.", prevention: "Bloc léger ou surveillance renforcée selon l'équipe ; pas de bloc profond masquant.", conduct: "Douleur croissante malgré l'analgésie, tension de la jambe : pression des loges, fasciotomie." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid", "perineural"], thrombo: "lmwh", watch: ["pain", "block"] }),
      tourniquetAlertMin: 120,
      notes: "Ostéotomie tibiale et plateau tibial : hospitalisation, acide tranexamique. Prothèse unicompartimentale : protocole prothèse de genou.",
    }),
  },
  {
    id: pid(87),
    name: "Chirurgie de la cheville et du pied",
    surgery: "Fracture de la cheville (bimalléolaire)",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${PROSPECT_REF("hallux valgus", 2025, "41122054")} (extrapolé) ; ${MANUAL}, chap. 12.`,
    content: content({
      techniques: ["superficial_block", "neuraxial", "general"],
      drugs: [propofolInduction(), ropivacaineBlock(150, "sciatique poplité + saphène"), drug("Dexaméthasone (IV)", "analgesia", "bolus_iv", { fixed: 8 }, "mg", "Prolonge le bloc."), drug("Bupivacaïne hyperbare 0,5 %", "alr", "intrathecal", { fixed: 10 }, "mg", "Rachianesthésie, si pas de bloc."), sedationPropofol(), cefazolin(), paracetamol(), ketorolac()],
      targets: ["Garrot de cuisse : bloc sciatique ou rachianesthésie", "Sortie avec analgésie orale avant la levée du bloc"],
      material: ["ECG", "PNI", "SpO₂", "Échographe", "Garrot"],
      risks: [risk("last"), { title: "Douleur de rebond à la levée du bloc", why: "Levée du bloc sciatique 12–24 h après.", prevention: "Analgésie orale programmée, cathéter poplité pour les gestes lourds.", conduct: "Paracétamol, AINS, opioïde oral de secours." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid", "perineural"], thrombo: "lmwh", watch: ["pain", "block"] }),
      tourniquetAlertMin: 120,
      notes: "Prothèse de cheville et arthrodèse : cathéter poplité, hospitalisation. Tendon d'Achille : décubitus ventral.",
    }),
  },
  {
    id: pid(88),
    name: "Reprise de prothèse, fracture périprothétique, chirurgie osseuse tumorale",
    surgery: "Reprise de prothèse de hanche ou de genou",
    operation_category: "K",
    hospital: "",
    source: `${DUBOIS} ; ${MANUAL}, chap. 12, 13 et 40.`,
    content: content({
      techniques: ["neuraxial", "general", "superficial_block"],
      drugs: [drug("Bupivacaïne hyperbare 0,5 %", "alr", "intrathecal", { fixed: 12.5 }, "mg", "Rachianesthésie si durée compatible, ou combinée rachi-péridurale."), propofolInduction(), sufentanil(), rocuronium(), cefazolin("Infection : prélèvements avant les antibiotiques si demandé par le chirurgien."), tranexamic(), ropivacaineBlock(150, "fascia iliaca ou canal des adducteurs"), paracetamol(), noradrenaline()],
      targets: ["Épargne sanguine : acide tranexamique, récupérateur de sang, seuil transfusionnel restrictif", "Ciment : surveillance à l'implantation (syndrome d'implantation du ciment)"],
      material: [...MONITORING, "Cathéter artériel selon le terrain", "Deux voies veineuses", "Récupérateur de sang", "Échographe"],
      risks: [risk("bleeding"), risk("hypothermia"), { title: "Syndrome d'implantation du ciment", why: "Embols de moelle et de ciment lors de la mise en place.", prevention: "Remplissage correct, FiO₂ augmentée, lavage du fût.", conduct: "Hypoxémie, hypotension, arrêt : O₂ 100 %, vasopresseur, réanimation." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "perineural", "opioid_titration"], thrombo: "lmwh", thromboDays: 35, watch: ["pain", "hb", "delirium"] }),
      notes: "Métastases osseuses : embolisation préalable si très vascularisée (rein, thyroïde) ; sarcome : lambeau et saignement. Infection de prothèse : sepsis possible.",
    }),
  },
  {
    id: pid(89),
    name: "Urgences orthopédiques (lavage articulaire, fasciotomie, fixateur, luxation)",
    surgery: "Réduction de luxation sous anesthésie",
    operation_category: "K",
    hospital: "",
    source: `${MANUAL}, chap. 39 (estomac plein) et 12.`,
    content: content({
      techniques: ["general", "sedation", "superficial_block"],
      drugs: [propofolInduction(1.5), drug("Kétamine", "induction", "bolus_iv", { perKg: 0.5 }, "mg", "0,5–1 mg/kg : analgésie pour une réduction brève."), drug("Rocuronium (séquence rapide)", "induction", "bolus_iv", { perKg: 1.2 }, "mg", "Estomac plein (traumatisme récent)."), ropivacaineBlock(100, "interscalénique, PENG ou fascia iliaca selon la luxation"), cefazolin("Fracture ouverte : céfazoline sans attendre ; lavage septique : après les prélèvements."), paracetamol()],
      targets: ["Traumatisme récent : estomac plein, séquence rapide si AG", "Syndrome des loges : pas de bloc prolongé masquant la douleur"],
      material: [...MONITORING, "Échographe"],
      risks: [risk("aspiration"), { title: "Syndrome des loges", why: "Fracture, reperfusion, plâtre serré.", prevention: "Surveillance clinique, analgésie sans bloc profond prolongé.", conduct: "Douleur disproportionnée : avis chirurgical, mesure des pressions, fasciotomie." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "opioid_titration"], thrombo: "lmwh", watch: ["pain"] }),
      notes: "Luxation d'épaule ou de hanche : sédation profonde courte (propofol, kétamine) ou bloc (interscalénique, PENG).",
    }),
  },

  // ============================================================ Plastique et reconstructrice
  {
    id: pid(90),
    name: "Chirurgie mammaire plastique (augmentation, réduction, prothèse)",
    surgery: "Augmentation mammaire",
    operation_category: "L",
    hospital: "",
    source: `${ERAS_BREAST} ; ${PROSPECT_REF("chirurgie du sein", 2026, "42581686")} (extrapolé).`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [propofolInduction(), sufentanil(), cefazolin(), dexamethasone(8), ondansetron(), droperidol(), paracetamol(), ketorolac(), ropivacaineBlock(150, "PECS ou serratus bilatéral")],
      targets: ["Double ou triple prophylaxie des NVPO", "Position semi-assise peropératoire : PA et appuis des bras"],
      material: [...MONITORING, "Échographe", "Masque laryngé"],
      risks: [risk("ponv"), risk("last")],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain", "bleeding"] }),
      notes: "Reconstruction par prothèse et gynécomastie : même protocole. Lipofilling : prélèvement sous tumescence.",
    }),
  },
  {
    id: pid(91),
    name: "Lambeau libre et microchirurgie (reconstruction mammaire, membres)",
    surgery: "Reconstruction mammaire par lambeau libre",
    operation_category: "L",
    hospital: "",
    source: `${ERAS_BREAST} ; ${MANUAL}, chap. 21.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ropivacaineBlock(150, "TAP (site donneur abdominal) et PECS"), ketamineSparing()],
      targets: ["Normothermie, normovolémie, Hb 8–10 g/dL", "PAM stable sans vasopresseur à forte dose ; débit cardiaque conservé", "Réveil calme (pas de toux, pas de frissons)"],
      material: [...MONITORING, "Cathéter artériel", "Sonde urinaire", "Réchauffement actif", "Monitorage du débit cardiaque selon l'équipe"],
      risks: [risk("hypothermia"), risk("ponv"), { title: "Thrombose du lambeau", why: "Hypoperfusion, vasoconstriction, compression du pédicule.", prevention: "Normothermie, volémie, analgésie, pas de compression.", conduct: "Lambeau pâle ou violacé : chirurgien immédiatement." }],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "nsaid", "opioid_titration"], thrombo: "lmwh", watch: ["pain", "temperature", "hb"] }),
      notes: "ERAS reconstruction mammaire : épargne des opioïdes, jeûne court, alimentation et mobilisation précoces.",
    }),
  },
  {
    id: pid(92),
    name: "Chirurgie des brûlés (excision-greffe)",
    surgery: "Excision-greffe de brûlure",
    operation_category: "L",
    hospital: "",
    source: `${MANUAL}, chap. 42 (brûlés).`,
    content: content({
      techniques: ["general"],
      drugs: [drug("Kétamine", "induction", "bolus_iv", { perKg: 1 }, "mg", "1–2 mg/kg : stabilité, analgésie (manuel, chap. 6)."), propofolInduction(1.5), rocuronium(1), sufentanil(0.3), tranexamic(), cefazolin("Selon la colonisation et le protocole du centre des brûlés."), noradrenaline()],
      targets: ["Pas de succinylcholine après 48 h (hyperkaliémie)", "Besoins en curares non dépolarisants augmentés", "Normothermie : salle chauffée, liquides réchauffés", "Saignement : ~ 1 mL/cm² excisé, transfusion anticipée"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "Accélérateur-réchauffeur de transfusion", "Salle à 28–32 °C"],
      risks: [risk("hyperkalaemia"), risk("hypothermia"), risk("bleeding"), risk("difficult_airway")],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration", "ketamine"], thrombo: "lmwh", watch: ["pain", "temperature", "hb", "potassium"] }),
      notes: "Brûlure faciale ou par inhalation : œdème des voies aériennes, intubation précoce. Doses d'opioïdes élevées (tolérance).",
    }),
  },
  {
    id: pid(93),
    name: "Chirurgie plastique de la silhouette (abdominoplastie, liposuccion)",
    surgery: "Abdominoplastie",
    operation_category: "L",
    hospital: "",
    source: `${MANUAL}, chap. 11 et 23.`,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [propofolInduction(), sufentanil(), rocuronium(), cefazolin(), dexamethasone(8), ondansetron(), paracetamol(), ketorolac(), ropivacaineBlock(150, "TAP bilatéral"), tranexamic()],
      targets: ["Liposuccion : lidocaïne de tumescence ≤ 35 mg/kg (diluée) ; volume aspiré limité", "Thromboprophylaxie (Caprini souvent élevé)"],
      material: [...MONITORING, "Réchauffement actif", "Bas de compression"],
      risks: [risk("last"), risk("hypothermia"), { title: "Thromboembolie", why: "Chirurgie longue, contraceptifs, obésité antérieure.", prevention: "Caprini, compression, HBPM.", conduct: "Dyspnée, douleur de mollet : angioscanner, écho-Doppler." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol", "nsaid"], thrombo: "lmwh_mechanical", watch: ["pain"] }),
      notes: "Chirurgie après amaigrissement massif : carences (fer, vitamines) et antécédent bariatrique.",
    }),
  },

  // ============================================================ Enfant
  {
    id: pid(94),
    name: "Chirurgie ambulatoire de l'enfant (hernie, circoncision, orchidopexie)",
    surgery: "Cure de hernie inguinale de l'enfant",
    operation_category: "A",
    hospital: "",
    source: CHILD,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [childPremed(), childPropofol(), caudal(), drug("Clonidine (caudale)", "alr", "peridural", { perKg: 1 }, "µg", "1 µg/kg avec l'anesthésique local, après 6 mois (manuel, chap. 37)."), childParacetamol(), childIbuprofen(), childDexa()],
      targets: ["Masque laryngé, ventilation spontanée", "Caudale après l'induction (ou bloc ilio-inguinal, pénien)", "Ancien prématuré < 60 SA post-conceptionnel : surveillance des apnées"],
      material: CHILD_MONITORING,
      risks: [risk("laryngospasm"), { title: "Apnées postopératoires (ancien prématuré)", why: "Immaturité du contrôle respiratoire, anémie.", prevention: "Rachianesthésie seule possible, caféine selon l'équipe.", conduct: "Surveillance monitorée 12–24 h, pas d'ambulatoire." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie. Hypospade : caudale ou bloc pénien, sonde, durée plus longue. Orchidopexie par cœlioscopie : curarisation, pneumopéritoine.",
    }),
  },
  {
    id: pid(95),
    name: "Estomac plein du nourrisson (sténose du pylore, invagination)",
    surgery: "Pylorotomie",
    operation_category: "A",
    hospital: "",
    source: CHILD,
    content: content({
      techniques: ["general"],
      drugs: [childAtropine(), childPropofol(), drug("Suxaméthonium (succinylcholine)", "induction", "bolus_iv", { perKg: 2 }, "mg", "1,5–2 mg/kg chez l'enfant (manuel, chap. 37) ; ou rocuronium 1 mg/kg."), childParacetamol(), drug("Ropivacaïne (infiltration)", "alr", "infiltration", { perKg: 1 }, "mg", "Par le chirurgien, maximum 2,5 mg/kg chez le nourrisson.")],
      targets: ["Sténose du pylore : urgence médicale — alcalose et hypochlorémie corrigées avant (Cl⁻ ≥ 100, HCO₃⁻ ≤ 28 mmol/L)", "Vidange de l'estomac par sonde, en décubitus dorsal, latéral et ventral", "Séquence rapide adaptée, préoxygénation douce"],
      material: CHILD_MONITORING,
      risks: [risk("aspiration"), { title: "Apnées postopératoires", why: "Alcalose persistante, jeune âge, opioïdes.", prevention: "Pas d'opioïde, correction métabolique préalable.", conduct: "Surveillance monitorée." }],
      postopPlan: postop({ destination: "ward", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain", "glucose"] }),
      notes: "Pas d'antibioprophylaxie. Invagination : déshydratation, remplissage 20 mL/kg avant l'induction ; réduction radiologique souvent sous sédation.",
    }),
  },
  {
    id: pid(96),
    name: "Chirurgie néonatale majeure",
    surgery: "Atrésie de l'œsophage",
    operation_category: "G",
    hospital: "",
    source: `${ERAS_NEONATE} ; ${CHILD}.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [childAtropine(), drug("Ropivacaïne 0,2 % (péridurale caudale ou lombaire)", "alr", "peridural", { perKg: 0.5 }, "mg", "Nouveau-né : 0,5 mL/kg de 0,2 % au plus en dose initiale, perfusion ≤ 0,2 mg/kg/h (manuel, chap. 37)."), drug("Fentanyl", "induction", "bolus_iv", { perKg: 1 }, "µg", "1–2 µg/kg titré (manuel, chap. 37)."), drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6 }, "mg", "0,6 mg/kg."), childCefazolin(), drug("Paracétamol", "analgesia", "perfusion", { perKg: 10 }, "mg", "Nouveau-né : 7,5–10 mg/kg selon l'âge (manuel, chap. 37)."), drug("Glucose 10 %", "haemodynamic", "perfusion", { fixed: 10 }, "mL", "Entretien glucosé (3–5 mL/kg/h selon le poids) : glycémie contrôlée (ERAS nouveau-né 2024).")],
      targets: ["Normothermie (salle chauffée, air pulsé, liquides réchauffés)", "Glycémie 2,5–8 mmol/L", "SpO₂ préductale 90–95 % (prématuré), pas d'hyperoxie", "Seuils transfusionnels ERAS 2024"],
      material: ["ECG", "PNI", "SpO₂ pré- et postductale", "EtCO₂", "Température", "Réchauffement", "Cathéter artériel (ombilical ou radial)", "Matériel au poids"],
      risks: [risk("hypothermia"), { title: "Hypoglycémie", why: "Réserves faibles, jeûne.", prevention: "Glucose en continu.", conduct: "Glycémie < 2,5 mmol/L : glucose 10 % 2 mL/kg." }, { title: "Ventilation difficile (fistule œso-trachéale, hernie diaphragmatique)", why: "Fuite par la fistule, hypoplasie pulmonaire.", prevention: "Ventilation douce, sonde placée sous la fistule, pas de ventilation au masque vigoureuse.", conduct: "Distension gastrique : gastrostomie de décharge ; hypoxémie : HTAP, NO inhalé selon l'équipe." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "none", watch: ["pain", "glucose", "temperature"] }),
      notes: "Souvent en réanimation néonatale (ECUN, grand prématuré). Myéloméningocèle : latex évité d'emblée. Péridurale caudale ou lombaire possible pour la chirurgie abdominale.",
    }),
  },
  {
    id: pid(97),
    name: "Chirurgie viscérale et urologique de l'enfant (appendicite, rein, Hirschsprung)",
    surgery: "Néphrectomie de l'enfant (tumeur de Wilms)",
    operation_category: "J2",
    hospital: "",
    source: CHILD,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [childPremed(), childPropofol(), childSufentanil(), drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6 }, "mg", "0,6 mg/kg."), childCefazolin(), drug("Ropivacaïne 0,2 % (péridurale de l'enfant)", "alr", "peridural", { perKg: 0.5 }, "mg", "0,5 mL/kg de 0,2 % à la dose test, puis 0,2 mg/kg/h (manuel, chap. 37)."), childParacetamol(), childDexa()],
      targets: ["Normothermie, glycémie", "Saignement rapporté au volume sanguin (80 mL/kg)", "Péridurale posée sous AG chez l'enfant"],
      material: [...CHILD_MONITORING, "Cathéter artériel si chirurgie majeure", "Deux voies veineuses"],
      risks: [risk("bleeding"), risk("hypothermia"), risk("laryngospasm")],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "none", watch: ["pain", "urine"] }),
      notes: "Wilms : HTA, thrombus cave possible. Hirschsprung, pyéloplastie, reflux : même principe (péridurale ou caudale). Appendicite : estomac plein, séquence rapide, métronidazole avec la céfazoline, pas de péridurale ; infiltration des orifices.",
    }),
  },
  {
    id: pid(98),
    name: "Orthopédie et chirurgie plastique de l'enfant",
    surgery: "Fracture supracondylienne de l'humérus (enfant)",
    operation_category: "K",
    hospital: "",
    source: CHILD,
    content: content({
      techniques: ["general", "superficial_block"],
      drugs: [childPropofol(), drug("Ropivacaïne 0,2 % (bloc périphérique)", "alr", "perinerveux", { perKg: 0.5, max: 150 }, "mg", "0,5 mL/kg selon le bloc (axillaire, fémoral, poplité) ; maximum 2,5 mg/kg au total (manuel, chap. 37)."), childSufentanil(), drug("Rocuronium (séquence rapide)", "induction", "bolus_iv", { perKg: 1 }, "mg", "Estomac plein après un traumatisme récent."), childCefazolin(), childParacetamol(), childIbuprofen(), childDexa()],
      targets: ["Traumatisme : estomac plein (vidange ralentie)", "Syndrome des loges : pas de bloc profond masquant sans accord du chirurgien", "Épiphysiolyse : adolescent souvent obèse"],
      material: CHILD_MONITORING,
      risks: [risk("aspiration"), { title: "Syndrome des loges", why: "Fracture, œdème, plâtre.", prevention: "Surveillance, analgésie adaptée.", conduct: "Douleur croissante : fendre le plâtre, avis chirurgical." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Ostéotomies pelviennes : péridurale caudale ou lombaire, transfusion possible. Paralysie cérébrale : reflux, épilepsie, hypothermie, spasmes (diazépam).",
    }),
  },
  {
    id: pid(99),
    name: "Scoliose de l'adolescent (arthrodèse)",
    surgery: "Arthrodèse pour scoliose de l'adolescent",
    operation_category: "K",
    hospital: "",
    source: `${ERAS_SPINE} (extrapolé) ; ${MANUAL}, chap. 29 et 37.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(), remifentanil(), rocuronium(), childCefazolin(), drug("Acide tranexamique", "haemodynamic", "perfusion", { perKg: 15 }, "mg", "10–15 mg/kg puis perfusion selon l'équipe (manuel, chap. 40)."), drug("Morphine intrathécale", "analgesia", "intrathecal", { fixed: 0.3 }, "mg", "Par le chirurgien ou avant l'incision, 5–10 µg/kg selon l'équipe ; surveillance respiratoire."), ketamineSparing(), childParacetamol(), noradrenaline("PAM ≥ 65–70 mmHg pendant la correction (perfusion médullaire).")],
      targets: ["Potentiels évoqués : TIVA, pas de curare après l'intubation", "PAM maintenue pendant la correction, Hb ≥ 8 g/dL", "Épargne sanguine : acide tranexamique, récupérateur"],
      material: [...MONITORING, "Cathéter artériel", "Deux voies veineuses", "Récupérateur de sang", "Coussins de décubitus ventral", "Protection oculaire"],
      risks: [risk("bleeding"), risk("hypothermia"), { title: "Alerte des potentiels évoqués", why: "Ischémie ou traction médullaire.", prevention: "PAM, Hb, profondeur d'anesthésie stables.", conduct: "Augmenter la PAM, vérifier Hb et température, relâcher la correction, test du réveil." }, { title: "Décubitus ventral : yeux et appuis", why: "Cécité postopératoire, compressions.", prevention: "Têtière adaptée, yeux libres vérifiés, abdomen libre.", conduct: "Vérifier toutes les 30 min." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "nsaid", "ketamine", "intrathecal_morphine", "pca_morphine"], thrombo: "mechanical", watch: ["pain", "neuro", "hb", "sedation"] }),
      notes: "Scoliose neuromusculaire (Duchenne) : pas de succinylcholine ni d'halogénés, fonction cardiaque et respiratoire, saignement plus important.",
    }),
  },
  {
    id: pid(100),
    name: "Anesthésie hors bloc de l'enfant (imagerie, radiothérapie, ponction, endoscopie)",
    surgery: "Examen sous anesthésie (enfant)",
    operation_category: "X",
    hospital: "",
    source: `${CHILD} ; ${MANUAL}, chap. 22.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [childPremed(), childPropofol(), drug("Propofol (sédation)", "maintenance", "pse", { perKg: 1 }, "mg", "Bolus 1 mg/kg puis 6–10 mg/kg/h titré (manuel, chap. 37)."), drug("Dexmédétomidine intranasale", "premed", "intranasal", { perKg: 2 }, "µg", "1–2 µg/kg, 30–45 min avant (imagerie sans douleur) (manuel, chap. 37)."), drug("Kétamine", "analgesia", "bolus_iv", { perKg: 0.5 }, "mg", "0,5–1 mg/kg pour un geste douloureux (ponction, myélogramme).")],
      targets: ["Ventilation spontanée, capnographie", "IRM : matériel compatible, monitorage à distance, accès à l'enfant préparé", "Sortie selon les critères pédiatriques"],
      material: ["ECG compatible IRM", "PNI", "SpO₂", "EtCO₂", "Masque laryngé prêt", "Aspiration"],
      risks: [risk("laryngospasm"), { title: "Dépression respiratoire loin du bloc", why: "Sédation profonde, accès limité (IRM).", prevention: "Capnographie, équipe et matériel complets sur place.", conduct: "Stimuler, subluxation, masque, masque laryngé." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie. Radiothérapie : séances quotidiennes, même protocole chaque jour, voie centrale. Pose de voie centrale : AG courte, échoguidage.",
    }),
  },
  {
    id: pid(101),
    name: "Neurochirurgie de l'enfant (craniosténose, valve, moelle attachée)",
    surgery: "Craniosténose",
    operation_category: "D",
    hospital: "",
    source: CHILD,
    content: content({
      techniques: ["general"],
      drugs: [childPremed(), childPropofol(), childSufentanil(), drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6 }, "mg", "0,6 mg/kg."), childCefazolin(), drug("Acide tranexamique", "haemodynamic", "perfusion", { perKg: 15 }, "mg", "10–15 mg/kg puis perfusion (manuel, chap. 40)."), childParacetamol()],
      targets: ["Saignement majeur rapporté au volume sanguin (80 mL/kg) : sang en salle, transfusion précoce", "Embolie gazeuse : EtCO₂, position", "Normothermie"],
      material: [...CHILD_MONITORING, "Cathéter artériel", "Deux voies veineuses de bon calibre", "Voie veineuse centrale selon l'équipe"],
      risks: [risk("bleeding"), risk("gas_embolism"), risk("hypothermia")],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "none", watch: ["pain", "hb", "neuro"] }),
      notes: "Syndromes associés (Apert, Crouzon) : intubation difficile possible. Valve dysfonctionnelle : hypertension intracrânienne, vomissements, séquence rapide. Moelle attachée : décubitus ventral, monitorage neurophysiologique (TIVA, pas de curare après l'induction).",
    }),
  },
  {
    id: pid(102),
    name: "Chirurgie thoracique de l'enfant (pectus, lobectomie)",
    surgery: "Correction de pectus excavatum (Nuss)",
    operation_category: "G",
    hospital: "",
    source: `${CHILD} ; ${MANUAL}, chap. 26.`,
    content: content({
      techniques: ["general", "deep_block"],
      drugs: [childPropofol(), childSufentanil(), drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6 }, "mg", "0,6 mg/kg."), childCefazolin(), drug("Ropivacaïne 0,2 % (ESP ou paravertébral)", "alr", "perinerveux", { perKg: 1.5, max: 150 }, "mg", "1,5 mg/kg au total, maximum 150 mg ; cathéters bilatéraux pour le pectus (manuel, chap. 37)."), childDexa(), childOndansetron(), childParacetamol(), childIbuprofen(), ketamineSparing()],
      targets: ["Pectus : douleur postopératoire intense — péridurale thoracique, ESP ou paravertébral continus, ou cryoanalgésie", "Pectus : passage de la barre sous thoracoscopie (arythmies, perforation cardiaque rare)", "Lobectomie de l'enfant : exclusion pulmonaire par bloqueur bronchique ou intubation sélective"],
      material: [...MONITORING, "Cathéter artériel selon l'équipe", "Échographe"],
      risks: [{ title: "Lésion cardiaque ou hémorragie au passage de la barre", why: "Barre passée derrière le sternum, près du cœur.", prevention: "Thoracoscopie, élévation sternale.", conduct: "Hypotension brutale : sang, sternotomie en urgence." }, risk("ponv")],
      postopPlan: postop({ destination: "hdu", analgesia: ["paracetamol", "nsaid", "perineural", "pca_morphine"], thrombo: "none", watch: ["pain", "sedation"] }),
      notes: "Doses au poids avec plafonds adultes (adolescent). Pas de sonde double lumière chez le petit enfant : bloqueur bronchique ou intubation sélective sous fibroscopie.",
    }),
  },
  {
    id: pid(103),
    name: "Cardiopathie congénitale (chirurgie et cathétérisme)",
    surgery: "Chirurgie des cardiopathies congénitales de l'enfant",
    operation_category: "F",
    hospital: "",
    source: `${CHILD} ; protocole du centre de cardiologie pédiatrique.`,
    content: content({
      techniques: ["general"],
      drugs: [drug("Kétamine", "induction", "bolus_iv", { perKg: 1 }, "mg", "1–2 mg/kg : stabilité hémodynamique."), drug("Fentanyl", "induction", "bolus_iv", { perKg: 1 }, "µg", "1–5 µg/kg titré."), drug("Rocuronium", "induction", "bolus_iv", { perKg: 0.6 }, "mg", "0,6 mg/kg."), childCefazolin(), childAtropine()],
      targets: ["Équilibre des résistances pulmonaires et systémiques selon la lésion (FiO₂, CO₂) avec le cardiopédiatre", "Pas de bulle dans les voies veineuses (shunt droite-gauche)", "Prophylaxie de l'endocardite selon la lésion"],
      material: [...CHILD_MONITORING, "Cathéter artériel", "Filtres à bulles", "Défibrillateur pédiatrique"],
      risks: [risk("induction_hypotension"), { title: "Crise d'hypertension pulmonaire ou de cyanose", why: "Hypoxie, hypercapnie, douleur, acidose.", prevention: "Oxygénation, normocapnie ou hypocapnie modérée, analgésie profonde.", conduct: "FiO₂ 100 %, hyperventilation, approfondir, NO inhalé ; tétralogie : phényléphrine, remplissage, genoux-poitrine." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "opioid_titration"], thrombo: "none", watch: ["pain", "urine"] }),
      notes: "Chirurgie et cathétérisme en centre spécialisé : ce protocole résume les principes, le protocole du centre prévaut.",
    }),
  },

  // ============================================================ Hors bloc et divers
  {
    id: pid(104),
    name: "Endoscopie bronchique (souple, EBUS, rigide, valves)",
    surgery: "Bronchoscopie souple / EBUS",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 22 et 26.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [sedationPropofol(), sedationRemi(), lidocaineTopical(), propofolInduction(), rocuronium()],
      targets: ["Voies aériennes partagées : masque laryngé (EBUS) ou bronchoscope rigide avec jet-ventilation", "Oxygénation : FiO₂ adaptée, pauses si désaturation"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Masque laryngé", "Jet-ventilateur (rigide)", "Masque d'endoscopie"],
      risks: [risk("bronchospasm"), risk("bleeding"), { title: "Pneumothorax (biopsie, valves)", why: "Biopsie transbronchique, valves endobronchiques sur emphysème.", prevention: "Pression de ventilation basse.", conduct: "Désaturation, pressions qui montent : échographie, exsufflation ou drain." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie. Sténose trachéale ou tumeur obstructive : ventilation spontanée jusqu'à la sécurisation, bronchoscope rigide prêt.",
    }),
  },
  {
    id: pid(105),
    name: "Endoscopie digestive interventionnelle (CPRE, écho-endoscopie, dissection)",
    surgery: "CPRE",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 22 ; ESGE/ESAES : sédation en endoscopie.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [sedationPropofol(), sedationRemi(), propofolInduction(), rocuronium(), drug("Céfuroxime (CPRE avec obstacle non drainé)", "antibio", "bolus_iv", { fixed: 1.5 }, "g", "Seulement si obstruction biliaire incomplètement drainée ou kyste pancréatique (ESGE).")],
      targets: ["CPRE en décubitus ventral : AG avec intubation si procédure longue ou estomac plein", "Capnographie sous sédation", "Hémorragie digestive active : AG, séquence rapide"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Cale-dents", "Masque laryngé ou sonde"],
      risks: [risk("aspiration"), { title: "Dépression respiratoire sous sédation", why: "Sédation profonde, position ventrale.", prevention: "Titration, capnographie.", conduct: "Stimuler, subluxation ; intubation si nécessaire (retourner le patient)." }, { title: "Embolie gazeuse (CPRE, POEM)", why: "Insufflation dans les voies biliaires ou la paroi.", prevention: "Insufflation au CO₂.", conduct: "Chute brutale de l'EtCO₂, collapsus : arrêt de l'insufflation, décubitus latéral gauche, FiO₂ 100 %, réanimation." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "POEM et dissection sous-muqueuse : AG avec intubation, pneumopéritoine possible (exsufflation à l'aiguille). Gastrostomie endoscopique : antibioprophylaxie (céfazoline).",
    }),
  },
  {
    id: pid(106),
    name: "Radiologie interventionnelle (embolisation, radiofréquence, biopsie, TIPS)",
    surgery: "Radiologie interventionnelle",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 22.`,
    content: content({
      techniques: ["sedation", "general"],
      drugs: [propofolInduction(), sedationPropofol(), sedationRemi(), drug("Lidocaïne 1 % (infiltration)", "alr", "infiltration", { fixed: 200 }, "mg", "Par le radiologue ; maximum 4,5 mg/kg."), drug("Kétamine", "analgesia", "bolus_iv", { perKg: 0.5 }, "mg", "Radiofréquence ou embolisation douloureuse : 0,25–0,5 mg/kg."), paracetamol(), ondansetron()],
      targets: ["Sédation adaptée à la douleur du geste ; AG pour les radiofréquences hépatiques ou pulmonaires longues", "Produit de contraste : fonction rénale, allergie", "Protection contre les rayons X de l'équipe"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Masque laryngé prêt", "Tablier plombé"],
      risks: [risk("anaphylaxis"), { title: "Syndrome post-embolisation", why: "Nécrose tissulaire (utérus, foie).", prevention: "Analgésie multimodale anticipée.", conduct: "Douleur, fièvre, nausées : antalgiques, antiémétiques." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol", "nsaid"], thrombo: "none", watch: ["pain"] }),
      notes: "Antibioprophylaxie selon le geste (chimio-embolisation, TIPS, drainage biliaire : protocole du radiologue). Vertébroplastie : décubitus ventral, sédation ou AG. TIPS : cirrhose, ascite, estomac plein.",
    }),
  },
  {
    id: pid(107),
    name: "Électroconvulsivothérapie",
    surgery: "Électroconvulsivothérapie",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 22 et 31 (psychiatrie).`,
    content: content({
      techniques: ["general"],
      drugs: [drug("Propofol (ECT)", "induction", "bolus_iv", { perKg: 1 }, "mg", "0,75–1 mg/kg (ou étomidate 0,15–0,3 mg/kg) : la dose influence la durée de la crise."), drug("Suxaméthonium (succinylcholine)", "induction", "bolus_iv", { perKg: 1 }, "mg", "0,5–1 mg/kg : atténue la crise motrice (manuel, chap. 8)."), childAtropine(), drug("Esmolol", "haemodynamic", "bolus_iv", { fixed: 20 }, "mg", "Poussée hypertensive et tachycardie de la crise.")],
      targets: ["Ventilation au masque (hyperventilation avant le choc : allonge la crise)", "Cale-dents", "Même protocole à chaque séance (noter les doses et la durée de la crise)"],
      material: ["ECG", "PNI", "SpO₂", "EtCO₂", "Cale-dents", "Garrot sur un bras (crise visible)", "Masque facial"],
      risks: [{ title: "Réponse vagale puis sympathique", why: "Stimulus électrique : bradycardie puis tachycardie et hypertension.", prevention: "Atropine selon le terrain, esmolol prêt.", conduct: "Bradycardie : atropine ; hypertension : esmolol, urapidil." }, { title: "Crise prolongée (> 120 s)", why: "Seuil abaissé.", prevention: "Doses adaptées.", conduct: "Propofol ou midazolam pour l'arrêter." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["neuro"] }),
      notes: "Pas d'antibioprophylaxie. Interactions : IMAO, lithium (curarisation prolongée), benzodiazépines (seuil de crise).",
    }),
  },
  {
    id: pid(108),
    name: "Prélèvement d'organes (donneur en mort encéphalique)",
    surgery: "Prélèvement d'organes",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 41 ; protocole de la coordination de transplantation.`,
    content: content({
      techniques: ["general"],
      drugs: [rocuronium(), noradrenaline("PAM ≥ 65 mmHg ; vasopressine si besoin."), drug("Méthylprednisolone", "other", "bolus_iv", { fixed: 1000 }, "mg", "15 mg/kg selon le protocole de la coordination."), drug("Héparine non fractionnée", "haemodynamic", "bolus_iv", { fixed: 25000 }, "UI", "300 UI/kg avant le clampage, sur demande des chirurgiens."), cefazolin("Selon le protocole de la coordination.")],
      targets: ["Réanimation des organes : PAM ≥ 65 mmHg, diurèse 1–3 mL/kg/h, Na 135–145 mmol/L, normothermie", "Ventilation protectrice (poumons prélevés : FiO₂ minimale, PEP, recrutement)", "Curarisation (réflexes médullaires)"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "Sonde urinaire"],
      risks: [{ title: "Diabète insipide", why: "Mort encéphalique.", prevention: "Diurèse et natrémie surveillées.", conduct: "Diurèse > 4 mL/kg/h : desmopressine, compensation." }, { title: "Instabilité hémodynamique", why: "Perte du tonus sympathique.", prevention: "Remplissage, noradrénaline.", conduct: "Vasopressine, hormones thyroïdiennes selon le protocole." }],
      postopPlan: postop({ destination: "icu", analgesia: [], thrombo: "none", watch: [] }),
      notes: "Accompagnement de la famille et de l'équipe ; protocole de la coordination (antibioprophylaxie, corticoïdes) prioritaire.",
    }),
  },
  {
    id: pid(109),
    name: "Gestes antalgiques et neuraxiaux (blood patch, infiltration)",
    surgery: "Blood patch",
    operation_category: "X",
    hospital: "",
    source: `${MANUAL}, chap. 13 et 25.`,
    content: content({
      techniques: ["neuraxial", "sedation"],
      drugs: [drug("Sang autologue (blood patch)", "other", "peridural", { fixed: 20 }, "mL", "15–20 mL prélevés stérilement, injectés jusqu'à la douleur lombaire ; décubitus 1–2 h."), drug("Lidocaïne 1 % (infiltration cutanée)", "alr", "infiltration", { fixed: 50 }, "mg", "Point de ponction."), paracetamol()],
      targets: ["Asepsie stricte (bilan infectieux négatif)", "Pas d'anticoagulant, coagulation normale"],
      material: ["PNI", "SpO₂", "Kit de péridurale"],
      risks: [{ title: "Complications de la ponction péridurale", why: "Nouvelle brèche, hématome ou infection.", prevention: "Coagulation normale, pas d'anticoagulant, asepsie stricte, opérateur expérimenté.", conduct: "Douleur radiculaire, fièvre, déficit : imagerie en urgence." }, { title: "Céphalée persistante", why: "Échec du premier patch.", prevention: "Diagnostic confirmé (céphalée posturale).", conduct: "Second patch après 24–48 h ; imagerie si atypique (thrombose veineuse, hématome)." }],
      postopPlan: postop({ destination: "ambulatory", analgesia: ["paracetamol"], thrombo: "none", watch: ["pain"] }),
      notes: "Pas d'antibioprophylaxie. Infiltrations radioguidées : AL, sédation légère si besoin.",
    }),
  },
  {
    id: pid(110),
    name: "Chirurgie trachéale, pulmonaire de recours et transplantation thoracique",
    surgery: "Résection trachéale",
    operation_category: "G",
    hospital: "",
    source: `${MANUAL}, chap. 26 et 41 ; protocole du centre.`,
    content: content({
      techniques: ["general", "neuraxial"],
      drugs: [propofolInduction(1.5), remifentanil(), rocuronium(), cefazolin(), dexamethasone(8), noradrenaline(), paracetamol(), drug("Ropivacaïne 0,2 % (péridurale thoracique)", "alr", "peridural", { fixed: 10 }, "mg", "Si coagulation compatible (pas pour la transplantation sous ECMO ou CEC héparinée : ESP ou paravertébral).")],
      targets: ["Résection trachéale : ventilation croisée par le champ opératoire, jet-ventilation, ECMO en secours", "Transplantation pulmonaire : ECMO ou CEC selon l'équipe, ventilation protectrice", "Extubation précoce si possible (anastomose trachéale : flexion du cou)"],
      material: [...MONITORING, "Cathéter artériel", "Voie veineuse centrale", "Sondes stériles pour le champ", "Jet-ventilateur", "ETO (transplantation)"],
      risks: [risk("difficult_airway"), risk("bleeding"), { title: "Perte du contrôle des voies aériennes", why: "Ouverture de la trachée.", prevention: "Plan partagé avec le chirurgien, sondes prêtes, ECMO disponible.", conduct: "Intubation par le champ, jet-ventilation, ECMO." }],
      postopPlan: postop({ destination: "icu", analgesia: ["paracetamol", "pcea"], pcea: DEFAULT_PCEA, thrombo: "lmwh", watch: ["pain"] }),
      notes: "Chirurgie de centre spécialisé : le protocole du centre prévaut.",
    }),
  },
];
