// Usual treatments other than antithrombotics — DRAFTS proposed from the
// most recent consensus statements on preoperative medication management
// (SPAQI series, Mayo Clin Proc 2021–2022; ACR/AAHKS 2022 for antirheumatic
// drugs; SPAQI 2026 for the SGLT2 inhibitors). Only the abstracts could be
// read from PreOx's build environment: the figures are the ones these
// statements are commonly cited for, and each rule must be checked against
// the full text before it is activated — hence the question on each.

import { MANUAL_RULES } from "./proposed-manual";
import type { Rule, RuleSource } from "./types";

type Proposed = Omit<Rule, "created_at" | "updated_at">;

const id = (n: number) => `5f1c0a10-0005-4000-8000-${String(n).padStart(12, "0")}`;

const spaqi = (title: string, year: number, doi: string, pmid: string): RuleSource => ({
  organisation: "SPAQI (Society for Perioperative Assessment and Quality Improvement)",
  title,
  year,
  doi,
  pmid,
  quote: "",
  grade: "Consensus Delphi",
  level: "int",
});

const PSY = spaqi("Preoperative Management of Medications for Psychiatric Diseases: SPAQI Consensus Statement (Mayo Clin Proc 2022;97:397-416)", 2022, "10.1016/j.mayocp.2021.11.011", "35120702");
const NEURO = spaqi("Preoperative Management of Medications for Neurologic Diseases: SPAQI Consensus Statement (Mayo Clin Proc 2022)", 2022, "10.1016/j.mayocp.2021.11.010", "35120701");
const ENDO = spaqi("Preoperative Management of Endocrine, Hormonal, and Urologic Medications: SPAQI Consensus Statement (Mayo Clin Proc 2021)", 2021, "10.1016/j.mayocp.2020.10.002", "33714600");
const GI_PULM = spaqi("Preoperative Management of Gastrointestinal and Pulmonary Medications: SPAQI Consensus Statement (Mayo Clin Proc 2021)", 2021, "10.1016/j.mayocp.2021.08.008", "34736777");
const CARDIO = spaqi("Preoperative Management of Cardiovascular Medications: SPAQI Consensus Statement (Mayo Clin Proc 2022)", 2022, "10.1016/j.mayocp.2022.03.039", "36058586");
const RHEUM_HIV = spaqi("Preoperative Management of Medications for Rheumatologic and HIV Diseases: SPAQI Consensus Statement (Mayo Clin Proc 2022)", 2022, "10.1016/j.mayocp.2022.05.002", "35933139");
const SUPPLEMENTS = spaqi("Preoperative Management of Surgical Patients Using Dietary Supplements: SPAQI Consensus Statement (Mayo Clin Proc 2021)", 2021, "10.1016/j.mayocp.2020.08.016", "33741131");
const SGLT2_2026 = spaqi("Perioperative management of patients taking SGLT2 inhibitors: SPAQI multidisciplinary consensus statement (Br J Anaesth 2026)", 2026, "10.1016/j.bja.2026.02.031", "42067493");
const ACR_2022: RuleSource = {
  organisation: "ACR / AAHKS",
  title: "2022 American College of Rheumatology/American Association of Hip and Knee Surgeons Guideline for the Perioperative Management of Antirheumatic Medication in Patients With Rheumatic Diseases Undergoing Elective Total Hip or Total Knee Arthroplasty",
  year: 2022,
  doi: "10.1002/acr.24893",
  pmid: "35718887",
  quote: "",
  grade: "GRADE",
  level: "int",
};

const SERTOZ_2025 = "Recoupé (Consensus, septembre 2026) — Sertöz et al., Minerva Anestesiol 2025 (PMID 40873193) : « The decision to maintain or adjust monoamine oxidase inhibitors or psychostimulants should be carefully individualized, considering the patient's overall health status and the potential for drug interactions with specific anesthetic agents. »";

const COREMANS_2026: RuleSource = {
  organisation: "Acta Anaesthesiologica Belgica (revue narrative de 10 recommandations 2015–2024)",
  title: "Towards ending the perioperative metformin controversy: a narrative review (Coremans et al., Acta Anaesthesiol Belg 2026) — https://consensus.app/papers/details/5087325a64785cb9946e39c9eaa9a27c/",
  year: 2026,
  doi: "",
  pmid: "",
  quote: "Seven out of ten guidelines support continuing metformin in patients without risk factors, such as impaired renal function or the use of contrast agents. When risk factors are present, most guidelines recommend withholding metformin on the morning of surgery.",
  grade: "Revue narrative",
  level: "article",
};
const ASER_POQI_2019: RuleSource = {
  organisation: "ASER / POQI",
  title: "American Society for Enhanced Recovery and Perioperative Quality Initiative Joint Consensus Statement on Perioperative Management of Patients on Preoperative Opioid Therapy (Edwards et al., Anesth Analg 2019;129:553-566)",
  year: 2019,
  doi: "10.1213/ANE.0000000000004018",
  pmid: "30768461",
  quote: "",
  grade: "Consensus",
  level: "int",
};
const BEVACIZUMAB: RuleSource = {
  organisation: "RCP du bévacizumab (Avastin), repris par la littérature",
  title: "A review on bevacizumab and surgical wound healing: an important warning to all surgeons (Gordon et al., Ann Plast Surg 2009;62:707-9)",
  year: 2009,
  doi: "10.1097/SAP.0b013e3181828141",
  pmid: "19461291",
  quote: "Current literature suggests patients should wait at least 6 to 8 weeks (>40 days) after cessation to have surgery (half-life = 20 days). In addition, postoperative reinitiation of bevacizumab must wait > or =28 days to prevent an increased risk of wound healing complications, and the surgical incision should be fully healed.",
  grade: "Revue",
  level: "article",
};
const IBRUTINIB: RuleSource = {
  organisation: "RCP de l'ibrutinib (Imbruvica), repris par la littérature",
  title: "Simulation of perioperative ibrutinib withdrawal using a population pharmacokinetic model (Kimura et al., Cancer Chemother Pharmacol 2025;95:107)",
  year: 2025,
  doi: "10.1007/s00280-025-04816-2",
  pmid: "41264019",
  quote: "After a withdrawal period of 3-7 days there were no bleeding events in patients that underwent surgery with a low bleeding risk; however, bleeding events occurred in one patient that underwent gastrectomy with moderate or higher bleeding risk.",
  grade: "Étude exploratoire",
  level: "article",
};

const ICI_REVIEW: RuleSource = {
  organisation: "Br J Anaesth (revue) ; J Anesth 2026 (cohorte)",
  title: "Immune checkpoint inhibitors: a narrative review of considerations for the anaesthesiologist (Lewis et al., Br J Anaesth 2020) ; Effects of immune checkpoint inhibitors on perioperative endocrine abnormalities and intraoperative hemodynamics (Li et al., J Anesth 2026)",
  year: 2026,
  doi: "",
  pmid: "",
  quote: "Subgroup analysis of ICI-treated patients showed higher incidences of sustained intraoperative hypotension (…) in the endocrine irAEs cohort compared with matched controls.",
  grade: "Revue et cohorte",
  level: "article",
};
const IMWG_2008: RuleSource = {
  organisation: "International Myeloma Working Group",
  title: "Prevention of thalidomide- and lenalidomide-associated thrombosis in myeloma (Palumbo et al., Leukemia 2008) — https://consensus.app/papers/details/db029a28e524591eb929479430d0a9b0/",
  year: 2008,
  doi: "",
  pmid: "",
  quote: "Individual risk factors for thrombosis associated with thalidomide/lenalidomide-based therapy include age, history of VTE, central venous catheter, comorbidities (infections, diabetes, cardiac disease), immobilization, surgery and inherited thrombophilia.",
  grade: "Consensus d'experts",
  level: "int",
};
const SMPC: RuleSource = {
  organisation: "RCP (résumé des caractéristiques du produit), via le CBIP",
  title: "Résumé des caractéristiques du produit — consulter la fiche CBIP de la spécialité",
  year: 2026,
  doi: "",
  pmid: "",
  quote: "",
  grade: "RCP",
  level: "be_inst",
};

const ARTHROPLASTY = "La recommandation ACR/AAHKS porte sur la prothèse de hanche et de genou programmée ; elle est couramment étendue aux autres chirurgies orthopédiques programmées, pas au-delà sans avis.";

const draft = (n: number, p: Pick<Proposed, "title" | "statement" | "conditions" | "action" | "source" | "question"> & Partial<Proposed>): Proposed => ({
  id: id(n),
  divergences: [],
  explanations: [],
  status: "draft",
  version: 1,
  verified_at: null,
  review_at: null,
  tool: "PreOx (proposition à vérifier sur le texte intégral)",
  ...p,
});

const drug = (atc: string) => ({ kind: "drug" as const, atc });
const continueIt = (text: string) => ({ type: "info" as const, text, target: "both" as const });

export const TREATMENT_RULES: Proposed[] = [
  // --- Psychiatrie -------------------------------------------------------------------------
  draft(1, {
    title: "Antidépresseurs ISRS et IRSN : poursuivre",
    statement: "Les ISRS et IRSN sont poursuivis, y compris le matin de l'intervention (risque de syndrome d'arrêt et de rechute).",
    conditions: [drug("N06AB")],
    action: continueIt("Poursuivre l'ISRS, matin de l'intervention compris ; éviter les autres sérotoninergiques (tramadol, péthidine, méthylène bleu)."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus on psychiatric medications, should SSRIs and SNRIs be continued on the day of surgery, and which perioperative interactions should be considered?",
  }),
  draft(2, {
    title: "Autres antidépresseurs (IRSN, mirtazapine, trazodone) : poursuivre",
    statement: "Venlafaxine, duloxétine, mirtazapine, trazodone et apparentés sont poursuivis.",
    conditions: [drug("N06AX")],
    action: continueIt("Poursuivre, matin de l'intervention compris ; syndrome sérotoninergique avec tramadol, péthidine, méthylène bleu."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus, how should venlafaxine, duloxetine, mirtazapine, trazodone and bupropion be managed before surgery?",
  }),
  draft(3, {
    title: "Antidépresseurs tricycliques : poursuivre",
    statement: "Les tricycliques sont poursuivis ; vasopresseurs indirects à éviter, agonistes directs à dose réduite.",
    conditions: [drug("N06AA")],
    action: continueIt("Poursuivre ; préférer les vasopresseurs directs (phényléphrine, noradrénaline) à faible dose ; QT."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus, should tricyclic antidepressants be continued before surgery, and what anaesthetic precautions apply?",
  }),
  draft(4, {
    title: "IMAO irréversibles : poursuivre avec une anesthésie adaptée",
    statement: "Les IMAO sont en règle poursuivis (un arrêt exige 2 semaines et un avis psychiatrique) ; péthidine, tramadol, dextrométhorphane et vasopresseurs indirects sont proscrits.",
    conditions: [drug("N06AF")],
    action: continueIt("Poursuivre sauf décision avec le psychiatre (sevrage de 2 semaines) ; pas de péthidine, tramadol, éphédrine ; vasopresseurs directs à faible dose."),
    source: PSY,
    explanations: [SERTOZ_2025],
    question: "According to the SPAQI 2022 consensus, should irreversible MAO inhibitors be continued or stopped before surgery (and how long before), and which drugs must be avoided?",
  }),
  draft(5, {
    title: "Moclobémide : poursuivre, mêmes précautions",
    statement: "Le moclobémide (IMAO-A réversible) est poursuivi ; mêmes interactions à éviter qu'avec les IMAO.",
    conditions: [drug("N06AG")],
    action: continueIt("Poursuivre ; pas de péthidine, tramadol ni vasopresseur indirect."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus, how should moclobemide (reversible MAO-A inhibitor) be managed before surgery?",
  }),
  draft(6, {
    title: "Lithium : arrêt 72 h avant une chirurgie majeure",
    statement: "Le lithium est arrêté 72 h avant une chirurgie majeure (déséquilibres hydroélectrolytiques, potentialisation des curares) et poursuivi pour une chirurgie mineure ; lithémie et fonction rénale.",
    conditions: [drug("N05AN"), { kind: "surgery", attribute: "grade", in: ["major"] }],
    action: { type: "stop_before", hours: 72, target: "both" },
    source: PSY,
    explanations: ["Reprise quand l'alimentation et l'hydratation sont rétablies, avec lithémie et créatinine."],
    question: "According to the SPAQI 2022 consensus on psychiatric medications, should lithium be stopped before major surgery, how many hours before, and when should it be resumed?",
  }),
  draft(7, {
    title: "Lithium : lithémie et ionogramme",
    statement: "Sous lithium, lithémie, natrémie et créatinine avant l'intervention.",
    conditions: [drug("N05AN")],
    action: { type: "exam", exam: "Lithémie, ionogramme, créatinine", withinDays: 30 },
    source: PSY,
    question: "According to the SPAQI 2022 consensus, which laboratory tests are recommended before surgery in a patient on lithium?",
  }),
  draft(8, {
    title: "Antipsychotiques : poursuivre",
    statement: "Les antipsychotiques sont poursuivis (risque de décompensation) ; QT à vérifier.",
    conditions: [drug("N05A")],
    action: continueIt("Poursuivre, matin de l'intervention compris ; ECG (QT) si plusieurs médicaments qui l'allongent."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus, should antipsychotics (including clozapine) be continued on the day of surgery?",
  }),
  draft(9, {
    title: "Benzodiazépines au long cours : poursuivre",
    statement: "Les benzodiazépines prises au long cours sont poursuivies (syndrome de sevrage).",
    conditions: [drug("N05B")],
    action: continueIt("Poursuivre à la dose habituelle ; tolérance aux hypnotiques."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus, should chronic benzodiazepines be continued before surgery?",
  }),
  draft(10, {
    title: "Psychostimulants (TDAH) : décision au cas par cas",
    statement: "Méthylphénidate et amphétamines : poursuite ou suspension le jour de l'intervention décidée au cas par cas ; chez l'enfant, la prise du matin ne s'accompagne pas d'instabilité hémodynamique.",
    conditions: [drug("N06BA")],
    action: { type: "info", text: "Poursuivre ou suspendre le matin selon le terrain (cardiopathie, HTA) ; s'il est pris : vasopresseurs directs à faible dose, pas d'éphédrine en première intention.", target: "anaesthesia" },
    source: PSY,
    explanations: [SERTOZ_2025, "Cartabuke et al., Paediatr Anaesth 2017 : « continuing preoperative stimulant medication is not associated with cardiovascular instability in the pediatric population »."],
    question: "According to the SPAQI 2022 consensus, should ADHD stimulants (methylphenidate, amphetamines) be held on the day of surgery or continued?",
  }),
  // --- Neurologie ----------------------------------------------------------------------------
  draft(11, {
    title: "Antiépileptiques : poursuivre sans interruption",
    statement: "Les antiépileptiques sont poursuivis, y compris le matin de l'intervention ; voie IV si le jeûne se prolonge.",
    conditions: [drug("N03")],
    action: continueIt("Poursuivre sans omettre de prise ; relais IV (lévétiracétam, valproate…) si la voie orale n'est pas possible."),
    source: NEURO,
    question: "According to the SPAQI 2022 consensus on neurologic medications, should antiepileptic drugs be continued on the day of surgery, and how should missed oral doses be replaced?",
  }),
  draft(12, {
    title: "Anticholinestérasiques (démence) : poursuivre",
    statement: "Donépézil, rivastigmine et galantamine sont poursuivis ; succinylcholine prolongée, curares non dépolarisants moins efficaces.",
    conditions: [drug("N06DA")],
    action: continueIt("Poursuivre ; succinylcholine prolongée, résistance relative aux curares non dépolarisants."),
    source: NEURO,
    question: "According to the SPAQI 2022 consensus, should acetylcholinesterase inhibitors for dementia be continued before surgery, and what are the interactions with neuromuscular blockers?",
  }),
  draft(13, {
    title: "Anticholinestérasiques (myasthénie) : poursuivre",
    statement: "La pyridostigmine est poursuivie le matin de l'intervention (risque de crise myasthénique).",
    conditions: [drug("N07AA")],
    action: continueIt("Poursuivre (sauf protocole local différent) ; monitorage de la curarisation, sugammadex pour la décurarisation."),
    source: NEURO,
    divergences: [{ summary: "Le Manuel pratique (2020) propose un arrêt 6 h avant : la pratique la plus récente est la poursuite.", source: "Manuel pratique d'anesthésie 2020", level: "book" }],
    question: "According to the SPAQI 2022 consensus on neurologic medications, should pyridostigmine be continued on the morning of surgery in myasthenia gravis?",
  }),
  // --- Endocrinologie, hormones, urologie ----------------------------------------------------
  draft(14, {
    title: "Insuline basale : 75 à 80 % de la dose la veille au soir",
    statement: "L'insuline basale (glargine, détémir, dégludec) est poursuivie à 75–80 % de la dose habituelle la veille au soir (ou le matin si elle est prise le matin).",
    conditions: [drug("A10AE")],
    action: continueIt("Insuline basale : 75–80 % de la dose habituelle la veille et le jour de l'intervention ; glycémies capillaires."),
    source: ENDO,
    divergences: [{ summary: "CPOC/JBDS 2021 : 80 % de la dose de la veille et du jour.", source: "CPOC 2021", level: "int" }],
    question: "According to current guidelines (SPAQI 2021, CPOC 2021, ADA Standards of Care), what dose of basal insulin should be given the evening before and the morning of surgery?",
  }),
  draft(15, {
    title: "Insulines rapides : suspendues pendant le jeûne",
    statement: "Les insulines prandiales (rapides) ne sont pas administrées pendant le jeûne ; corrections selon la glycémie.",
    conditions: [drug("A10AB")],
    action: continueIt("Pas d'insuline rapide à jeun ; schéma de correction selon les glycémies."),
    source: ENDO,
    question: "According to SPAQI 2021 and CPOC 2021, how should prandial (rapid-acting) insulin be managed while fasting before surgery?",
  }),
  draft(16, {
    title: "Insulines prémélangées : moitié de la dose du matin",
    statement: "Les insulines prémélangées sont données à 50 % de la dose habituelle le matin de l'intervention.",
    conditions: [drug("A10AD")],
    action: continueIt("Prémélange : 50 % de la dose du matin, perfusion de glucose selon la glycémie."),
    source: ENDO,
    question: "According to CPOC 2021 and SPAQI 2021, what dose of premixed insulin should be given on the morning of surgery?",
  }),
  draft(17, {
    title: "Gliptines : poursuivre",
    statement: "Les inhibiteurs de la DPP-4 peuvent être poursuivis le jour de l'intervention (peu d'hypoglycémies).",
    conditions: [drug("A10BH")],
    action: continueIt("Poursuivre (risque d'hypoglycémie faible)."),
    source: ENDO,
    question: "According to SPAQI 2021 and CPOC 2021, can DPP-4 inhibitors be continued on the day of surgery?",
  }),
  draft(18, {
    title: "Lévothyroxine : poursuivre",
    statement: "La lévothyroxine est poursuivie ; quelques jours sans prise sont sans conséquence (demi-vie de 7 jours).",
    conditions: [drug("H03AA")],
    action: continueIt("Poursuivre ; une omission de quelques jours est sans conséquence."),
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should levothyroxine be continued on the day of surgery?",
  }),
  draft(19, {
    title: "Antithyroïdiens : poursuivre",
    statement: "Thiamazole et propylthiouracile sont poursuivis, y compris le jour de l'intervention.",
    conditions: [drug("H03B")],
    action: continueIt("Poursuivre ; euthyroïdie à confirmer avant une chirurgie programmée."),
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should antithyroid drugs be continued on the day of surgery?",
  }),
  draft(20, {
    title: "Contraception œstroprogestative : discuter l'arrêt avant une chirurgie à haut risque thromboembolique",
    statement: "La contraception œstroprogestative est poursuivie en règle ; avant une chirurgie majeure à haut risque thromboembolique, un arrêt 4 à 6 semaines avant (avec une autre contraception) se discute.",
    conditions: [drug("G03A"), { kind: "surgery", attribute: "grade", in: ["major"] }],
    action: { type: "info", text: "Chirurgie majeure : discuter l'arrêt 4 à 6 semaines avant (contraception alternative, test de grossesse) ; sinon thromboprophylaxie renforcée.", target: "surgery" },
    source: ENDO,
    question: "According to the SPAQI 2021 consensus and European VTE guidelines (ESAIC 2018), should combined hormonal contraceptives be stopped before major surgery, and how many weeks before?",
  }),
  draft(21, {
    title: "Traitement hormonal de la ménopause : discuter l'arrêt avant une chirurgie à haut risque thromboembolique",
    statement: "Le THM est poursuivi en règle ; avant une chirurgie à haut risque thromboembolique, un arrêt 4 semaines avant se discute.",
    conditions: [drug("G03C"), { kind: "surgery", attribute: "grade", in: ["major"] }],
    action: { type: "info", text: "Chirurgie majeure : discuter l'arrêt 4 semaines avant, ou thromboprophylaxie adaptée.", target: "surgery" },
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should menopausal hormone therapy be stopped before surgery with a high risk of venous thromboembolism, and how long before?",
  }),
  draft(22, {
    title: "Raloxifène : arrêt 3 jours avant",
    statement: "Le raloxifène (modulateur sélectif des récepteurs aux œstrogènes, ostéoporose) est arrêté 3 jours avant une chirurgie à risque thromboembolique.",
    conditions: [drug("G03XC")],
    action: { type: "stop_before", hours: 72, target: "surgery" },
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, how many days before surgery should raloxifene be stopped?",
  }),
  draft(23, {
    title: "Tamoxifène : décision avec l'oncologue",
    statement: "Le tamoxifène pris pour un cancer n'est pas arrêté sans l'avis de l'oncologue ; thromboprophylaxie adaptée.",
    conditions: [drug("L02BA")],
    action: { type: "info", text: "Ne pas arrêter sans avis oncologique ; risque thromboembolique à intégrer à la thromboprophylaxie.", target: "surgery" },
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should tamoxifen be stopped before surgery, and who decides?",
  }),
  draft(24, {
    title: "Inhibiteurs de la PDE5 (dysfonction érectile) : arrêt 24 h avant",
    statement: "Sildénafil et vardénafil sont arrêtés 24 h avant, le tadalafil 48 h avant (hypotension, interaction avec les dérivés nitrés) — sauf s'ils traitent une hypertension pulmonaire.",
    conditions: [drug("G04BE")],
    action: { type: "stop_before", hours: 24, target: "anaesthesia" },
    source: ENDO,
    divergences: [{ summary: "Tadalafil : 48 h (demi-vie plus longue). Hypertension pulmonaire : ne jamais interrompre.", source: "SPAQI 2021", level: "int" }],
    question: "According to the SPAQI 2021 and 2022 consensus statements, how long before surgery should phosphodiesterase-5 inhibitors used for erectile dysfunction be stopped (sildenafil, tadalafil), and what if they treat pulmonary hypertension?",
  }),
  draft(25, {
    title: "Alpha-bloquants urologiques : poursuivre, prévenir le chirurgien ophtalmologue",
    statement: "Tamsulosine et apparentés sont poursuivis ; syndrome de l'iris flasque à signaler avant une chirurgie de la cataracte.",
    conditions: [drug("G04CA")],
    action: continueIt("Poursuivre ; cataracte : syndrome de l'iris flasque à signaler au chirurgien."),
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should alpha-blockers for benign prostatic hyperplasia be continued before surgery?",
  }),
  draft(26, {
    title: "Inhibiteurs du SGLT2 : approche selon le terrain (SPAQI 2026)",
    statement: "SPAQI 2026 adapte l'arrêt des inhibiteurs du SGLT2 à la présence d'un diabète, aux comorbidités et au jeûne, avec surveillance de la cétonémie.",
    conditions: [drug("A10BK")],
    action: { type: "info", text: "Délai d'arrêt selon le terrain (diabète ou non, insuffisance cardiaque, jeûne prolongé) ; cétonémie si malaise, nausées ou acidose, même avec une glycémie normale.", target: "both" },
    source: SGLT2_2026,
    explanations: ["La règle vérifiée (ESC 2022, arrêt 3 jours avant) reste celle appliquée ; ce brouillon signale la révision SPAQI 2026, dont seul le résumé a pu être lu."],
    question: "According to the SPAQI 2026 consensus statement on SGLT2 inhibitors (Br J Anaesth 2026), how many days before surgery should SGLT2 inhibitors be stopped in patients with and without diabetes, and how should euglycaemic ketoacidosis be monitored?",
  }),
  // --- Cardiovasculaire (hors antithrombotiques) -----------------------------------------------
  draft(27, {
    title: "Amiodarone : poursuivre",
    statement: "L'amiodarone est poursuivie (demi-vie très longue) ; TSH, QT.",
    conditions: [drug("C01BD")],
    action: continueIt("Poursuivre ; ECG (QT, bradycardie) et fonction thyroïdienne."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus on cardiovascular medications, should amiodarone and other class III antiarrhythmics be continued on the day of surgery?",
  }),
  draft(28, {
    title: "Digoxine : poursuivre",
    statement: "La digoxine est poursuivie ; kaliémie et fonction rénale, digoxinémie si doute de toxicité.",
    conditions: [drug("C01AA")],
    action: continueIt("Poursuivre ; kaliémie, créatinine."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus, should digoxin be continued on the day of surgery?",
  }),
  draft(29, {
    title: "Inhibiteurs calciques : poursuivre",
    statement: "Les inhibiteurs calciques sont poursuivis, y compris le matin de l'intervention.",
    conditions: [drug("C08")],
    action: continueIt("Poursuivre, matin de l'intervention compris."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus, should calcium-channel blockers be continued on the morning of surgery?",
  }),
  draft(30, {
    title: "Antihypertenseurs centraux : ne pas interrompre",
    statement: "Clonidine et moxonidine sont poursuivies (rebond hypertensif à l'arrêt).",
    conditions: [drug("C02AC")],
    action: continueIt("Poursuivre, matin de l'intervention compris (rebond hypertensif)."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus, should centrally acting sympatholytics (clonidine) be continued before surgery?",
  }),
  draft(31, {
    title: "Dérivés nitrés : poursuivre",
    statement: "Les dérivés nitrés sont poursuivis.",
    conditions: [drug("C01DA")],
    action: continueIt("Poursuivre ; jamais d'inhibiteur de la PDE5 associé."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus, should nitrates be continued on the day of surgery?",
  }),
  draft(32, {
    title: "Hypertension artérielle pulmonaire : ne jamais interrompre",
    statement: "Antagonistes des récepteurs de l'endothéline, riociguat, prostanoïdes et inhibiteurs de la PDE5 prescrits pour une HTAP ne sont jamais interrompus.",
    conditions: [drug("C02KX")],
    action: continueIt("Ne jamais interrompre ; relais IV ou inhalé si nécessaire ; centre expert."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus (endothelin receptor antagonists) and current pulmonary hypertension guidelines, should pulmonary arterial hypertension therapies be continued perioperatively?",
  }),
  draft(33, {
    title: "Alpha-bloquants antihypertenseurs : poursuivre",
    statement: "Doxazosine et prazosine sont poursuivies ; hypotension à l'induction.",
    conditions: [drug("C02CA")],
    action: continueIt("Poursuivre ; hypotension à l'induction."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus, should alpha-adrenergic receptor antagonists be continued before surgery?",
  }),
  // --- Pneumologie, digestif -------------------------------------------------------------------
  draft(34, {
    title: "Traitements inhalés : poursuivre et apporter l'inhalateur",
    statement: "Bronchodilatateurs et corticoïdes inhalés sont poursuivis, y compris le matin de l'intervention.",
    conditions: [drug("R03")],
    action: continueIt("Poursuivre, prise le matin de l'intervention, apporter l'inhalateur au bloc."),
    source: GI_PULM,
    question: "According to the SPAQI 2021 consensus on pulmonary medications, should inhaled bronchodilators and corticosteroids be taken on the morning of surgery?",
  }),
  draft(35, {
    title: "Théophylline : suspendre la veille au soir",
    statement: "La théophylline est suspendue la veille au soir (marge thérapeutique étroite, arythmies, interactions).",
    conditions: [drug("R03DA")],
    action: { type: "stop_before", hours: 12, target: "anaesthesia" },
    source: GI_PULM,
    question: "According to the SPAQI 2021 consensus, should theophylline be held before surgery, and from when?",
  }),
  draft(36, {
    title: "IPP : poursuivre",
    statement: "Les inhibiteurs de la pompe à protons sont poursuivis, y compris le matin de l'intervention.",
    conditions: [drug("A02BC")],
    action: continueIt("Poursuivre, matin de l'intervention compris."),
    source: GI_PULM,
    question: "According to the SPAQI 2021 consensus, should proton-pump inhibitors be taken on the morning of surgery?",
  }),
  // --- Rhumatologie, immunologie, VIH ----------------------------------------------------------
  draft(37, {
    title: "Méthotrexate, léflunomide, hydroxychloroquine, sulfasalazine : poursuivre",
    statement: "Les traitements de fond conventionnels (méthotrexate, léflunomide, hydroxychloroquine, sulfasalazine, aprémilast) sont poursuivis pendant la période opératoire.",
    conditions: [drug("L04AX03")],
    action: continueIt("Poursuivre (arrêt non recommandé : le risque de poussée l'emporte)."),
    source: ACR_2022,
    explanations: [ARTHROPLASTY],
    question: "According to the 2022 ACR/AAHKS guideline, should methotrexate, leflunomide, hydroxychloroquine, sulfasalazine and apremilast be continued through elective arthroplasty?",
  }),
  draft(38, {
    title: "Anti-TNF et autres biothérapies : chirurgie en fin d'intervalle",
    statement: "Les biothérapies sont suspendues et la chirurgie programmée à la fin de l'intervalle entre deux injections (semaine suivant la dose omise) ; reprise après cicatrisation, au moins 14 jours.",
    conditions: [drug("L04AB")],
    action: { type: "info", text: "Programmer la chirurgie à la fin de l'intervalle d'administration (injection suivante omise) ; reprise après cicatrisation, ≥ 14 jours, sans infection.", target: "surgery" },
    source: ACR_2022,
    explanations: [ARTHROPLASTY],
    question: "According to the 2022 ACR/AAHKS guideline, how should biologics (anti-TNF, IL-6, IL-17, IL-12/23 inhibitors, abatacept, rituximab) be withheld before elective arthroplasty, and when should they be restarted?",
  }),
  draft(39, {
    title: "Anti-interleukines : chirurgie en fin d'intervalle",
    statement: "Même conduite que pour les anti-TNF : chirurgie à la fin de l'intervalle d'administration, reprise après cicatrisation.",
    conditions: [drug("L04AC")],
    action: { type: "info", text: "Programmer la chirurgie à la fin de l'intervalle d'administration ; reprise après cicatrisation (≥ 14 jours).", target: "surgery" },
    source: ACR_2022,
    explanations: [ARTHROPLASTY],
    question: "According to the 2022 ACR/AAHKS guideline, when should IL-6, IL-17 and IL-12/23 inhibitors be withheld before elective arthroplasty?",
  }),
  draft(40, {
    title: "Inhibiteurs de JAK : arrêt 3 jours avant",
    statement: "Tofacitinib, baricitinib, upadacitinib et filgotinib sont arrêtés 3 jours avant la chirurgie et repris après cicatrisation (≥ 14 jours).",
    conditions: [drug("L04AF")],
    action: { type: "stop_before", hours: 72, target: "surgery" },
    source: ACR_2022,
    explanations: [ARTHROPLASTY, "Reprise après cicatrisation, sans infection, en général ≥ 14 jours.", "Recoupé (Consensus, septembre 2026) : « In 2022, this guideline was revised to suggest a 3-day preoperative discontinuation period for JAKi » (Harigane et al., Ann Rheum Dis 2025) ; « recent guidelines recommend a 3-day preoperative withdrawal of JAKi » (Yoshida et al., Ann Rheum Dis 2023)."],
    question: "According to the 2022 ACR/AAHKS guideline, how many days before elective arthroplasty should JAK inhibitors (tofacitinib, baricitinib, upadacitinib) be stopped, and when restarted?",
  }),
  draft(41, {
    title: "Corticothérapie au long cours : dose habituelle, pas de supplémentation systématique",
    statement: "La corticothérapie est poursuivie à la dose quotidienne habituelle, sans dose de stress supraphysiologique systématique (arthroplastie programmée).",
    conditions: [drug("H02AB")],
    action: continueIt("Dose habituelle le matin de l'intervention ; pas de dose de stress systématique pour une arthroplastie ; à discuter pour une chirurgie majeure ou en cas d'instabilité hémodynamique."),
    source: ACR_2022,
    explanations: [ARTHROPLASTY],
    divergences: [{ summary: "AAGBI 2020 (insuffisance surrénalienne) : hydrocortisone 100 mg à l'induction chez le patient sous ≥ 5 mg de prednisolone depuis plus de 4 semaines, selon la chirurgie.", source: "Association of Anaesthetists 2020", level: "int" }],
    question: "According to the 2022 ACR/AAHKS guideline and the 2020 Association of Anaesthetists guideline on adrenal insufficiency, should patients on chronic glucocorticoids receive supraphysiologic stress doses at surgery?",
  }),
  draft(42, {
    title: "Immunosuppresseurs du lupus sévère et des greffés : poursuivre",
    statement: "Mycophénolate, azathioprine, ciclosporine et tacrolimus sont poursuivis en cas de lupus sévère ou de greffe (arrêtés 1 semaine avant en cas de lupus non sévère, selon ACR/AAHKS).",
    conditions: [drug("L04AD")],
    action: continueIt("Poursuivre (greffe, lupus sévère) ; lupus non sévère : arrêt 1 semaine avant à discuter avec le rhumatologue."),
    source: ACR_2022,
    explanations: [ARTHROPLASTY],
    question: "According to the 2022 ACR/AAHKS guideline, should mycophenolate, azathioprine, cyclosporine and tacrolimus be continued or withheld in severe and non-severe SLE before elective arthroplasty?",
  }),
  draft(43, {
    title: "Antirétroviraux : ne pas interrompre",
    statement: "Les antirétroviraux sont poursuivis sans interruption ; interactions (ritonavir, cobicistat) à vérifier.",
    conditions: [drug("J05A")],
    action: continueIt("Poursuivre sans omettre de prise ; interactions CYP3A4 (midazolam, fentanyl…)."),
    source: RHEUM_HIV,
    question: "According to the SPAQI 2022 consensus on HIV medications, should antiretrovirals be continued perioperatively?",
  }),
  // --- Opioïdes et dépendances -----------------------------------------------------------------
  draft(44, {
    title: "Buprénorphine : poursuivre",
    statement: "La buprénorphine (substitution ou douleur) est poursuivie ; analgésie multimodale, opioïdes agonistes complets en complément si nécessaire.",
    conditions: [drug("N07BC01")],
    action: continueIt("Poursuivre à la dose habituelle (éventuellement fractionnée) ; analgésie multimodale."),
    source: PSY,
    explanations: ["PAIN 2019 (Goel et al., Br J Anaesth 2019, PMID 31153631) : « The major recommendation of this practice advisory is to continue buprenorphine therapy in the perioperative period. » ; Hitt et al., Anesthesiology 2024 : l'interruption double les besoins en opioïdes (recoupé via Consensus)."],
    divergences: [{ summary: "MAPAR : douleur postopératoire modérée à sévère prévue — arrêt avant la chirurgie selon la dose (≤ 4 mg/j : 24 h ; 4–8 mg/j : 48 h ; 8–12 mg/j : 72 h ; au-delà : addictologue) et relais par un opioïde fort titré.", source: "MAPAR (douleur postopératoire sous buprénorphine)", level: "book" }],
    question: "According to the PAIN 2019 clinical practice advisory (Br J Anaesth 2019) and SPAQI 2022, should buprenorphine be continued perioperatively, and how should postoperative pain be managed?",
  }),
  draft(45, {
    title: "Méthadone : poursuivre",
    statement: "La méthadone est poursuivie à la dose habituelle ; QT.",
    conditions: [drug("N07BC02")],
    action: continueIt("Poursuivre à la dose habituelle (confirmée auprès du prescripteur) ; ECG (QT)."),
    source: PSY,
    question: "According to current guidance, should methadone for opioid use disorder be continued on the day of surgery?",
  }),
  draft(46, {
    title: "Naltrexone orale : arrêt 72 h avant",
    statement: "La naltrexone orale est arrêtée 72 h avant une intervention qui nécessitera des opioïdes.",
    conditions: [drug("N07BB04")],
    action: { type: "stop_before", hours: 72, target: "anaesthesia" },
    source: PSY,
    divergences: [{ summary: "Naltrexone retard injectable : programmer la chirurgie au moins 4 semaines après l'injection.", source: "Pratique courante", level: "int" }],
    question: "According to current guidance (SPAQI 2022, ASRA), how long before surgery should oral naltrexone be stopped, and how should the extended-release injection be managed?",
  }),
  // --- Compléments ---------------------------------------------------------------------------
  draft(47, {
    title: "Millepertuis : arrêt 2 semaines avant",
    statement: "Le millepertuis (inducteur enzymatique, sérotoninergique) est arrêté 2 semaines avant l'intervention.",
    conditions: [drug("N06AX25")],
    action: { type: "stop_before", hours: 336, target: "both" },
    source: SUPPLEMENTS,
    question: "According to the SPAQI 2021 consensus on dietary supplements, how long before surgery should St John's wort be stopped?",
  }),
  draft(48, {
    title: "Ginkgo biloba : arrêt avant l'intervention",
    statement: "Le ginkgo biloba (effet antiplaquettaire) est arrêté avant l'intervention.",
    conditions: [drug("N06DX02")],
    action: { type: "stop_before", hours: 168, target: "surgery" },
    source: SUPPLEMENTS,
    question: "According to the SPAQI 2021 consensus on dietary supplements, how long before surgery should ginkgo biloba be stopped?",
  }),
  // --- Compléments de classes -------------------------------------------------------------------
  draft(49, {
    title: "Hypnotiques au long cours : poursuivre",
    statement: "Zolpidem, zopiclone et hypnotiques benzodiazépiniques pris au long cours sont poursuivis la veille au soir.",
    conditions: [drug("N05C")],
    action: continueIt("Poursuivre la veille au soir ; sédation additive, prudence en cas de SAOS."),
    source: PSY,
    question: "According to the SPAQI 2022 consensus, should chronic hypnotics (zolpidem, zopiclone) be continued the night before surgery?",
  }),
  draft(50, {
    title: "Traitement hormonal de la ménopause (associations) : discuter l'arrêt avant une chirurgie à haut risque thromboembolique",
    statement: "Même conduite que pour les œstrogènes seuls : poursuite en règle, arrêt 4 semaines avant une chirurgie majeure à haut risque à discuter.",
    conditions: [drug("G03F"), { kind: "surgery", attribute: "grade", in: ["major"] }],
    action: { type: "info", text: "Chirurgie majeure : discuter l'arrêt 4 semaines avant, ou thromboprophylaxie adaptée.", target: "surgery" },
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should combined menopausal hormone therapy be stopped before surgery with a high risk of venous thromboembolism?",
  }),
  draft(51, {
    title: "Antiarythmiques de classe I : poursuivre",
    statement: "Flécaïnide et propafénone sont poursuivis ; kaliémie, ECG.",
    conditions: [drug("C01BC")],
    action: continueIt("Poursuivre ; ECG (QRS), kaliémie ; attention aux anesthésiques locaux à forte dose."),
    source: CARDIO,
    question: "According to the SPAQI 2022 consensus on cardiovascular medications, should class I antiarrhythmics (flecainide, propafenone) be continued on the day of surgery?",
  }),
  draft(52, {
    title: "Baclofène et myorelaxants centraux : ne pas interrompre",
    statement: "Le baclofène est poursuivi : son arrêt brutal expose à un sevrage (convulsions, hyperthermie, confusion).",
    conditions: [drug("M03BX")],
    action: continueIt("Poursuivre sans interruption (sevrage grave) ; pompe intrathécale : vérifier le remplissage et la programmation."),
    source: NEURO,
    question: "According to the SPAQI 2022 consensus on neurologic medications, should baclofen (oral or intrathecal) be continued perioperatively?",
  }),
  draft(53, {
    title: "Mémantine : poursuivre",
    statement: "La mémantine est poursuivie.",
    conditions: [drug("N06DX01")],
    action: continueIt("Poursuivre ; prudence avec la kétamine (antagonistes NMDA)."),
    source: NEURO,
    question: "According to the SPAQI 2022 consensus, should memantine be continued before surgery?",
  }),
  draft(54, {
    title: "Fludrocortisone : poursuivre",
    statement: "La fludrocortisone est poursuivie le matin de l'intervention.",
    conditions: [drug("H02AA")],
    action: continueIt("Poursuivre ; insuffisance surrénalienne primaire : supplémentation en hydrocortisone selon l'intervention."),
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, should fludrocortisone be continued on the day of surgery?",
  }),
  draft(55, {
    title: "Desmopressine : poursuivre, natrémie",
    statement: "La desmopressine est poursuivie (sauf énurésie ou nycturie : suspendre) ; natrémie et apports hydriques surveillés.",
    conditions: [drug("H01BA")],
    action: continueIt("Diabète insipide : poursuivre ; énurésie ou nycturie : suspendre la veille ; natrémie."),
    source: ENDO,
    question: "According to the SPAQI 2021 consensus, how should desmopressin be managed before surgery depending on its indication?",
  }),
  draft(56, {
    title: "Hydroxychloroquine : poursuivre",
    statement: "L'hydroxychloroquine est poursuivie pendant la période opératoire.",
    conditions: [drug("P01BA02")],
    action: continueIt("Poursuivre (QT)."),
    source: ACR_2022,
    explanations: [ARTHROPLASTY],
    question: "According to the 2022 ACR/AAHKS guideline, should hydroxychloroquine be continued through elective arthroplasty?",
  }),
  draft(57, {
    title: "Varénicline et substituts nicotiniques : poursuivre",
    statement: "Les traitements d'aide au sevrage tabagique sont poursuivis : l'arrêt du tabac avant la chirurgie est bénéfique.",
    conditions: [drug("N07BA")],
    action: continueIt("Poursuivre ; encourager le sevrage avant la chirurgie."),
    source: PSY,
    question: "According to current perioperative guidance (SPAQI 2022, WHO), should varenicline and nicotine replacement therapy be continued before surgery?",
  }),
  // --- Compléments recoupés via Consensus (septembre 2026) ---------------------------------------
  draft(58, {
    title: "Metformine : poursuivre, sauf insuffisance rénale ou produit de contraste",
    statement: "La metformine est poursuivie ; elle est suspendue le matin de l'intervention en cas d'insuffisance rénale (clairance < 60 mL/min) ou d'injection de produit de contraste ; reprise dès que l'alimentation est reprise et la fonction rénale stable.",
    conditions: [drug("A10BA02")],
    action: continueIt("Poursuivre la metformine ; la suspendre le matin si clairance < 60 mL/min ou produit de contraste ; reprise avec l'alimentation, fonction rénale stable."),
    source: COREMANS_2026,
    explanations: ["Ancienne pratique (Manuel 2020) : arrêt 48 h avant ; la plupart des recommandations 2015–2024 ne l'arrêtent plus sans facteur de risque (revue belge, Acta Anaesthesiol Belg 2026)."],
    question: "According to current guidelines (CPOC 2021, ADA, SPAQI), should metformin be continued on the day of surgery in patients with normal renal function, and when should it be withheld?",
  }),
  draft(59, {
    title: "Metformine avec facteur de risque : suspendre le matin de l'intervention",
    statement: "En cas d'insuffisance rénale (clairance < 60 mL/min) ou d'injection de produit de contraste, la metformine est suspendue le matin de l'intervention.",
    conditions: [drug("A10BA02"), { kind: "value", value: "crcl", op: "<", threshold: 60 }],
    action: { type: "stop_before", hours: 12, target: "both" },
    source: COREMANS_2026,
    explanations: ["Seuil de 60 mL/min retenu par PreOx pour « impaired renal function » : à ajuster à la recommandation suivie (CPOC : DFGe < 60 et produit de contraste)."],
    question: "According to current guidelines (CPOC 2021, ADA, SPAQI), from which renal function threshold should metformin be withheld on the day of surgery?",
  }),
  draft(60, {
    title: "Bévacizumab (anti-VEGF) : 6 à 8 semaines entre la dernière dose et la chirurgie",
    statement: "Une chirurgie programmée a lieu au moins 6 à 8 semaines après la dernière dose de bévacizumab (demi-vie de 20 jours) ; reprise au moins 28 jours après, plaie cicatrisée.",
    conditions: [drug("L01FG")],
    action: { type: "stop_before", hours: 1008, target: "surgery" },
    source: BEVACIZUMAB,
    explanations: ["Reprise ≥ 28 jours après la chirurgie, incision cicatrisée. Décision avec l'oncologue (chirurgie oncologique souvent programmée sur ce délai)."],
    question: "How long before elective surgery should bevacizumab be stopped, and when can it be restarted (SmPC, ESMO)?",
  }),
  draft(61, {
    title: "Inhibiteurs de la BTK : arrêt 3 jours avant une chirurgie à faible risque hémorragique",
    statement: "L'ibrutinib (et les autres inhibiteurs de la BTK) est interrompu 3 jours avant et après une intervention mineure.",
    conditions: [drug("L01EL"), { kind: "surgery", attribute: "bleedingRisk", in: ["minimal", "low"] }],
    action: { type: "stop_before", hours: 72, target: "surgery" },
    source: IBRUTINIB,
    explanations: ["RCP de l'ibrutinib : interruption 3 à 7 jours avant et après la chirurgie selon le type d'intervention et le risque hémorragique."],
    question: "According to the ibrutinib SmPC and current haematology guidance, how many days before and after surgery should BTK inhibitors be withheld depending on bleeding risk?",
  }),
  draft(62, {
    title: "Inhibiteurs de la BTK : arrêt 7 jours avant une chirurgie à haut risque hémorragique",
    statement: "L'ibrutinib est interrompu 7 jours avant et après une chirurgie à haut risque hémorragique.",
    conditions: [drug("L01EL"), { kind: "surgery", attribute: "bleedingRisk", in: ["high"] }],
    action: { type: "stop_before", hours: 168, target: "surgery" },
    source: IBRUTINIB,
    question: "According to the ibrutinib SmPC, how many days before major surgery should BTK inhibitors be withheld?",
  }),
  draft(63, {
    title: "Opioïdes au long cours : poursuivre la dose de base",
    statement: "Le traitement opioïde au long cours est poursuivi, y compris le matin de l'intervention (dose de base), avec une analgésie multimodale et une ALR quand c'est possible.",
    conditions: [drug("N02A")],
    action: continueIt("Poursuivre la dose de base (matin compris), patch en place ; analgésie multimodale, kétamine, ALR ; besoins postopératoires majorés."),
    source: ASER_POQI_2019,
    explanations: ["Recoupé (Consensus) : Crosier et al., Am J Surg 2024 — « Continuing home opioids for chronic opioid users following VHR resulted in less opioid prescribing with no increase in refills. »"],
    question: "According to the ASER/POQI 2019 joint consensus statement, should the baseline opioid regimen of patients on long-term opioid therapy be continued on the day of surgery?",
  }),
  draft(64, {
    title: "Immunothérapie (anti-PD-1, anti-PD-L1, anti-CTLA-4) : bilan endocrinien avant l'intervention",
    statement: "Sous inhibiteur de point de contrôle immunitaire, rechercher une toxicité endocrinienne (thyroïde, surrénales, hypophyse, diabète) et une pneumopathie ou une myocardite avant l'intervention.",
    conditions: [drug("L01FF")],
    action: { type: "exam", exam: "TSH, T4 libre, cortisol de 8 h, glycémie, ionogramme (troponine et ECG si symptômes)", withinDays: 30 },
    source: ICI_REVIEW,
    explanations: ["Recoupé via Consensus (septembre 2026) ; méta-analyse (Zhou et al., Ther Adv Med Oncol 2024) : risque accru d'hypothyroïdie, d'insuffisance surrénalienne et d'hypophysite sous immunothérapie périopératoire."],
    question: "Which preoperative tests are recommended in patients treated with immune checkpoint inhibitors (endocrine, pulmonary, cardiac toxicities), and how should suspected adrenal insufficiency be managed perioperatively?",
  }),
  draft(65, {
    title: "Immunothérapie : hypotension réfractaire, penser à l'insuffisance surrénalienne",
    statement: "Une hypotension peropératoire inexpliquée ou réfractaire sous immunothérapie évoque une insuffisance surrénalienne : hydrocortisone.",
    conditions: [drug("L01FF")],
    action: { type: "info", text: "Hypotension réfractaire, hyponatrémie, hypoglycémie : hydrocortisone 100 mg IV après prélèvement du cortisol.", target: "anaesthesia" },
    source: ICI_REVIEW,
    question: "In a patient on immune checkpoint inhibitors with refractory perioperative hypotension, when should adrenal insufficiency be suspected and hydrocortisone given?",
  }),
  ...([[66, "L04AX04", "Lénalidomide"], [75, "L04AX02", "Thalidomide"], [76, "L04AX06", "Pomalidomide"]] as const).map(([n, atc, name]) =>
    draft(n, {
      title: `${name} : thromboprophylaxie obligatoire`,
      statement: "La chirurgie s'ajoute au risque thromboembolique des immunomodulateurs : thromboprophylaxie par HBPM ; interruption éventuelle décidée avec l'hématologue.",
      conditions: [drug(atc)],
      action: { type: "info", text: "Thromboprophylaxie par HBPM (pas d'aspirine seule) ; interruption éventuelle à décider avec l'hématologue.", target: "surgery" },
      source: IMWG_2008,
      question: "How should lenalidomide or thalidomide be managed around surgery (interruption, thromboprophylaxis), according to IMWG and current haematology guidance?",
    })
  ),
  draft(67, {
    title: "Abiratérone : corticoïde associé et kaliémie",
    statement: "L'abiratérone est poursuivie ; la prednisone associée expose à une insuffisance surrénalienne relative, et l'excès minéralocorticoïde à une hypokaliémie et une HTA.",
    conditions: [drug("L02BX03")],
    action: { type: "exam", exam: "Kaliémie ; prednisone associée à poursuivre (supplémentation selon l'intervention)", withinDays: 30 },
    source: SMPC,
    question: "How should abiraterone and the associated prednisone be managed perioperatively (hypokalaemia, adrenal insufficiency)?",
  }),
  draft(68, {
    title: "Hydroxycarbamide : poursuivre, hémogramme",
    statement: "L'hydroxycarbamide est poursuivie (drépanocytose, syndrome myéloprolifératif) ; hémogramme avant l'intervention.",
    conditions: [drug("L01XX05")],
    action: { type: "exam", exam: "Hémogramme (cytopénies)", withinDays: 30 },
    source: SMPC,
    question: "Should hydroxyurea be continued perioperatively in sickle cell disease or myeloproliferative neoplasms, and which tests are needed?",
  }),
  draft(69, {
    title: "Anagrélide : effet antiagrégant, avis de l'hématologue",
    statement: "L'anagrélide a un effet antiagrégant et cardiovasculaire (palpitations, QT) : décision de poursuite avec l'hématologue ; plaquettes et ECG.",
    conditions: [drug("L01XX35")],
    action: { type: "exam", exam: "Plaquettes, ECG (QT)", withinDays: 30 },
    source: SMPC,
    question: "How should anagrelide be managed before surgery (bleeding risk, thrombotic risk of essential thrombocythaemia)?",
  }),
  draft(70, {
    title: "Mavacamten : FEVG récente, éviter l'hypovolémie",
    statement: "Mavacamten (cardiomyopathie hypertrophique obstructive) : FEVG récente ; éviter hypovolémie et inotropes positifs ; interactions CYP2C19 et CYP3A4.",
    conditions: [drug("C01EB24")],
    action: { type: "exam", exam: "Échocardiographie récente (FEVG ≥ 50 %)", withinDays: 90 },
    source: SMPC,
    question: "How should mavacamten be managed perioperatively (continuation, LVEF check, interactions)?",
  }),
  draft(71, {
    title: "Nintédanib et pirfénidone : fonction respiratoire, risque hémorragique",
    statement: "Antifibrosants pulmonaires : fonction respiratoire récente ; le nintédanib majore le risque hémorragique et gêne la cicatrisation.",
    conditions: [drug("L04AX05")],
    action: { type: "info", text: "EFR et gazométrie récentes ; nintédanib : risque hémorragique, discussion d'un arrêt avant une chirurgie majeure avec le pneumologue.", target: "both" },
    source: SMPC,
    question: "Should nintedanib or pirfenidone be withheld before surgery, and for how long?",
  }),
  draft(72, {
    title: "Testostérone : hématocrite, risque thromboembolique",
    statement: "La testostérone est poursuivie ; polyglobulie et risque thromboembolique à intégrer.",
    conditions: [drug("G03B")],
    action: { type: "exam", exam: "Hémogramme (hématocrite)", withinDays: 90 },
    source: SMPC,
    question: "Should testosterone therapy be continued before surgery, and what are the perioperative thromboembolic considerations?",
  }),
  draft(73, {
    title: "Disulfirame : pas d'antiseptique ni de médicament alcoolique",
    statement: "Sous disulfirame, éviter l'exposition à l'alcool (antiseptiques alcooliques en grande quantité, solutions buvables alcoolisées) ; effet antabuse.",
    conditions: [drug("N07BB01")],
    action: { type: "info", text: "Préférer un antiseptique non alcoolique si possible ; pas de médicament contenant de l'alcool ; hépatotoxicité.", target: "both" },
    source: SMPC,
    question: "Should disulfiram be stopped before surgery, and should alcohol-based skin antiseptics be avoided?",
  }),
  draft(74, {
    title: "Nalméfène : arrêt une semaine avant si des opioïdes sont prévus",
    statement: "Antagoniste opioïde : arrêter le nalméfène une semaine avant une intervention qui nécessitera des opioïdes.",
    conditions: [drug("N07BB05")],
    action: { type: "stop_before", hours: 168, target: "anaesthesia" },
    source: SMPC,
    question: "According to the nalmefene (Selincro) SmPC, how long before an anticipated opioid use should nalmefene be stopped?",
  }),
];

/** The older proposals (Manuel 2020) a more recent rule of this file replaces. */
const manualId = (title: string) => {
  const r = MANUAL_RULES.find((x) => x.title === title);
  if (!r) throw new Error(`Règle du manuel introuvable : ${title}`);
  return r.id;
};
export const TREATMENT_SUPERSEDES: Record<string, string[]> = {
  [id(13)]: [manualId("Myasthénie : anticholinestérasique arrêté 6 h avant")],
  [id(41)]: [manualId("Corticothérapie : maintenir")],
  [id(58)]: [manualId("Metformine : arrêt 48 h avant")],
  [id(59)]: [manualId("Metformine : arrêt 48 h avant")],
};
